/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Assignment,
  BasicUser,
  BulkUpdateAssignmentDatesRequestInner,
  CreateAssignmentRequest,
  EditAssignmentRequest,
  Progress,
} from '../models/index';
import {
    AssignmentFromJSON,
    AssignmentToJSON,
    BasicUserFromJSON,
    BasicUserToJSON,
    BulkUpdateAssignmentDatesRequestInnerFromJSON,
    BulkUpdateAssignmentDatesRequestInnerToJSON,
    CreateAssignmentRequestFromJSON,
    CreateAssignmentRequestToJSON,
    EditAssignmentRequestFromJSON,
    EditAssignmentRequestToJSON,
    ProgressFromJSON,
    ProgressToJSON,
} from '../models/index';

export interface BulkUpdateAssignmentDatesRequest {
    courseId: number;
    bulkUpdateAssignmentDatesRequestInner: Array<BulkUpdateAssignmentDatesRequestInner>;
}

export interface CreateAssignmentOperationRequest {
    courseId: number;
    createAssignmentRequest: CreateAssignmentRequest;
}

export interface DeleteAssignmentRequest {
    courseId: number;
    id: number;
}

export interface DuplicateAssignmentRequest {
    courseId: number;
    assignmentId: number;
    resultType?: DuplicateAssignmentResultTypeEnum;
}

export interface EditAssignmentOperationRequest {
    courseId: number;
    id: number;
    editAssignmentRequest: EditAssignmentRequest;
}

export interface GetAssignmentRequest {
    courseId: number;
    id: number;
    include?: Array<GetAssignmentIncludeEnum>;
    overrideAssignmentDates?: boolean;
    needsGradingCountBySection?: boolean;
    allDates?: boolean;
}

export interface ListAssignmentGroupMembersForUserRequest {
    courseId: number;
    assignmentId: number;
    userId: string;
}

export interface ListAssignmentsForCourseRequest {
    courseId: number;
    include?: Array<ListAssignmentsForCourseIncludeEnum>;
    searchTerm?: string;
    overrideAssignmentDates?: boolean;
    needsGradingCountBySection?: boolean;
    bucket?: ListAssignmentsForCourseBucketEnum;
    assignmentIds?: Array<number>;
    orderBy?: ListAssignmentsForCourseOrderByEnum;
    postToSis?: boolean;
    newQuizzes?: boolean;
}

export interface ListAssignmentsForGroupRequest {
    courseId: number;
    assignmentGroupId: number;
    include?: Array<ListAssignmentsForGroupIncludeEnum>;
    searchTerm?: string;
    overrideAssignmentDates?: boolean;
    needsGradingCountBySection?: boolean;
    bucket?: ListAssignmentsForGroupBucketEnum;
    assignmentIds?: Array<number>;
    orderBy?: ListAssignmentsForGroupOrderByEnum;
    postToSis?: boolean;
    newQuizzes?: boolean;
}

export interface ListAssignmentsForUserRequest {
    userId: string;
    courseId: number;
    include?: Array<ListAssignmentsForUserIncludeEnum>;
    searchTerm?: string;
    overrideAssignmentDates?: boolean;
    needsGradingCountBySection?: boolean;
    bucket?: ListAssignmentsForUserBucketEnum;
    assignmentIds?: Array<number>;
    orderBy?: ListAssignmentsForUserOrderByEnum;
    postToSis?: boolean;
    newQuizzes?: boolean;
}

/**
 * AssignmentsApi - interface
 * 
 * @export
 * @interface AssignmentsApiInterface
 */
export interface AssignmentsApiInterface {
    /**
     * Update due dates and availability dates for multiple assignments in a course. Accepts a JSON array of objects containing \'id\' and \'all_dates\' (array of AssignmentDate structures). Performs update in a background job.
     * @summary Bulk update assignment dates
     * @param {number} courseId ID of the course.
     * @param {Array<BulkUpdateAssignmentDatesRequestInner>} bulkUpdateAssignmentDatesRequestInner 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    bulkUpdateAssignmentDatesRaw(requestParameters: BulkUpdateAssignmentDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Progress>>;

    /**
     * Update due dates and availability dates for multiple assignments in a course. Accepts a JSON array of objects containing \'id\' and \'all_dates\' (array of AssignmentDate structures). Performs update in a background job.
     * Bulk update assignment dates
     */
    bulkUpdateAssignmentDates(requestParameters: BulkUpdateAssignmentDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Progress>;

    /**
     * Create a new assignment for this course. The assignment is created in the active state.
     * @summary Create an assignment
     * @param {number} courseId ID of the course.
     * @param {CreateAssignmentRequest} createAssignmentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    createAssignmentRaw(requestParameters: CreateAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>>;

    /**
     * Create a new assignment for this course. The assignment is created in the active state.
     * Create an assignment
     */
    createAssignment(requestParameters: CreateAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment>;

    /**
     * Delete the given assignment.
     * @summary Delete an assignment
     * @param {number} courseId ID of the course.
     * @param {number} id ID of the assignment to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    deleteAssignmentRaw(requestParameters: DeleteAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>>;

    /**
     * Delete the given assignment.
     * Delete an assignment
     */
    deleteAssignment(requestParameters: DeleteAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment>;

    /**
     * Duplicate an assignment and return the new assignment. Optionally returns a Quiz object if result_type=Quiz and New Quizzes are enabled.
     * @summary Duplicate assignment
     * @param {number} courseId ID of the course.
     * @param {number} assignmentId ID of the assignment to duplicate.
     * @param {'Quiz'} [resultType] If \&#39;Quiz\&#39; and New Quizzes are enabled, returns a Quiz object instead.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    duplicateAssignmentRaw(requestParameters: DuplicateAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>>;

    /**
     * Duplicate an assignment and return the new assignment. Optionally returns a Quiz object if result_type=Quiz and New Quizzes are enabled.
     * Duplicate assignment
     */
    duplicateAssignment(requestParameters: DuplicateAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment>;

    /**
     * Modify an existing assignment. If assignment[assignment_overrides] is provided, all existing overrides are deleted and replaced by the new ones.
     * @summary Edit an assignment
     * @param {number} courseId ID of the course.
     * @param {number} id ID of the assignment.
     * @param {EditAssignmentRequest} editAssignmentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    editAssignmentRaw(requestParameters: EditAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>>;

    /**
     * Modify an existing assignment. If assignment[assignment_overrides] is provided, all existing overrides are deleted and replaced by the new ones.
     * Edit an assignment
     */
    editAssignment(requestParameters: EditAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment>;

    /**
     * Returns the assignment with the given id.
     * @summary Get a single assignment
     * @param {number} courseId ID of the course.
     * @param {number} id ID of the assignment.
     * @param {Array<'submission' | 'assignment_visibility' | 'all_dates' | 'overrides' | 'observed_users' | 'can_edit' | 'score_statistics' | 'ab_guid'>} [include] Associations to include with the assignment.
     * @param {boolean} [overrideAssignmentDates] Apply assignment overrides. Defaults to true.
     * @param {boolean} [needsGradingCountBySection] Split needs_grading_count by section. Defaults to false.
     * @param {boolean} [allDates] If true, include all dates associated with the assignment, if applicable.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    getAssignmentRaw(requestParameters: GetAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>>;

    /**
     * Returns the assignment with the given id.
     * Get a single assignment
     */
    getAssignment(requestParameters: GetAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment>;

    /**
     * Returns student ids and names for the group the specified user is in for the given assignment.
     * @summary List group members for a student on an assignment
     * @param {number} courseId ID of the course.
     * @param {number} assignmentId ID of the assignment.
     * @param {string} userId ID of the user.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    listAssignmentGroupMembersForUserRaw(requestParameters: ListAssignmentGroupMembersForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BasicUser>>>;

    /**
     * Returns student ids and names for the group the specified user is in for the given assignment.
     * List group members for a student on an assignment
     */
    listAssignmentGroupMembersForUser(requestParameters: ListAssignmentGroupMembersForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BasicUser>>;

    /**
     * Returns the paginated list of assignments for the current course.
     * @summary List assignments
     * @param {number} courseId ID of the course.
     * @param {Array<'submission' | 'assignment_visibility' | 'all_dates' | 'overrides' | 'observed_users' | 'can_edit' | 'score_statistics' | 'ab_guid'>} [include] Associations to include with the assignment.
     * @param {string} [searchTerm] Partial title of assignments to match.
     * @param {boolean} [overrideAssignmentDates] Apply assignment overrides. Defaults to true.
     * @param {boolean} [needsGradingCountBySection] Split needs_grading_count by section. Defaults to false.
     * @param {'past' | 'overdue' | 'undated' | 'ungraded' | 'unsubmitted' | 'upcoming' | 'future'} [bucket] Filter assignments by due date and submission status.
     * @param {Array<number>} [assignmentIds] Return only specified assignment IDs.
     * @param {'position' | 'name' | 'due_at'} [orderBy] Order of assignments. Defaults to position.
     * @param {boolean} [postToSis] Filter assignments based on post_to_sis flag.
     * @param {boolean} [newQuizzes] Return only New Quizzes assignments.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    listAssignmentsForCourseRaw(requestParameters: ListAssignmentsForCourseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assignment>>>;

    /**
     * Returns the paginated list of assignments for the current course.
     * List assignments
     */
    listAssignmentsForCourse(requestParameters: ListAssignmentsForCourseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assignment>>;

    /**
     * Returns the paginated list of assignments for the assignment group.
     * @summary List assignments for assignment group
     * @param {number} courseId ID of the course.
     * @param {number} assignmentGroupId ID of the assignment group.
     * @param {Array<'submission' | 'assignment_visibility' | 'all_dates' | 'overrides' | 'observed_users' | 'can_edit' | 'score_statistics' | 'ab_guid'>} [include] Associations to include with the assignment.
     * @param {string} [searchTerm] Partial title of assignments to match.
     * @param {boolean} [overrideAssignmentDates] Apply assignment overrides. Defaults to true.
     * @param {boolean} [needsGradingCountBySection] Split needs_grading_count by section. Defaults to false.
     * @param {'past' | 'overdue' | 'undated' | 'ungraded' | 'unsubmitted' | 'upcoming' | 'future'} [bucket] Filter assignments by due date and submission status.
     * @param {Array<number>} [assignmentIds] Return only specified assignment IDs.
     * @param {'position' | 'name' | 'due_at'} [orderBy] Order of assignments. Defaults to position.
     * @param {boolean} [postToSis] Filter assignments based on post_to_sis flag.
     * @param {boolean} [newQuizzes] Return only New Quizzes assignments.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    listAssignmentsForGroupRaw(requestParameters: ListAssignmentsForGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assignment>>>;

    /**
     * Returns the paginated list of assignments for the assignment group.
     * List assignments for assignment group
     */
    listAssignmentsForGroup(requestParameters: ListAssignmentsForGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assignment>>;

    /**
     * Returns the paginated list of assignments for the specified user if the current user has rights to view. See List assignments for valid arguments.
     * @summary List assignments for user
     * @param {string} userId ID of the user.
     * @param {number} courseId ID of the course.
     * @param {Array<'submission' | 'assignment_visibility' | 'all_dates' | 'overrides' | 'observed_users' | 'can_edit' | 'score_statistics' | 'ab_guid'>} [include] Associations to include with the assignment.
     * @param {string} [searchTerm] Partial title of assignments to match.
     * @param {boolean} [overrideAssignmentDates] Apply assignment overrides. Defaults to true.
     * @param {boolean} [needsGradingCountBySection] Split needs_grading_count by section. Defaults to false.
     * @param {'past' | 'overdue' | 'undated' | 'ungraded' | 'unsubmitted' | 'upcoming' | 'future'} [bucket] Filter assignments by due date and submission status.
     * @param {Array<number>} [assignmentIds] Return only specified assignment IDs.
     * @param {'position' | 'name' | 'due_at'} [orderBy] Order of assignments. Defaults to position.
     * @param {boolean} [postToSis] Filter assignments based on post_to_sis flag.
     * @param {boolean} [newQuizzes] Return only New Quizzes assignments.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssignmentsApiInterface
     */
    listAssignmentsForUserRaw(requestParameters: ListAssignmentsForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assignment>>>;

    /**
     * Returns the paginated list of assignments for the specified user if the current user has rights to view. See List assignments for valid arguments.
     * List assignments for user
     */
    listAssignmentsForUser(requestParameters: ListAssignmentsForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assignment>>;

}

/**
 * 
 */
export class AssignmentsApi extends runtime.BaseAPI implements AssignmentsApiInterface {

    /**
     * Update due dates and availability dates for multiple assignments in a course. Accepts a JSON array of objects containing \'id\' and \'all_dates\' (array of AssignmentDate structures). Performs update in a background job.
     * Bulk update assignment dates
     */
    async bulkUpdateAssignmentDatesRaw(requestParameters: BulkUpdateAssignmentDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Progress>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling bulkUpdateAssignmentDates().'
            );
        }

        if (requestParameters['bulkUpdateAssignmentDatesRequestInner'] == null) {
            throw new runtime.RequiredError(
                'bulkUpdateAssignmentDatesRequestInner',
                'Required parameter "bulkUpdateAssignmentDatesRequestInner" was null or undefined when calling bulkUpdateAssignmentDates().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignments/bulk_update`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['bulkUpdateAssignmentDatesRequestInner']!.map(BulkUpdateAssignmentDatesRequestInnerToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProgressFromJSON(jsonValue));
    }

    /**
     * Update due dates and availability dates for multiple assignments in a course. Accepts a JSON array of objects containing \'id\' and \'all_dates\' (array of AssignmentDate structures). Performs update in a background job.
     * Bulk update assignment dates
     */
    async bulkUpdateAssignmentDates(requestParameters: BulkUpdateAssignmentDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Progress> {
        const response = await this.bulkUpdateAssignmentDatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new assignment for this course. The assignment is created in the active state.
     * Create an assignment
     */
    async createAssignmentRaw(requestParameters: CreateAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling createAssignment().'
            );
        }

        if (requestParameters['createAssignmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createAssignmentRequest',
                'Required parameter "createAssignmentRequest" was null or undefined when calling createAssignment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignments`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAssignmentRequestToJSON(requestParameters['createAssignmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssignmentFromJSON(jsonValue));
    }

    /**
     * Create a new assignment for this course. The assignment is created in the active state.
     * Create an assignment
     */
    async createAssignment(requestParameters: CreateAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment> {
        const response = await this.createAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete the given assignment.
     * Delete an assignment
     */
    async deleteAssignmentRaw(requestParameters: DeleteAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling deleteAssignment().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAssignment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignments/{id}`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssignmentFromJSON(jsonValue));
    }

    /**
     * Delete the given assignment.
     * Delete an assignment
     */
    async deleteAssignment(requestParameters: DeleteAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment> {
        const response = await this.deleteAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Duplicate an assignment and return the new assignment. Optionally returns a Quiz object if result_type=Quiz and New Quizzes are enabled.
     * Duplicate assignment
     */
    async duplicateAssignmentRaw(requestParameters: DuplicateAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling duplicateAssignment().'
            );
        }

        if (requestParameters['assignmentId'] == null) {
            throw new runtime.RequiredError(
                'assignmentId',
                'Required parameter "assignmentId" was null or undefined when calling duplicateAssignment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['resultType'] != null) {
            queryParameters['result_type'] = requestParameters['resultType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignments/{assignment_id}/duplicate`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))).replace(`{${"assignment_id"}}`, encodeURIComponent(String(requestParameters['assignmentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssignmentFromJSON(jsonValue));
    }

    /**
     * Duplicate an assignment and return the new assignment. Optionally returns a Quiz object if result_type=Quiz and New Quizzes are enabled.
     * Duplicate assignment
     */
    async duplicateAssignment(requestParameters: DuplicateAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment> {
        const response = await this.duplicateAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Modify an existing assignment. If assignment[assignment_overrides] is provided, all existing overrides are deleted and replaced by the new ones.
     * Edit an assignment
     */
    async editAssignmentRaw(requestParameters: EditAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling editAssignment().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling editAssignment().'
            );
        }

        if (requestParameters['editAssignmentRequest'] == null) {
            throw new runtime.RequiredError(
                'editAssignmentRequest',
                'Required parameter "editAssignmentRequest" was null or undefined when calling editAssignment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignments/{id}`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EditAssignmentRequestToJSON(requestParameters['editAssignmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssignmentFromJSON(jsonValue));
    }

    /**
     * Modify an existing assignment. If assignment[assignment_overrides] is provided, all existing overrides are deleted and replaced by the new ones.
     * Edit an assignment
     */
    async editAssignment(requestParameters: EditAssignmentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment> {
        const response = await this.editAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the assignment with the given id.
     * Get a single assignment
     */
    async getAssignmentRaw(requestParameters: GetAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Assignment>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling getAssignment().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAssignment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['include'] != null) {
            queryParameters['include[]'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['overrideAssignmentDates'] != null) {
            queryParameters['override_assignment_dates'] = requestParameters['overrideAssignmentDates'];
        }

        if (requestParameters['needsGradingCountBySection'] != null) {
            queryParameters['needs_grading_count_by_section'] = requestParameters['needsGradingCountBySection'];
        }

        if (requestParameters['allDates'] != null) {
            queryParameters['all_dates'] = requestParameters['allDates'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignments/{id}`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssignmentFromJSON(jsonValue));
    }

    /**
     * Returns the assignment with the given id.
     * Get a single assignment
     */
    async getAssignment(requestParameters: GetAssignmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Assignment> {
        const response = await this.getAssignmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns student ids and names for the group the specified user is in for the given assignment.
     * List group members for a student on an assignment
     */
    async listAssignmentGroupMembersForUserRaw(requestParameters: ListAssignmentGroupMembersForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BasicUser>>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling listAssignmentGroupMembersForUser().'
            );
        }

        if (requestParameters['assignmentId'] == null) {
            throw new runtime.RequiredError(
                'assignmentId',
                'Required parameter "assignmentId" was null or undefined when calling listAssignmentGroupMembersForUser().'
            );
        }

        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listAssignmentGroupMembersForUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignments/{assignment_id}/users/{user_id}/group_members`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))).replace(`{${"assignment_id"}}`, encodeURIComponent(String(requestParameters['assignmentId']))).replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BasicUserFromJSON));
    }

    /**
     * Returns student ids and names for the group the specified user is in for the given assignment.
     * List group members for a student on an assignment
     */
    async listAssignmentGroupMembersForUser(requestParameters: ListAssignmentGroupMembersForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BasicUser>> {
        const response = await this.listAssignmentGroupMembersForUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the paginated list of assignments for the current course.
     * List assignments
     */
    async listAssignmentsForCourseRaw(requestParameters: ListAssignmentsForCourseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assignment>>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling listAssignmentsForCourse().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['include'] != null) {
            queryParameters['include[]'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['searchTerm'] != null) {
            queryParameters['search_term'] = requestParameters['searchTerm'];
        }

        if (requestParameters['overrideAssignmentDates'] != null) {
            queryParameters['override_assignment_dates'] = requestParameters['overrideAssignmentDates'];
        }

        if (requestParameters['needsGradingCountBySection'] != null) {
            queryParameters['needs_grading_count_by_section'] = requestParameters['needsGradingCountBySection'];
        }

        if (requestParameters['bucket'] != null) {
            queryParameters['bucket'] = requestParameters['bucket'];
        }

        if (requestParameters['assignmentIds'] != null) {
            queryParameters['assignment_ids[]'] = requestParameters['assignmentIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['postToSis'] != null) {
            queryParameters['post_to_sis'] = requestParameters['postToSis'];
        }

        if (requestParameters['newQuizzes'] != null) {
            queryParameters['new_quizzes'] = requestParameters['newQuizzes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignments`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssignmentFromJSON));
    }

    /**
     * Returns the paginated list of assignments for the current course.
     * List assignments
     */
    async listAssignmentsForCourse(requestParameters: ListAssignmentsForCourseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assignment>> {
        const response = await this.listAssignmentsForCourseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the paginated list of assignments for the assignment group.
     * List assignments for assignment group
     */
    async listAssignmentsForGroupRaw(requestParameters: ListAssignmentsForGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assignment>>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling listAssignmentsForGroup().'
            );
        }

        if (requestParameters['assignmentGroupId'] == null) {
            throw new runtime.RequiredError(
                'assignmentGroupId',
                'Required parameter "assignmentGroupId" was null or undefined when calling listAssignmentsForGroup().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['include'] != null) {
            queryParameters['include[]'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['searchTerm'] != null) {
            queryParameters['search_term'] = requestParameters['searchTerm'];
        }

        if (requestParameters['overrideAssignmentDates'] != null) {
            queryParameters['override_assignment_dates'] = requestParameters['overrideAssignmentDates'];
        }

        if (requestParameters['needsGradingCountBySection'] != null) {
            queryParameters['needs_grading_count_by_section'] = requestParameters['needsGradingCountBySection'];
        }

        if (requestParameters['bucket'] != null) {
            queryParameters['bucket'] = requestParameters['bucket'];
        }

        if (requestParameters['assignmentIds'] != null) {
            queryParameters['assignment_ids[]'] = requestParameters['assignmentIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['postToSis'] != null) {
            queryParameters['post_to_sis'] = requestParameters['postToSis'];
        }

        if (requestParameters['newQuizzes'] != null) {
            queryParameters['new_quizzes'] = requestParameters['newQuizzes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/assignment_groups/{assignment_group_id}/assignments`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))).replace(`{${"assignment_group_id"}}`, encodeURIComponent(String(requestParameters['assignmentGroupId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssignmentFromJSON));
    }

    /**
     * Returns the paginated list of assignments for the assignment group.
     * List assignments for assignment group
     */
    async listAssignmentsForGroup(requestParameters: ListAssignmentsForGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assignment>> {
        const response = await this.listAssignmentsForGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the paginated list of assignments for the specified user if the current user has rights to view. See List assignments for valid arguments.
     * List assignments for user
     */
    async listAssignmentsForUserRaw(requestParameters: ListAssignmentsForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Assignment>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling listAssignmentsForUser().'
            );
        }

        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling listAssignmentsForUser().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['include'] != null) {
            queryParameters['include[]'] = requestParameters['include']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['searchTerm'] != null) {
            queryParameters['search_term'] = requestParameters['searchTerm'];
        }

        if (requestParameters['overrideAssignmentDates'] != null) {
            queryParameters['override_assignment_dates'] = requestParameters['overrideAssignmentDates'];
        }

        if (requestParameters['needsGradingCountBySection'] != null) {
            queryParameters['needs_grading_count_by_section'] = requestParameters['needsGradingCountBySection'];
        }

        if (requestParameters['bucket'] != null) {
            queryParameters['bucket'] = requestParameters['bucket'];
        }

        if (requestParameters['assignmentIds'] != null) {
            queryParameters['assignment_ids[]'] = requestParameters['assignmentIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['orderBy'] != null) {
            queryParameters['order_by'] = requestParameters['orderBy'];
        }

        if (requestParameters['postToSis'] != null) {
            queryParameters['post_to_sis'] = requestParameters['postToSis'];
        }

        if (requestParameters['newQuizzes'] != null) {
            queryParameters['new_quizzes'] = requestParameters['newQuizzes'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/users/{user_id}/courses/{course_id}/assignments`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))).replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssignmentFromJSON));
    }

    /**
     * Returns the paginated list of assignments for the specified user if the current user has rights to view. See List assignments for valid arguments.
     * List assignments for user
     */
    async listAssignmentsForUser(requestParameters: ListAssignmentsForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Assignment>> {
        const response = await this.listAssignmentsForUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const DuplicateAssignmentResultTypeEnum = {
    Quiz: 'Quiz'
} as const;
export type DuplicateAssignmentResultTypeEnum = typeof DuplicateAssignmentResultTypeEnum[keyof typeof DuplicateAssignmentResultTypeEnum];
/**
 * @export
 */
export const GetAssignmentIncludeEnum = {
    Submission: 'submission',
    AssignmentVisibility: 'assignment_visibility',
    AllDates: 'all_dates',
    Overrides: 'overrides',
    ObservedUsers: 'observed_users',
    CanEdit: 'can_edit',
    ScoreStatistics: 'score_statistics',
    AbGuid: 'ab_guid'
} as const;
export type GetAssignmentIncludeEnum = typeof GetAssignmentIncludeEnum[keyof typeof GetAssignmentIncludeEnum];
/**
 * @export
 */
export const ListAssignmentsForCourseIncludeEnum = {
    Submission: 'submission',
    AssignmentVisibility: 'assignment_visibility',
    AllDates: 'all_dates',
    Overrides: 'overrides',
    ObservedUsers: 'observed_users',
    CanEdit: 'can_edit',
    ScoreStatistics: 'score_statistics',
    AbGuid: 'ab_guid'
} as const;
export type ListAssignmentsForCourseIncludeEnum = typeof ListAssignmentsForCourseIncludeEnum[keyof typeof ListAssignmentsForCourseIncludeEnum];
/**
 * @export
 */
export const ListAssignmentsForCourseBucketEnum = {
    Past: 'past',
    Overdue: 'overdue',
    Undated: 'undated',
    Ungraded: 'ungraded',
    Unsubmitted: 'unsubmitted',
    Upcoming: 'upcoming',
    Future: 'future'
} as const;
export type ListAssignmentsForCourseBucketEnum = typeof ListAssignmentsForCourseBucketEnum[keyof typeof ListAssignmentsForCourseBucketEnum];
/**
 * @export
 */
export const ListAssignmentsForCourseOrderByEnum = {
    Position: 'position',
    Name: 'name',
    DueAt: 'due_at'
} as const;
export type ListAssignmentsForCourseOrderByEnum = typeof ListAssignmentsForCourseOrderByEnum[keyof typeof ListAssignmentsForCourseOrderByEnum];
/**
 * @export
 */
export const ListAssignmentsForGroupIncludeEnum = {
    Submission: 'submission',
    AssignmentVisibility: 'assignment_visibility',
    AllDates: 'all_dates',
    Overrides: 'overrides',
    ObservedUsers: 'observed_users',
    CanEdit: 'can_edit',
    ScoreStatistics: 'score_statistics',
    AbGuid: 'ab_guid'
} as const;
export type ListAssignmentsForGroupIncludeEnum = typeof ListAssignmentsForGroupIncludeEnum[keyof typeof ListAssignmentsForGroupIncludeEnum];
/**
 * @export
 */
export const ListAssignmentsForGroupBucketEnum = {
    Past: 'past',
    Overdue: 'overdue',
    Undated: 'undated',
    Ungraded: 'ungraded',
    Unsubmitted: 'unsubmitted',
    Upcoming: 'upcoming',
    Future: 'future'
} as const;
export type ListAssignmentsForGroupBucketEnum = typeof ListAssignmentsForGroupBucketEnum[keyof typeof ListAssignmentsForGroupBucketEnum];
/**
 * @export
 */
export const ListAssignmentsForGroupOrderByEnum = {
    Position: 'position',
    Name: 'name',
    DueAt: 'due_at'
} as const;
export type ListAssignmentsForGroupOrderByEnum = typeof ListAssignmentsForGroupOrderByEnum[keyof typeof ListAssignmentsForGroupOrderByEnum];
/**
 * @export
 */
export const ListAssignmentsForUserIncludeEnum = {
    Submission: 'submission',
    AssignmentVisibility: 'assignment_visibility',
    AllDates: 'all_dates',
    Overrides: 'overrides',
    ObservedUsers: 'observed_users',
    CanEdit: 'can_edit',
    ScoreStatistics: 'score_statistics',
    AbGuid: 'ab_guid'
} as const;
export type ListAssignmentsForUserIncludeEnum = typeof ListAssignmentsForUserIncludeEnum[keyof typeof ListAssignmentsForUserIncludeEnum];
/**
 * @export
 */
export const ListAssignmentsForUserBucketEnum = {
    Past: 'past',
    Overdue: 'overdue',
    Undated: 'undated',
    Ungraded: 'ungraded',
    Unsubmitted: 'unsubmitted',
    Upcoming: 'upcoming',
    Future: 'future'
} as const;
export type ListAssignmentsForUserBucketEnum = typeof ListAssignmentsForUserBucketEnum[keyof typeof ListAssignmentsForUserBucketEnum];
/**
 * @export
 */
export const ListAssignmentsForUserOrderByEnum = {
    Position: 'position',
    Name: 'name',
    DueAt: 'due_at'
} as const;
export type ListAssignmentsForUserOrderByEnum = typeof ListAssignmentsForUserOrderByEnum[keyof typeof ListAssignmentsForUserOrderByEnum];
