/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1CoursesCourseIdFilesQuotaGet200Response,
} from '../models/index';
import {
    ApiV1CoursesCourseIdFilesQuotaGet200ResponseFromJSON,
    ApiV1CoursesCourseIdFilesQuotaGet200ResponseToJSON,
} from '../models/index';

export interface ApiV1CoursesCourseIdFilesQuotaGetRequest {
    courseId: number;
}

export interface ApiV1GroupsGroupIdFilesQuotaGetRequest {
    groupId: number;
}

export interface ApiV1UsersUserIdFilesQuotaGetRequest {
    userId: number;
}

/**
 * FilesApi - interface
 * 
 * @export
 * @interface FilesApiInterface
 */
export interface FilesApiInterface {
    /**
     * Returns the total and used storage quota for the specified course.
     * @summary Get quota information for a course
     * @param {number} courseId ID of the course
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    apiV1CoursesCourseIdFilesQuotaGetRaw(requestParameters: ApiV1CoursesCourseIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1CoursesCourseIdFilesQuotaGet200Response>>;

    /**
     * Returns the total and used storage quota for the specified course.
     * Get quota information for a course
     */
    apiV1CoursesCourseIdFilesQuotaGet(requestParameters: ApiV1CoursesCourseIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1CoursesCourseIdFilesQuotaGet200Response>;

    /**
     * Returns the total and used storage quota for the specified group.
     * @summary Get quota information for a group
     * @param {number} groupId ID of the group
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    apiV1GroupsGroupIdFilesQuotaGetRaw(requestParameters: ApiV1GroupsGroupIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1CoursesCourseIdFilesQuotaGet200Response>>;

    /**
     * Returns the total and used storage quota for the specified group.
     * Get quota information for a group
     */
    apiV1GroupsGroupIdFilesQuotaGet(requestParameters: ApiV1GroupsGroupIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1CoursesCourseIdFilesQuotaGet200Response>;

    /**
     * Returns the total and used storage quota for the specified user.
     * @summary Get quota information for a user
     * @param {number} userId ID of the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FilesApiInterface
     */
    apiV1UsersUserIdFilesQuotaGetRaw(requestParameters: ApiV1UsersUserIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1CoursesCourseIdFilesQuotaGet200Response>>;

    /**
     * Returns the total and used storage quota for the specified user.
     * Get quota information for a user
     */
    apiV1UsersUserIdFilesQuotaGet(requestParameters: ApiV1UsersUserIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1CoursesCourseIdFilesQuotaGet200Response>;

}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI implements FilesApiInterface {

    /**
     * Returns the total and used storage quota for the specified course.
     * Get quota information for a course
     */
    async apiV1CoursesCourseIdFilesQuotaGetRaw(requestParameters: ApiV1CoursesCourseIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1CoursesCourseIdFilesQuotaGet200Response>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling apiV1CoursesCourseIdFilesQuotaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/files/quota`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1CoursesCourseIdFilesQuotaGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the total and used storage quota for the specified course.
     * Get quota information for a course
     */
    async apiV1CoursesCourseIdFilesQuotaGet(requestParameters: ApiV1CoursesCourseIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1CoursesCourseIdFilesQuotaGet200Response> {
        const response = await this.apiV1CoursesCourseIdFilesQuotaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the total and used storage quota for the specified group.
     * Get quota information for a group
     */
    async apiV1GroupsGroupIdFilesQuotaGetRaw(requestParameters: ApiV1GroupsGroupIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1CoursesCourseIdFilesQuotaGet200Response>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling apiV1GroupsGroupIdFilesQuotaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/groups/{group_id}/files/quota`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1CoursesCourseIdFilesQuotaGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the total and used storage quota for the specified group.
     * Get quota information for a group
     */
    async apiV1GroupsGroupIdFilesQuotaGet(requestParameters: ApiV1GroupsGroupIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1CoursesCourseIdFilesQuotaGet200Response> {
        const response = await this.apiV1GroupsGroupIdFilesQuotaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the total and used storage quota for the specified user.
     * Get quota information for a user
     */
    async apiV1UsersUserIdFilesQuotaGetRaw(requestParameters: ApiV1UsersUserIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1CoursesCourseIdFilesQuotaGet200Response>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiV1UsersUserIdFilesQuotaGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/users/{user_id}/files/quota`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1CoursesCourseIdFilesQuotaGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the total and used storage quota for the specified user.
     * Get quota information for a user
     */
    async apiV1UsersUserIdFilesQuotaGet(requestParameters: ApiV1UsersUserIdFilesQuotaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1CoursesCourseIdFilesQuotaGet200Response> {
        const response = await this.apiV1UsersUserIdFilesQuotaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
