/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Error4,
  Page,
} from '../models/index';
import {
    Error4FromJSON,
    Error4ToJSON,
    PageFromJSON,
    PageToJSON,
} from '../models/index';

export interface ApiV1CoursesCourseIdFrontPageGetRequest {
    courseId: number;
}

export interface ApiV1GroupsGroupIdFrontPageGetRequest {
    groupId: number;
}

/**
 * PagesApi - interface
 * 
 * @export
 * @interface PagesApiInterface
 */
export interface PagesApiInterface {
    /**
     * Retrieve the content of the front page for a course.
     * @summary Show front page
     * @param {number} courseId ID of the course
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PagesApiInterface
     */
    apiV1CoursesCourseIdFrontPageGetRaw(requestParameters: ApiV1CoursesCourseIdFrontPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>>;

    /**
     * Retrieve the content of the front page for a course.
     * Show front page
     */
    apiV1CoursesCourseIdFrontPageGet(requestParameters: ApiV1CoursesCourseIdFrontPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page>;

    /**
     * Retrieve the content of the front page for a group.
     * @summary Show front page
     * @param {number} groupId ID of the group
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PagesApiInterface
     */
    apiV1GroupsGroupIdFrontPageGetRaw(requestParameters: ApiV1GroupsGroupIdFrontPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>>;

    /**
     * Retrieve the content of the front page for a group.
     * Show front page
     */
    apiV1GroupsGroupIdFrontPageGet(requestParameters: ApiV1GroupsGroupIdFrontPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page>;

}

/**
 * 
 */
export class PagesApi extends runtime.BaseAPI implements PagesApiInterface {

    /**
     * Retrieve the content of the front page for a course.
     * Show front page
     */
    async apiV1CoursesCourseIdFrontPageGetRaw(requestParameters: ApiV1CoursesCourseIdFrontPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling apiV1CoursesCourseIdFrontPageGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/courses/{course_id}/front_page`.replace(`{${"course_id"}}`, encodeURIComponent(String(requestParameters['courseId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageFromJSON(jsonValue));
    }

    /**
     * Retrieve the content of the front page for a course.
     * Show front page
     */
    async apiV1CoursesCourseIdFrontPageGet(requestParameters: ApiV1CoursesCourseIdFrontPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page> {
        const response = await this.apiV1CoursesCourseIdFrontPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the content of the front page for a group.
     * Show front page
     */
    async apiV1GroupsGroupIdFrontPageGetRaw(requestParameters: ApiV1GroupsGroupIdFrontPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Page>> {
        if (requestParameters['groupId'] == null) {
            throw new runtime.RequiredError(
                'groupId',
                'Required parameter "groupId" was null or undefined when calling apiV1GroupsGroupIdFrontPageGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/groups/{group_id}/front_page`.replace(`{${"group_id"}}`, encodeURIComponent(String(requestParameters['groupId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageFromJSON(jsonValue));
    }

    /**
     * Retrieve the content of the front page for a group.
     * Show front page
     */
    async apiV1GroupsGroupIdFrontPageGet(requestParameters: ApiV1GroupsGroupIdFrontPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Page> {
        const response = await this.apiV1GroupsGroupIdFrontPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
