/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SharedBrandConfig,
} from '../models/index';
import {
    SharedBrandConfigFromJSON,
    SharedBrandConfigToJSON,
} from '../models/index';

export interface AccountsAccountIdSharedBrandConfigsIdPutRequest {
    accountId: string;
    id: number;
    sharedBrandConfigName: string;
    sharedBrandConfigBrandConfigMd5: string;
}

export interface AccountsAccountIdSharedBrandConfigsPostRequest {
    accountId: string;
    sharedBrandConfigName: string;
    sharedBrandConfigBrandConfigMd5: string;
}

export interface SharedBrandConfigsIdDeleteRequest {
    id: number;
}

/**
 * SharedBrandConfigsApi - interface
 * 
 * @export
 * @interface SharedBrandConfigsApiInterface
 */
export interface SharedBrandConfigsApiInterface {
    /**
     * Update the specified SharedBrandConfig with a new name or to point to a different BrandConfig. Uses same parameters as create. 
     * @summary Update a shared theme
     * @param {string} accountId The id of the account containing the SharedBrandConfig.
     * @param {number} id The id of the SharedBrandConfig to update.
     * @param {string} sharedBrandConfigName New name for the SharedBrandConfig.
     * @param {string} sharedBrandConfigBrandConfigMd5 MD5 of the new BrandConfig to share.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SharedBrandConfigsApiInterface
     */
    accountsAccountIdSharedBrandConfigsIdPutRaw(requestParameters: AccountsAccountIdSharedBrandConfigsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharedBrandConfig>>;

    /**
     * Update the specified SharedBrandConfig with a new name or to point to a different BrandConfig. Uses same parameters as create. 
     * Update a shared theme
     */
    accountsAccountIdSharedBrandConfigsIdPut(requestParameters: AccountsAccountIdSharedBrandConfigsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharedBrandConfig>;

    /**
     * Create a SharedBrandConfig, which will give the given brand_config a name and make it available to other users of this account. 
     * @summary Share a BrandConfig (Theme)
     * @param {string} accountId The id of the account in which to share the BrandConfig.
     * @param {string} sharedBrandConfigName Name to share this BrandConfig (theme) as.
     * @param {string} sharedBrandConfigBrandConfigMd5 MD5 of the BrandConfig to share.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SharedBrandConfigsApiInterface
     */
    accountsAccountIdSharedBrandConfigsPostRaw(requestParameters: AccountsAccountIdSharedBrandConfigsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharedBrandConfig>>;

    /**
     * Create a SharedBrandConfig, which will give the given brand_config a name and make it available to other users of this account. 
     * Share a BrandConfig (Theme)
     */
    accountsAccountIdSharedBrandConfigsPost(requestParameters: AccountsAccountIdSharedBrandConfigsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharedBrandConfig>;

    /**
     * Delete a SharedBrandConfig, which will unshare it so you nor anyone else in your account will see it as an option to pick from. 
     * @summary Un-share a BrandConfig (Theme)
     * @param {number} id The id of the SharedBrandConfig to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SharedBrandConfigsApiInterface
     */
    sharedBrandConfigsIdDeleteRaw(requestParameters: SharedBrandConfigsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharedBrandConfig>>;

    /**
     * Delete a SharedBrandConfig, which will unshare it so you nor anyone else in your account will see it as an option to pick from. 
     * Un-share a BrandConfig (Theme)
     */
    sharedBrandConfigsIdDelete(requestParameters: SharedBrandConfigsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharedBrandConfig>;

}

/**
 * 
 */
export class SharedBrandConfigsApi extends runtime.BaseAPI implements SharedBrandConfigsApiInterface {

    /**
     * Update the specified SharedBrandConfig with a new name or to point to a different BrandConfig. Uses same parameters as create. 
     * Update a shared theme
     */
    async accountsAccountIdSharedBrandConfigsIdPutRaw(requestParameters: AccountsAccountIdSharedBrandConfigsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharedBrandConfig>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsAccountIdSharedBrandConfigsIdPut().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling accountsAccountIdSharedBrandConfigsIdPut().'
            );
        }

        if (requestParameters['sharedBrandConfigName'] == null) {
            throw new runtime.RequiredError(
                'sharedBrandConfigName',
                'Required parameter "sharedBrandConfigName" was null or undefined when calling accountsAccountIdSharedBrandConfigsIdPut().'
            );
        }

        if (requestParameters['sharedBrandConfigBrandConfigMd5'] == null) {
            throw new runtime.RequiredError(
                'sharedBrandConfigBrandConfigMd5',
                'Required parameter "sharedBrandConfigBrandConfigMd5" was null or undefined when calling accountsAccountIdSharedBrandConfigsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['sharedBrandConfigName'] != null) {
            formParams.append('shared_brand_config[name]', requestParameters['sharedBrandConfigName'] as any);
        }

        if (requestParameters['sharedBrandConfigBrandConfigMd5'] != null) {
            formParams.append('shared_brand_config[brand_config_md5]', requestParameters['sharedBrandConfigBrandConfigMd5'] as any);
        }

        const response = await this.request({
            path: `/accounts/{account_id}/shared_brand_configs/{id}`.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SharedBrandConfigFromJSON(jsonValue));
    }

    /**
     * Update the specified SharedBrandConfig with a new name or to point to a different BrandConfig. Uses same parameters as create. 
     * Update a shared theme
     */
    async accountsAccountIdSharedBrandConfigsIdPut(requestParameters: AccountsAccountIdSharedBrandConfigsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharedBrandConfig> {
        const response = await this.accountsAccountIdSharedBrandConfigsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a SharedBrandConfig, which will give the given brand_config a name and make it available to other users of this account. 
     * Share a BrandConfig (Theme)
     */
    async accountsAccountIdSharedBrandConfigsPostRaw(requestParameters: AccountsAccountIdSharedBrandConfigsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharedBrandConfig>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling accountsAccountIdSharedBrandConfigsPost().'
            );
        }

        if (requestParameters['sharedBrandConfigName'] == null) {
            throw new runtime.RequiredError(
                'sharedBrandConfigName',
                'Required parameter "sharedBrandConfigName" was null or undefined when calling accountsAccountIdSharedBrandConfigsPost().'
            );
        }

        if (requestParameters['sharedBrandConfigBrandConfigMd5'] == null) {
            throw new runtime.RequiredError(
                'sharedBrandConfigBrandConfigMd5',
                'Required parameter "sharedBrandConfigBrandConfigMd5" was null or undefined when calling accountsAccountIdSharedBrandConfigsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['sharedBrandConfigName'] != null) {
            formParams.append('shared_brand_config[name]', requestParameters['sharedBrandConfigName'] as any);
        }

        if (requestParameters['sharedBrandConfigBrandConfigMd5'] != null) {
            formParams.append('shared_brand_config[brand_config_md5]', requestParameters['sharedBrandConfigBrandConfigMd5'] as any);
        }

        const response = await this.request({
            path: `/accounts/{account_id}/shared_brand_configs`.replace(`{${"account_id"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SharedBrandConfigFromJSON(jsonValue));
    }

    /**
     * Create a SharedBrandConfig, which will give the given brand_config a name and make it available to other users of this account. 
     * Share a BrandConfig (Theme)
     */
    async accountsAccountIdSharedBrandConfigsPost(requestParameters: AccountsAccountIdSharedBrandConfigsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharedBrandConfig> {
        const response = await this.accountsAccountIdSharedBrandConfigsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a SharedBrandConfig, which will unshare it so you nor anyone else in your account will see it as an option to pick from. 
     * Un-share a BrandConfig (Theme)
     */
    async sharedBrandConfigsIdDeleteRaw(requestParameters: SharedBrandConfigsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SharedBrandConfig>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sharedBrandConfigsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/shared_brand_configs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SharedBrandConfigFromJSON(jsonValue));
    }

    /**
     * Delete a SharedBrandConfig, which will unshare it so you nor anyone else in your account will see it as an option to pick from. 
     * Un-share a BrandConfig (Theme)
     */
    async sharedBrandConfigsIdDelete(requestParameters: SharedBrandConfigsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SharedBrandConfig> {
        const response = await this.sharedBrandConfigsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
