# flake8: noqa

# import apis into api package
from canvas_lms_sdk.api.account_notifications_api import AccountNotificationsApi
from canvas_lms_sdk.api.account_reports_api import AccountReportsApi
from canvas_lms_sdk.api.authentication_api import AuthenticationApi
from canvas_lms_sdk.api.authentication_providers_api import AuthenticationProvidersApi
from canvas_lms_sdk.api.conversations_api import ConversationsApi
from canvas_lms_sdk.api.courses_api import CoursesApi
from canvas_lms_sdk.api.enrollment_terms_api import EnrollmentTermsApi
from canvas_lms_sdk.api.files_api import FilesApi
from canvas_lms_sdk.api.lti2_api import LTI2Api
from canvas_lms_sdk.api.new_quiz_items_api import NewQuizItemsApi
from canvas_lms_sdk.api.outcome_imports_api import OutcomeImportsApi
from canvas_lms_sdk.api.pages_api import PagesApi
from canvas_lms_sdk.api.plagiarism_detection_platform_assignments_api import PlagiarismDetectionPlatformAssignmentsApi
from canvas_lms_sdk.api.platform_notification_service_api import PlatformNotificationServiceApi
from canvas_lms_sdk.api.poll_sessions_api import PollSessionsApi
from canvas_lms_sdk.api.search_api import SearchApi
from canvas_lms_sdk.api.services_api import ServicesApi
from canvas_lms_sdk.api.shared_brand_configs_api import SharedBrandConfigsApi
from canvas_lms_sdk.api.submission_comments_api import SubmissionCommentsApi
from canvas_lms_sdk.api.tabs_api import TabsApi
from canvas_lms_sdk.api.user_observees_api import UserObserveesApi
from canvas_lms_sdk.api.webhook_subscriptions_api import WebhookSubscriptionsApi
from canvas_lms_sdk.api.default_api import DefaultApi

