# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.api_v1_courses_course_id_quizzes_id_put_request_quiz import ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz

class TestApiV1CoursesCourseIdQuizzesIdPutRequestQuiz(unittest.TestCase):
    """ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz:
        """Test ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz`
        """
        model = ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz()
        if include_optional:
            return ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz(
                notify_of_update = True
            )
        else:
            return ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz(
        )
        """

    def testApiV1CoursesCourseIdQuizzesIdPutRequestQuiz(self):
        """Test ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
