# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_get_assignment_override_for_group(self) -> None:
        """Test case for get_assignment_override_for_group

        Redirect to the assignment override for a group
        """
        pass

    def test_list_assignment_group_members_for_user(self) -> None:
        """Test case for list_assignment_group_members_for_user

        List group members for a student on an assignment
        """
        pass


if __name__ == '__main__':
    unittest.main()
