# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.authentication_provider import AuthenticationProvider

class TestAuthenticationProvider(unittest.TestCase):
    """AuthenticationProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthenticationProvider:
        """Test AuthenticationProvider
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthenticationProvider`
        """
        model = AuthenticationProvider()
        if include_optional:
            return AuthenticationProvider(
                id = 56,
                auth_type = '',
                identifier_format = '',
                log_in_url = '',
                log_out_url = '',
                certificate_fingerprint = '',
                requested_authn_context = '',
                auth_host = '',
                auth_filter = '',
                auth_over_tls = '',
                auth_base = '',
                auth_username = '',
                auth_port = 56,
                position = 56,
                idp_entity_id = '',
                login_attribute = '',
                sig_alg = '',
                jit_provisioning = True,
                federated_attributes = {
                    'key' : null
                    },
                mfa_required = True
            )
        else:
            return AuthenticationProvider(
        )
        """

    def testAuthenticationProvider(self):
        """Test AuthenticationProvider"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
