# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.grade import Grade

class TestGrade(unittest.TestCase):
    """Grade unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Grade:
        """Test Grade
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Grade`
        """
        model = Grade()
        if include_optional:
            return Grade(
                grade = 1.337,
                total = 1.337,
                possible = 1.337,
                dropped = [
                    null
                    ]
            )
        else:
            return Grade(
        )
        """

    def testGrade(self):
        """Test Grade"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
