# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.create_assignment_override_request import CreateAssignmentOverrideRequest

class TestCreateAssignmentOverrideRequest(unittest.TestCase):
    """CreateAssignmentOverrideRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAssignmentOverrideRequest:
        """Test CreateAssignmentOverrideRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAssignmentOverrideRequest`
        """
        model = CreateAssignmentOverrideRequest()
        if include_optional:
            return CreateAssignmentOverrideRequest(
                assignment_override = canvas_lms_sdk.models.assignment_override_input.AssignmentOverrideInput(
                    student_ids = [
                        56
                        ], 
                    title = '', 
                    group_id = 56, 
                    course_section_id = 56, 
                    due_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    unlock_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    lock_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return CreateAssignmentOverrideRequest(
        )
        """

    def testCreateAssignmentOverrideRequest(self):
        """Test CreateAssignmentOverrideRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
