# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.api_v1_courses_course_id_quizzes_id_reorder_post_request import ApiV1CoursesCourseIdQuizzesIdReorderPostRequest

class TestApiV1CoursesCourseIdQuizzesIdReorderPostRequest(unittest.TestCase):
    """ApiV1CoursesCourseIdQuizzesIdReorderPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1CoursesCourseIdQuizzesIdReorderPostRequest:
        """Test ApiV1CoursesCourseIdQuizzesIdReorderPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1CoursesCourseIdQuizzesIdReorderPostRequest`
        """
        model = ApiV1CoursesCourseIdQuizzesIdReorderPostRequest()
        if include_optional:
            return ApiV1CoursesCourseIdQuizzesIdReorderPostRequest(
                order = [
                    canvas_lms_sdk.models._api_v1_courses__course_id__quizzes__id__reorder_post_request_order_inner._api_v1_courses__course_id__quizzes__id__reorder_post_request_order_inner(
                        id = 56, 
                        type = 'question', )
                    ]
            )
        else:
            return ApiV1CoursesCourseIdQuizzesIdReorderPostRequest(
        )
        """

    def testApiV1CoursesCourseIdQuizzesIdReorderPostRequest(self):
        """Test ApiV1CoursesCourseIdQuizzesIdReorderPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
