# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.poll_session import PollSession

class TestPollSession(unittest.TestCase):
    """PollSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PollSession:
        """Test PollSession
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PollSession`
        """
        model = PollSession()
        if include_optional:
            return PollSession(
                id = 56,
                poll_id = 56,
                course_id = 56,
                course_section_id = 56,
                is_published = True,
                has_public_results = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                results = {
                    'key' : 56
                    },
                poll_submissions = [
                    null
                    ]
            )
        else:
            return PollSession(
        )
        """

    def testPollSession(self):
        """Test PollSession"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
