# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.external_tool import ExternalTool

class TestExternalTool(unittest.TestCase):
    """ExternalTool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExternalTool:
        """Test ExternalTool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExternalTool`
        """
        model = ExternalTool()
        if include_optional:
            return ExternalTool(
                id = 56,
                domain = '',
                url = '',
                consumer_key = '',
                name = '',
                description = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                privacy_level = '',
                custom_fields = {
                    'key' : ''
                    },
                is_rce_favorite = True,
                is_top_nav_favorite = True,
                account_navigation = None,
                assignment_selection = None,
                course_navigation = None,
                editor_button = None,
                selection_width = 56,
                selection_height = 56,
                icon_url = '',
                not_selectable = True
            )
        else:
            return ExternalTool(
        )
        """

    def testExternalTool(self):
        """Test ExternalTool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
