# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.api_lti_notice_handlers_deployment_id_get200_response_notice_handlers_inner import ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner

class TestApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner(unittest.TestCase):
    """ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner:
        """Test ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner`
        """
        model = ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner()
        if include_optional:
            return ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner(
                notice_type = '',
                handler = ''
            )
        else:
            return ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner(
        )
        """

    def testApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner(self):
        """Test ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
