# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.grading_rules import GradingRules

class TestGradingRules(unittest.TestCase):
    """GradingRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GradingRules:
        """Test GradingRules
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GradingRules`
        """
        model = GradingRules()
        if include_optional:
            return GradingRules(
                drop_lowest = 56,
                drop_highest = 56,
                never_drop = [
                    56
                    ]
            )
        else:
            return GradingRules(
                drop_lowest = 56,
                drop_highest = 56,
                never_drop = [
                    56
                    ],
        )
        """

    def testGradingRules(self):
        """Test GradingRules"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
