# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.api_v1_quiz_submissions_quiz_submission_id_questions_id_flag_put_request import ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest

class TestApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest(unittest.TestCase):
    """ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest:
        """Test ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest`
        """
        model = ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest()
        if include_optional:
            return ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest(
                attempt = 56,
                validation_token = '',
                access_code = ''
            )
        else:
            return ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest(
                attempt = 56,
                validation_token = '',
        )
        """

    def testApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest(self):
        """Test ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
