# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.api_v1_courses_course_id_quizzes_post_request import ApiV1CoursesCourseIdQuizzesPostRequest

class TestApiV1CoursesCourseIdQuizzesPostRequest(unittest.TestCase):
    """ApiV1CoursesCourseIdQuizzesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1CoursesCourseIdQuizzesPostRequest:
        """Test ApiV1CoursesCourseIdQuizzesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1CoursesCourseIdQuizzesPostRequest`
        """
        model = ApiV1CoursesCourseIdQuizzesPostRequest()
        if include_optional:
            return ApiV1CoursesCourseIdQuizzesPostRequest(
                quiz = canvas_lms_sdk.models._api_v1_courses__course_id__quizzes_post_request_quiz._api_v1_courses__course_id__quizzes_post_request_quiz(
                    title = '', 
                    description = '', 
                    quiz_type = 'practice_quiz', 
                    assignment_group_id = 56, 
                    time_limit = 56, 
                    shuffle_answers = True, 
                    hide_results = 'always', 
                    show_correct_answers = True, 
                    show_correct_answers_last_attempt = True, 
                    show_correct_answers_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    hide_correct_answers_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    allowed_attempts = 56, 
                    scoring_policy = 'keep_highest', 
                    one_question_at_a_time = True, 
                    cant_go_back = True, 
                    access_code = '', 
                    ip_filter = '', 
                    due_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    lock_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    unlock_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    published = True, 
                    one_time_results = True, 
                    only_visible_to_overrides = True, )
            )
        else:
            return ApiV1CoursesCourseIdQuizzesPostRequest(
        )
        """

    def testApiV1CoursesCourseIdQuizzesPostRequest(self):
        """Test ApiV1CoursesCourseIdQuizzesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
