# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.api.platform_notification_service_api import PlatformNotificationServiceApi


class TestPlatformNotificationServiceApi(unittest.TestCase):
    """PlatformNotificationServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlatformNotificationServiceApi()

    def tearDown(self) -> None:
        pass

    def test_api_lti_notice_handlers_deployment_id_get(self) -> None:
        """Test case for api_lti_notice_handlers_deployment_id_get

        Retrieve registered notice handlers
        """
        pass

    def test_api_lti_notice_handlers_deployment_id_put(self) -> None:
        """Test case for api_lti_notice_handlers_deployment_id_put

        Register or update a notice handler
        """
        pass


if __name__ == '__main__':
    unittest.main()
