# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.assignment import Assignment

class TestAssignment(unittest.TestCase):
    """Assignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Assignment:
        """Test Assignment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Assignment`
        """
        model = Assignment()
        if include_optional:
            return Assignment(
                id = 56,
                name = '',
                html_url = ''
            )
        else:
            return Assignment(
        )
        """

    def testAssignment(self):
        """Test Assignment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
