# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.api_v1_polls_poll_id_poll_sessions_post_request_poll_sessions_inner import ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner

class TestApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner(unittest.TestCase):
    """ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner:
        """Test ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner`
        """
        model = ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner()
        if include_optional:
            return ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner(
                course_id = 56,
                course_section_id = 56,
                has_public_results = True
            )
        else:
            return ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner(
                course_id = 56,
        )
        """

    def testApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner(self):
        """Test ApiV1PollsPollIdPollSessionsPostRequestPollSessionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
