# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.api.pages_api import PagesApi


class TestPagesApi(unittest.TestCase):
    """PagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PagesApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_courses_course_id_front_page_get(self) -> None:
        """Test case for api_v1_courses_course_id_front_page_get

        Show front page
        """
        pass

    def test_api_v1_groups_group_id_front_page_get(self) -> None:
        """Test case for api_v1_groups_group_id_front_page_get

        Show front page
        """
        pass


if __name__ == '__main__':
    unittest.main()
