# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.resource_link import ResourceLink

class TestResourceLink(unittest.TestCase):
    """ResourceLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResourceLink:
        """Test ResourceLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResourceLink`
        """
        model = ResourceLink()
        if include_optional:
            return ResourceLink(
                id = 56,
                context_id = 56,
                context_type = '',
                context_external_tool_id = 56,
                resource_type = '',
                canvas_launch_url = '',
                resource_link_uuid = '',
                lookup_uuid = '',
                title = '',
                url = '',
                lti_1_1_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                workflow_state = '',
                associated_content_type = '',
                associated_content_id = 56
            )
        else:
            return ResourceLink(
        )
        """

    def testResourceLink(self):
        """Test ResourceLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
