# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_accounts_account_id_group_categories_get(self) -> None:
        """Test case for accounts_account_id_group_categories_get

        List group categories for an account
        """
        pass

    def test_accounts_account_id_group_categories_post(self) -> None:
        """Test case for accounts_account_id_group_categories_post

        Create a Group Category in an account
        """
        pass

    def test_accounts_account_id_lti_registration_by_client_id_client_id_get(self) -> None:
        """Test case for accounts_account_id_lti_registration_by_client_id_client_id_get

        Show an LTI Registration (via the client_id)
        """
        pass

    def test_accounts_account_id_lti_registrations_get(self) -> None:
        """Test case for accounts_account_id_lti_registrations_get

        List LTI Registrations in an account
        """
        pass

    def test_accounts_account_id_lti_registrations_id_bind_post(self) -> None:
        """Test case for accounts_account_id_lti_registrations_id_bind_post

        Bind an LTI Registration to an Account
        """
        pass

    def test_accounts_account_id_lti_registrations_id_delete(self) -> None:
        """Test case for accounts_account_id_lti_registrations_id_delete

        Delete an LTI Registration
        """
        pass

    def test_accounts_account_id_lti_registrations_id_get(self) -> None:
        """Test case for accounts_account_id_lti_registrations_id_get

        Show an LTI Registration
        """
        pass

    def test_accounts_account_id_lti_registrations_id_put(self) -> None:
        """Test case for accounts_account_id_lti_registrations_id_put

        Update an LTI Registration
        """
        pass

    def test_accounts_account_id_lti_registrations_id_reset_put(self) -> None:
        """Test case for accounts_account_id_lti_registrations_id_reset_put

        Reset an LTI Registration to Defaults
        """
        pass

    def test_accounts_account_id_lti_registrations_post(self) -> None:
        """Test case for accounts_account_id_lti_registrations_post

        Create an LTI Registration
        """
        pass

    def test_api_lti_assignments_assignment_id_submissions_submission_id_get(self) -> None:
        """Test case for api_lti_assignments_assignment_id_submissions_submission_id_get

        Get a single submission
        """
        pass

    def test_api_lti_assignments_assignment_id_submissions_submission_id_history_get(self) -> None:
        """Test case for api_lti_assignments_assignment_id_submissions_submission_id_history_get

        Get the history of a single submission
        """
        pass

    def test_api_lti_groups_group_id_users_get(self) -> None:
        """Test case for api_lti_groups_group_id_users_get

        Get all users in a group (lti)
        """
        pass

    def test_api_lti_users_id_get(self) -> None:
        """Test case for api_lti_users_id_get

        Get a single user (lti)
        """
        pass

    def test_api_v1_accounts_account_id_developer_keys_get(self) -> None:
        """Test case for api_v1_accounts_account_id_developer_keys_get

        List Developer Keys
        """
        pass

    def test_api_v1_accounts_account_id_developer_keys_post(self) -> None:
        """Test case for api_v1_accounts_account_id_developer_keys_post

        Create a Developer Key
        """
        pass

    def test_api_v1_accounts_account_id_enrollments_id_get(self) -> None:
        """Test case for api_v1_accounts_account_id_enrollments_id_get

        Get an Enrollment by ID
        """
        pass

    def test_api_v1_accounts_account_id_external_tools_get(self) -> None:
        """Test case for api_v1_accounts_account_id_external_tools_get

        List external tools (account)
        """
        pass

    def test_api_v1_accounts_account_id_sis_import_errors_get(self) -> None:
        """Test case for api_v1_accounts_account_id_sis_import_errors_get

        Get SIS import error list for an account
        """
        pass

    def test_api_v1_accounts_account_id_sis_imports_id_errors_get(self) -> None:
        """Test case for api_v1_accounts_account_id_sis_imports_id_errors_get

        Get SIS import error list for a specific SIS import
        """
        pass

    def test_api_v1_accounts_account_id_temporary_enrollment_pairings_get(self) -> None:
        """Test case for api_v1_accounts_account_id_temporary_enrollment_pairings_get

        List temporary enrollment pairings
        """
        pass

    def test_api_v1_accounts_account_id_temporary_enrollment_pairings_id_delete(self) -> None:
        """Test case for api_v1_accounts_account_id_temporary_enrollment_pairings_id_delete

        Delete Temporary Enrollment Pairing
        """
        pass

    def test_api_v1_accounts_account_id_temporary_enrollment_pairings_id_get(self) -> None:
        """Test case for api_v1_accounts_account_id_temporary_enrollment_pairings_id_get

        Get a single temporary enrollment pairing
        """
        pass

    def test_api_v1_accounts_account_id_temporary_enrollment_pairings_new_get(self) -> None:
        """Test case for api_v1_accounts_account_id_temporary_enrollment_pairings_new_get

        Initialize an unsaved TemporaryEnrollmentPairing
        """
        pass

    def test_api_v1_accounts_account_id_temporary_enrollment_pairings_post(self) -> None:
        """Test case for api_v1_accounts_account_id_temporary_enrollment_pairings_post

        Create Temporary Enrollment Pairing
        """
        pass

    def test_api_v1_accounts_get(self) -> None:
        """Test case for api_v1_accounts_get

        List accounts
        """
        pass

    def test_api_v1_courses_course_id_assignment_groups_assignment_group_id_delete(self) -> None:
        """Test case for api_v1_courses_course_id_assignment_groups_assignment_group_id_delete

        Destroy an Assignment Group
        """
        pass

    def test_api_v1_courses_course_id_assignment_groups_assignment_group_id_get(self) -> None:
        """Test case for api_v1_courses_course_id_assignment_groups_assignment_group_id_get

        Get an Assignment Group
        """
        pass

    def test_api_v1_courses_course_id_assignment_groups_assignment_group_id_put(self) -> None:
        """Test case for api_v1_courses_course_id_assignment_groups_assignment_group_id_put

        Edit an Assignment Group
        """
        pass

    def test_api_v1_courses_course_id_assignment_groups_get(self) -> None:
        """Test case for api_v1_courses_course_id_assignment_groups_get

        List assignment groups
        """
        pass

    def test_api_v1_courses_course_id_assignment_groups_post(self) -> None:
        """Test case for api_v1_courses_course_id_assignment_groups_post

        Create an Assignment Group
        """
        pass

    def test_api_v1_courses_course_id_content_migrations_content_migration_id_migration_issues_get(self) -> None:
        """Test case for api_v1_courses_course_id_content_migrations_content_migration_id_migration_issues_get

        List migration issues
        """
        pass

    def test_api_v1_courses_course_id_discussion_topics_get(self) -> None:
        """Test case for api_v1_courses_course_id_discussion_topics_get

        Returns the paginated list of discussion topics for a course.
        """
        pass

    def test_api_v1_courses_course_id_enrollments_get(self) -> None:
        """Test case for api_v1_courses_course_id_enrollments_get

        Return a paginated list of enrollments in a course
        """
        pass

    def test_api_v1_courses_course_id_enrollments_id_accept_post(self) -> None:
        """Test case for api_v1_courses_course_id_enrollments_id_accept_post

        Accept a pending course invitation
        """
        pass

    def test_api_v1_courses_course_id_enrollments_id_delete(self) -> None:
        """Test case for api_v1_courses_course_id_enrollments_id_delete

        Conclude, deactivate, or delete an enrollment
        """
        pass

    def test_api_v1_courses_course_id_enrollments_id_reactivate_put(self) -> None:
        """Test case for api_v1_courses_course_id_enrollments_id_reactivate_put

        Re-activate an inactive enrollment
        """
        pass

    def test_api_v1_courses_course_id_enrollments_id_reject_post(self) -> None:
        """Test case for api_v1_courses_course_id_enrollments_id_reject_post

        Reject a pending course invitation
        """
        pass

    def test_api_v1_courses_course_id_enrollments_post(self) -> None:
        """Test case for api_v1_courses_course_id_enrollments_post

        Enroll a user in a course
        """
        pass

    def test_api_v1_courses_course_id_external_tools_get(self) -> None:
        """Test case for api_v1_courses_course_id_external_tools_get

        List external tools
        """
        pass

    def test_api_v1_courses_course_id_lti_resource_links_bulk_post(self) -> None:
        """Test case for api_v1_courses_course_id_lti_resource_links_bulk_post

        Bulk Create LTI Resource Links
        """
        pass

    def test_api_v1_courses_course_id_lti_resource_links_get(self) -> None:
        """Test case for api_v1_courses_course_id_lti_resource_links_get

        Returns all Resource Links in the specified course
        """
        pass

    def test_api_v1_courses_course_id_lti_resource_links_id_delete(self) -> None:
        """Test case for api_v1_courses_course_id_lti_resource_links_id_delete

        Delete an LTI Resource Link
        """
        pass

    def test_api_v1_courses_course_id_lti_resource_links_id_get(self) -> None:
        """Test case for api_v1_courses_course_id_lti_resource_links_id_get

        Show an LTI Resource Link
        """
        pass

    def test_api_v1_courses_course_id_lti_resource_links_id_put(self) -> None:
        """Test case for api_v1_courses_course_id_lti_resource_links_id_put

        Update an LTI Resource Link
        """
        pass

    def test_api_v1_courses_course_id_lti_resource_links_post(self) -> None:
        """Test case for api_v1_courses_course_id_lti_resource_links_post

        Create an LTI Resource Link
        """
        pass

    def test_api_v1_courses_course_id_quizzes_get(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_get

        List quizzes in a course
        """
        pass

    def test_api_v1_courses_course_id_quizzes_id_delete(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_id_delete

        Delete a quiz
        """
        pass

    def test_api_v1_courses_course_id_quizzes_id_get(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_id_get

        Get a single quiz
        """
        pass

    def test_api_v1_courses_course_id_quizzes_id_put(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_id_put

        Edit a quiz
        """
        pass

    def test_api_v1_courses_course_id_quizzes_id_reorder_post(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_id_reorder_post

        Reorder quiz items
        """
        pass

    def test_api_v1_courses_course_id_quizzes_id_validate_access_code_post(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_id_validate_access_code_post

        Validate quiz access code
        """
        pass

    def test_api_v1_courses_course_id_quizzes_post(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_post

        Create a quiz
        """
        pass

    def test_api_v1_courses_course_id_quizzes_quiz_id_questions_get(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_quiz_id_questions_get

        List questions in a quiz or a submission
        """
        pass

    def test_api_v1_courses_course_id_quizzes_quiz_id_questions_id_delete(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_quiz_id_questions_id_delete

        Delete a quiz question
        """
        pass

    def test_api_v1_courses_course_id_quizzes_quiz_id_questions_id_get(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_quiz_id_questions_id_get

        Get a single quiz question
        """
        pass

    def test_api_v1_courses_course_id_quizzes_quiz_id_questions_id_put(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_quiz_id_questions_id_put

        Update an existing quiz question
        """
        pass

    def test_api_v1_courses_course_id_quizzes_quiz_id_questions_post(self) -> None:
        """Test case for api_v1_courses_course_id_quizzes_quiz_id_questions_post

        Create a single quiz question
        """
        pass

    def test_api_v1_courses_course_id_sections_get(self) -> None:
        """Test case for api_v1_courses_course_id_sections_get

        A paginated list of the sections for this course.
        """
        pass

    def test_api_v1_courses_course_id_sections_id_get(self) -> None:
        """Test case for api_v1_courses_course_id_sections_id_get

        Gets details about a specific section.
        """
        pass

    def test_api_v1_courses_course_id_sections_post(self) -> None:
        """Test case for api_v1_courses_course_id_sections_post

        Creates a new section for this course.
        """
        pass

    def test_api_v1_courses_course_id_users_user_id_last_attended_put(self) -> None:
        """Test case for api_v1_courses_course_id_users_user_id_last_attended_put

        Add last attended date to a student enrollment
        """
        pass

    def test_api_v1_courses_course_id_what_if_grades_reset_put(self) -> None:
        """Test case for api_v1_courses_course_id_what_if_grades_reset_put

        Reset the what-if scores for the current user for an entire course and recalculate grades
        """
        pass

    def test_api_v1_developer_keys_id_delete(self) -> None:
        """Test case for api_v1_developer_keys_id_delete

        Delete a Developer Key
        """
        pass

    def test_api_v1_developer_keys_id_put(self) -> None:
        """Test case for api_v1_developer_keys_id_put

        Update a Developer Key
        """
        pass

    def test_api_v1_groups_group_id_discussion_topics_get(self) -> None:
        """Test case for api_v1_groups_group_id_discussion_topics_get

        Returns the paginated list of discussion topics for a group.
        """
        pass

    def test_api_v1_quiz_submissions_quiz_submission_id_questions_get(self) -> None:
        """Test case for api_v1_quiz_submissions_quiz_submission_id_questions_get

        Get a list of all the question records for this quiz submission.
        """
        pass

    def test_api_v1_quiz_submissions_quiz_submission_id_questions_id_flag_put(self) -> None:
        """Test case for api_v1_quiz_submissions_quiz_submission_id_questions_id_flag_put

        Set a flag on a quiz question to indicate that you want to return to it later.
        """
        pass

    def test_api_v1_quiz_submissions_quiz_submission_id_questions_id_formatted_answer_get(self) -> None:
        """Test case for api_v1_quiz_submissions_quiz_submission_id_questions_id_formatted_answer_get

        Matches the intended behavior of the UI when a numerical answer is entered and returns the resulting formatted number.
        """
        pass

    def test_api_v1_quiz_submissions_quiz_submission_id_questions_id_unflag_put(self) -> None:
        """Test case for api_v1_quiz_submissions_quiz_submission_id_questions_id_unflag_put

        Remove the flag that you previously set on a quiz question after you've returned to it.
        """
        pass

    def test_api_v1_quiz_submissions_quiz_submission_id_questions_post(self) -> None:
        """Test case for api_v1_quiz_submissions_quiz_submission_id_questions_post

        Provide or update an answer to one or more QuizQuestions.
        """
        pass

    def test_api_v1_sections_id_crosslist_delete(self) -> None:
        """Test case for api_v1_sections_id_crosslist_delete

        Undo cross-listing of a Section.
        """
        pass

    def test_api_v1_sections_id_crosslist_new_course_id_post(self) -> None:
        """Test case for api_v1_sections_id_crosslist_new_course_id_post

        Move the section to another course.
        """
        pass

    def test_api_v1_sections_id_delete(self) -> None:
        """Test case for api_v1_sections_id_delete

        Delete an existing section.
        """
        pass

    def test_api_v1_sections_id_get(self) -> None:
        """Test case for api_v1_sections_id_get

        Gets details about a specific section.
        """
        pass

    def test_api_v1_sections_id_put(self) -> None:
        """Test case for api_v1_sections_id_put

        Modify an existing section.
        """
        pass

    def test_api_v1_sections_section_id_enrollments_get(self) -> None:
        """Test case for api_v1_sections_section_id_enrollments_get

        Return a paginated list of enrollments in a section
        """
        pass

    def test_api_v1_submissions_id_what_if_grades_put(self) -> None:
        """Test case for api_v1_submissions_id_what_if_grades_put

        Update a submission's what-if score and calculate grades
        """
        pass

    def test_api_v1_users_self_groups_get(self) -> None:
        """Test case for api_v1_users_self_groups_get

        List your groups
        """
        pass

    def test_api_v1_users_user_id_content_shares_id_add_users_post(self) -> None:
        """Test case for api_v1_users_user_id_content_shares_id_add_users_post

        Send a previously created content share to additional users
        """
        pass

    def test_api_v1_users_user_id_content_shares_id_delete(self) -> None:
        """Test case for api_v1_users_user_id_content_shares_id_delete

        Remove a content share from your list
        """
        pass

    def test_api_v1_users_user_id_content_shares_id_get(self) -> None:
        """Test case for api_v1_users_user_id_content_shares_id_get

        Get a content share
        """
        pass

    def test_api_v1_users_user_id_content_shares_id_put(self) -> None:
        """Test case for api_v1_users_user_id_content_shares_id_put

        Mark a content share read or unread
        """
        pass

    def test_api_v1_users_user_id_content_shares_post(self) -> None:
        """Test case for api_v1_users_user_id_content_shares_post

        Share content directly between two or more users
        """
        pass

    def test_api_v1_users_user_id_content_shares_received_get(self) -> None:
        """Test case for api_v1_users_user_id_content_shares_received_get

        List content shares received by a user
        """
        pass

    def test_api_v1_users_user_id_content_shares_sent_get(self) -> None:
        """Test case for api_v1_users_user_id_content_shares_sent_get

        List content shares sent by a user
        """
        pass

    def test_api_v1_users_user_id_content_shares_unread_count_get(self) -> None:
        """Test case for api_v1_users_user_id_content_shares_unread_count_get

        Get the number of unread content shares received by a user
        """
        pass

    def test_api_v1_users_user_id_enrollments_get(self) -> None:
        """Test case for api_v1_users_user_id_enrollments_get

        Return a paginated list of a user's enrollments
        """
        pass

    def test_api_v1_users_user_id_temporary_enrollment_status_get(self) -> None:
        """Test case for api_v1_users_user_id_temporary_enrollment_status_get

        Show temporary enrollment recipient and provider status
        """
        pass

    def test_courses_course_id_group_categories_bulk_manage_differentiation_tag_post(self) -> None:
        """Test case for courses_course_id_group_categories_bulk_manage_differentiation_tag_post

        Bulk manage differentiation tags
        """
        pass

    def test_courses_course_id_group_categories_get(self) -> None:
        """Test case for courses_course_id_group_categories_get

        List group categories for a course
        """
        pass

    def test_courses_course_id_group_categories_post(self) -> None:
        """Test case for courses_course_id_group_categories_post

        Create a Group Category in a course
        """
        pass

    def test_courses_course_id_quizzes_assignment_id_delete(self) -> None:
        """Test case for courses_course_id_quizzes_assignment_id_delete

        Delete a new quiz
        """
        pass

    def test_courses_course_id_quizzes_assignment_id_get(self) -> None:
        """Test case for courses_course_id_quizzes_assignment_id_get

        Get a new quiz
        """
        pass

    def test_courses_course_id_quizzes_assignment_id_patch(self) -> None:
        """Test case for courses_course_id_quizzes_assignment_id_patch

        Update a single quiz
        """
        pass

    def test_courses_course_id_quizzes_get(self) -> None:
        """Test case for courses_course_id_quizzes_get

        List new quizzes
        """
        pass

    def test_courses_course_id_quizzes_post(self) -> None:
        """Test case for courses_course_id_quizzes_post

        Create a new quiz
        """
        pass

    def test_group_categories_group_category_id_assign_unassigned_members_post(self) -> None:
        """Test case for group_categories_group_category_id_assign_unassigned_members_post

        Assign unassigned members
        """
        pass

    def test_group_categories_group_category_id_delete(self) -> None:
        """Test case for group_categories_group_category_id_delete

        Delete a Group Category
        """
        pass

    def test_group_categories_group_category_id_export_get(self) -> None:
        """Test case for group_categories_group_category_id_export_get

        Export groups and users in category
        """
        pass

    def test_group_categories_group_category_id_get(self) -> None:
        """Test case for group_categories_group_category_id_get

        Get a single group category
        """
        pass

    def test_group_categories_group_category_id_groups_get(self) -> None:
        """Test case for group_categories_group_category_id_groups_get

        List groups in a group category
        """
        pass

    def test_group_categories_group_category_id_import_post(self) -> None:
        """Test case for group_categories_group_category_id_import_post

        Import category groups
        """
        pass

    def test_group_categories_group_category_id_put(self) -> None:
        """Test case for group_categories_group_category_id_put

        Update a Group Category
        """
        pass

    def test_group_categories_group_category_id_users_get(self) -> None:
        """Test case for group_categories_group_category_id_users_get

        List users in group category
        """
        pass

    def test_lti_xapi_post(self) -> None:
        """Test case for lti_xapi_post

        Log xAPI interaction activity for an LTI tool
        """
        pass


if __name__ == '__main__':
    unittest.main()
