# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.api.outcome_imports_api import OutcomeImportsApi


class TestOutcomeImportsApi(unittest.TestCase):
    """OutcomeImportsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OutcomeImportsApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_accounts_account_id_outcome_imports_group_learning_outcome_group_id_post(self) -> None:
        """Test case for api_v1_accounts_account_id_outcome_imports_group_learning_outcome_group_id_post

        Import outcomes into a specific learning outcome group
        """
        pass

    def test_api_v1_accounts_account_id_outcome_imports_id_created_group_ids_get(self) -> None:
        """Test case for api_v1_accounts_account_id_outcome_imports_id_created_group_ids_get

        Get IDs of outcome groups created after successful import
        """
        pass

    def test_api_v1_accounts_account_id_outcome_imports_id_get(self) -> None:
        """Test case for api_v1_accounts_account_id_outcome_imports_id_get

        Get outcome import status
        """
        pass

    def test_api_v1_accounts_account_id_outcome_imports_post(self) -> None:
        """Test case for api_v1_accounts_account_id_outcome_imports_post

        Import outcomes into Canvas
        """
        pass

    def test_api_v1_courses_course_id_outcome_imports_group_learning_outcome_group_id_post(self) -> None:
        """Test case for api_v1_courses_course_id_outcome_imports_group_learning_outcome_group_id_post

        Import outcomes into a specific learning outcome group
        """
        pass

    def test_api_v1_courses_course_id_outcome_imports_id_created_group_ids_get(self) -> None:
        """Test case for api_v1_courses_course_id_outcome_imports_id_created_group_ids_get

        Get IDs of outcome groups created after successful import
        """
        pass

    def test_api_v1_courses_course_id_outcome_imports_id_get(self) -> None:
        """Test case for api_v1_courses_course_id_outcome_imports_id_get

        Get outcome import status
        """
        pass

    def test_api_v1_courses_course_id_outcome_imports_post(self) -> None:
        """Test case for api_v1_courses_course_id_outcome_imports_post

        Import outcomes into Canvas
        """
        pass


if __name__ == '__main__':
    unittest.main()
