# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.account_notification_author import AccountNotificationAuthor

class TestAccountNotificationAuthor(unittest.TestCase):
    """AccountNotificationAuthor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountNotificationAuthor:
        """Test AccountNotificationAuthor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountNotificationAuthor`
        """
        model = AccountNotificationAuthor()
        if include_optional:
            return AccountNotificationAuthor(
                id = 56,
                name = ''
            )
        else:
            return AccountNotificationAuthor(
        )
        """

    def testAccountNotificationAuthor(self):
        """Test AccountNotificationAuthor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
