# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.conversation_participant import ConversationParticipant

class TestConversationParticipant(unittest.TestCase):
    """ConversationParticipant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConversationParticipant:
        """Test ConversationParticipant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConversationParticipant`
        """
        model = ConversationParticipant()
        if include_optional:
            return ConversationParticipant(
                id = 56,
                name = '',
                full_name = '',
                avatar_url = ''
            )
        else:
            return ConversationParticipant(
        )
        """

    def testConversationParticipant(self):
        """Test ConversationParticipant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
