# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.migration_issue import MigrationIssue

class TestMigrationIssue(unittest.TestCase):
    """MigrationIssue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MigrationIssue:
        """Test MigrationIssue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MigrationIssue`
        """
        model = MigrationIssue()
        if include_optional:
            return MigrationIssue(
                id = 56,
                content_migration_url = '',
                description = '',
                workflow_state = 'active',
                fix_issue_html_url = '',
                issue_type = 'todo',
                error_report_html_url = '',
                error_message = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return MigrationIssue(
                id = 56,
                content_migration_url = '',
                description = '',
                workflow_state = 'active',
                issue_type = 'todo',
        )
        """

    def testMigrationIssue(self):
        """Test MigrationIssue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
