# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from canvas_lms_sdk.models.create_assignment_request_assignment import CreateAssignmentRequestAssignment

class TestCreateAssignmentRequestAssignment(unittest.TestCase):
    """CreateAssignmentRequestAssignment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAssignmentRequestAssignment:
        """Test CreateAssignmentRequestAssignment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAssignmentRequestAssignment`
        """
        model = CreateAssignmentRequestAssignment()
        if include_optional:
            return CreateAssignmentRequestAssignment(
                name = '',
                position = 56,
                submission_types = [
                    'online_quiz'
                    ],
                allowed_extensions = [
                    ''
                    ],
                turnitin_enabled = True,
                vericite_enabled = True,
                turnitin_settings = canvas_lms_sdk.models.turnitin_settings.TurnitinSettings(
                    originality_report_visibility = 'immediate', 
                    s_paper_check = True, 
                    internet_check = True, 
                    journal_check = True, 
                    exclude_biblio = True, 
                    exclude_quoted = True, 
                    exclude_small_matches_type = 'percent', 
                    exclude_small_matches_value = 56, ),
                integration_data = { },
                integration_id = '',
                peer_reviews = True,
                automatic_peer_reviews = True,
                notify_of_update = True,
                group_category_id = 56,
                grade_group_students_individually = True,
                external_tool_tag_attributes = canvas_lms_sdk.models.external_tool_tag_attributes.ExternalToolTagAttributes(
                    url = '', 
                    new_tab = True, 
                    resource_link_id = '', ),
                points_possible = 1.337,
                grading_type = 'pass_fail',
                due_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                lock_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                unlock_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                assignment_group_id = 56,
                assignment_overrides = [
                    canvas_lms_sdk.models.assignment_override_input.AssignmentOverrideInput(
                        student_ids = [
                            56
                            ], 
                        title = '', 
                        group_id = 56, 
                        course_section_id = 56, 
                        due_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        unlock_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        lock_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                only_visible_to_overrides = True,
                published = True,
                grading_standard_id = 56,
                omit_from_final_grade = True,
                hide_in_gradebook = True,
                quiz_lti = True,
                moderated_grading = True,
                grader_count = 56,
                final_grader_id = 56,
                grader_comments_visible_to_graders = True,
                graders_anonymous_to_graders = True,
                graders_names_visible_to_final_grader = True,
                anonymous_grading = True,
                allowed_attempts = 56,
                annotatable_attachment_id = 56
            )
        else:
            return CreateAssignmentRequestAssignment(
                name = '',
        )
        """

    def testCreateAssignmentRequestAssignment(self):
        """Test CreateAssignmentRequestAssignment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
