/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsAccountIdLtiRegistrationsIdBindPostRequest
 */
export interface AccountsAccountIdLtiRegistrationsIdBindPostRequest {
    /**
     * The desired state for this registration/account binding.
     * @type {string}
     * @memberof AccountsAccountIdLtiRegistrationsIdBindPostRequest
     */
    workflowState: AccountsAccountIdLtiRegistrationsIdBindPostRequestWorkflowStateEnum;
}


/**
 * @export
 */
export const AccountsAccountIdLtiRegistrationsIdBindPostRequestWorkflowStateEnum = {
    On: 'on',
    Off: 'off',
    Allow: 'allow'
} as const;
export type AccountsAccountIdLtiRegistrationsIdBindPostRequestWorkflowStateEnum = typeof AccountsAccountIdLtiRegistrationsIdBindPostRequestWorkflowStateEnum[keyof typeof AccountsAccountIdLtiRegistrationsIdBindPostRequestWorkflowStateEnum];


/**
 * Check if a given object implements the AccountsAccountIdLtiRegistrationsIdBindPostRequest interface.
 */
export function instanceOfAccountsAccountIdLtiRegistrationsIdBindPostRequest(value: object): value is AccountsAccountIdLtiRegistrationsIdBindPostRequest {
    if (!('workflowState' in value) || value['workflowState'] === undefined) return false;
    return true;
}

export function AccountsAccountIdLtiRegistrationsIdBindPostRequestFromJSON(json: any): AccountsAccountIdLtiRegistrationsIdBindPostRequest {
    return AccountsAccountIdLtiRegistrationsIdBindPostRequestFromJSONTyped(json, false);
}

export function AccountsAccountIdLtiRegistrationsIdBindPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsAccountIdLtiRegistrationsIdBindPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'workflowState': json['workflow_state'],
    };
}

export function AccountsAccountIdLtiRegistrationsIdBindPostRequestToJSON(json: any): AccountsAccountIdLtiRegistrationsIdBindPostRequest {
    return AccountsAccountIdLtiRegistrationsIdBindPostRequestToJSONTyped(json, false);
}

export function AccountsAccountIdLtiRegistrationsIdBindPostRequestToJSONTyped(value?: AccountsAccountIdLtiRegistrationsIdBindPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflow_state': value['workflowState'],
    };
}

