/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountsAccountIdLtiRegistrationsIdPutRequest
 */
export interface AccountsAccountIdLtiRegistrationsIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountsAccountIdLtiRegistrationsIdPutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountsAccountIdLtiRegistrationsIdPutRequest
     */
    adminNickname?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountsAccountIdLtiRegistrationsIdPutRequest
     */
    description?: string;
    /**
     * Lti::ToolConfiguration or Lti::LegacyConfiguration. Not allowed for dynamic registrations.
     * @type {object}
     * @memberof AccountsAccountIdLtiRegistrationsIdPutRequest
     */
    _configuration?: object;
    /**
     * Lti::Overlay overrides.
     * @type {object}
     * @memberof AccountsAccountIdLtiRegistrationsIdPutRequest
     */
    overlay?: object;
    /**
     * 
     * @type {string}
     * @memberof AccountsAccountIdLtiRegistrationsIdPutRequest
     */
    workflowState?: AccountsAccountIdLtiRegistrationsIdPutRequestWorkflowStateEnum;
}


/**
 * @export
 */
export const AccountsAccountIdLtiRegistrationsIdPutRequestWorkflowStateEnum = {
    On: 'on',
    Off: 'off',
    Allow: 'allow'
} as const;
export type AccountsAccountIdLtiRegistrationsIdPutRequestWorkflowStateEnum = typeof AccountsAccountIdLtiRegistrationsIdPutRequestWorkflowStateEnum[keyof typeof AccountsAccountIdLtiRegistrationsIdPutRequestWorkflowStateEnum];


/**
 * Check if a given object implements the AccountsAccountIdLtiRegistrationsIdPutRequest interface.
 */
export function instanceOfAccountsAccountIdLtiRegistrationsIdPutRequest(value: object): value is AccountsAccountIdLtiRegistrationsIdPutRequest {
    return true;
}

export function AccountsAccountIdLtiRegistrationsIdPutRequestFromJSON(json: any): AccountsAccountIdLtiRegistrationsIdPutRequest {
    return AccountsAccountIdLtiRegistrationsIdPutRequestFromJSONTyped(json, false);
}

export function AccountsAccountIdLtiRegistrationsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountsAccountIdLtiRegistrationsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'adminNickname': json['admin_nickname'] == null ? undefined : json['admin_nickname'],
        'description': json['description'] == null ? undefined : json['description'],
        '_configuration': json['configuration'] == null ? undefined : json['configuration'],
        'overlay': json['overlay'] == null ? undefined : json['overlay'],
        'workflowState': json['workflow_state'] == null ? undefined : json['workflow_state'],
    };
}

export function AccountsAccountIdLtiRegistrationsIdPutRequestToJSON(json: any): AccountsAccountIdLtiRegistrationsIdPutRequest {
    return AccountsAccountIdLtiRegistrationsIdPutRequestToJSONTyped(json, false);
}

export function AccountsAccountIdLtiRegistrationsIdPutRequestToJSONTyped(value?: AccountsAccountIdLtiRegistrationsIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'admin_nickname': value['adminNickname'],
        'description': value['description'],
        'configuration': value['_configuration'],
        'overlay': value['overlay'],
        'workflow_state': value['workflowState'],
    };
}

