/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The author of the notification. Only available to admins when include_all is used.
 * @export
 * @interface AccountNotificationAuthor
 */
export interface AccountNotificationAuthor {
    /**
     * 
     * @type {number}
     * @memberof AccountNotificationAuthor
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountNotificationAuthor
     */
    name?: string;
}

/**
 * Check if a given object implements the AccountNotificationAuthor interface.
 */
export function instanceOfAccountNotificationAuthor(value: object): value is AccountNotificationAuthor {
    return true;
}

export function AccountNotificationAuthorFromJSON(json: any): AccountNotificationAuthor {
    return AccountNotificationAuthorFromJSONTyped(json, false);
}

export function AccountNotificationAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountNotificationAuthor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AccountNotificationAuthorToJSON(json: any): AccountNotificationAuthor {
    return AccountNotificationAuthorToJSONTyped(json, false);
}

export function AccountNotificationAuthorToJSONTyped(value?: AccountNotificationAuthor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

