/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Answer
 */
export interface Answer {
    /**
     * The unique identifier for the answer. Do not supply if this answer is part of a new question.
     * @type {number}
     * @memberof Answer
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    answerText?: string;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    answerWeight?: number;
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    answerComments?: string;
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    textAfterAnswers?: string;
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    answerMatchLeft?: string;
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    answerMatchRight?: string;
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    matchingAnswerIncorrectMatches?: string;
    /**
     * 
     * @type {string}
     * @memberof Answer
     */
    numericalAnswerType?: AnswerNumericalAnswerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    exact?: number;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    margin?: number;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    approximate?: number;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    precision?: number;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    start?: number;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    end?: number;
    /**
     * 
     * @type {number}
     * @memberof Answer
     */
    blankId?: number;
}


/**
 * @export
 */
export const AnswerNumericalAnswerTypeEnum = {
    ExactAnswer: 'exact_answer',
    RangeAnswer: 'range_answer',
    PrecisionAnswer: 'precision_answer'
} as const;
export type AnswerNumericalAnswerTypeEnum = typeof AnswerNumericalAnswerTypeEnum[keyof typeof AnswerNumericalAnswerTypeEnum];


/**
 * Check if a given object implements the Answer interface.
 */
export function instanceOfAnswer(value: object): value is Answer {
    return true;
}

export function AnswerFromJSON(json: any): Answer {
    return AnswerFromJSONTyped(json, false);
}

export function AnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Answer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'answerText': json['answer_text'] == null ? undefined : json['answer_text'],
        'answerWeight': json['answer_weight'] == null ? undefined : json['answer_weight'],
        'answerComments': json['answer_comments'] == null ? undefined : json['answer_comments'],
        'textAfterAnswers': json['text_after_answers'] == null ? undefined : json['text_after_answers'],
        'answerMatchLeft': json['answer_match_left'] == null ? undefined : json['answer_match_left'],
        'answerMatchRight': json['answer_match_right'] == null ? undefined : json['answer_match_right'],
        'matchingAnswerIncorrectMatches': json['matching_answer_incorrect_matches'] == null ? undefined : json['matching_answer_incorrect_matches'],
        'numericalAnswerType': json['numerical_answer_type'] == null ? undefined : json['numerical_answer_type'],
        'exact': json['exact'] == null ? undefined : json['exact'],
        'margin': json['margin'] == null ? undefined : json['margin'],
        'approximate': json['approximate'] == null ? undefined : json['approximate'],
        'precision': json['precision'] == null ? undefined : json['precision'],
        'start': json['start'] == null ? undefined : json['start'],
        'end': json['end'] == null ? undefined : json['end'],
        'blankId': json['blank_id'] == null ? undefined : json['blank_id'],
    };
}

export function AnswerToJSON(json: any): Answer {
    return AnswerToJSONTyped(json, false);
}

export function AnswerToJSONTyped(value?: Answer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'answer_text': value['answerText'],
        'answer_weight': value['answerWeight'],
        'answer_comments': value['answerComments'],
        'text_after_answers': value['textAfterAnswers'],
        'answer_match_left': value['answerMatchLeft'],
        'answer_match_right': value['answerMatchRight'],
        'matching_answer_incorrect_matches': value['matchingAnswerIncorrectMatches'],
        'numerical_answer_type': value['numericalAnswerType'],
        'exact': value['exact'],
        'margin': value['margin'],
        'approximate': value['approximate'],
        'precision': value['precision'],
        'start': value['start'],
        'end': value['end'],
        'blank_id': value['blankId'],
    };
}

