/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An object with a single key - 'Url'.
 * @export
 * @interface ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata
 */
export interface ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata {
    /**
     * The endpoint URL or queue identifier to receive events.
     * @type {string}
     * @memberof ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata
     */
    url?: string;
}

/**
 * Check if a given object implements the ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata interface.
 */
export function instanceOfApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata(value: object): value is ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata {
    return true;
}

export function ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadataFromJSON(json: any): ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata {
    return ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadataFromJSONTyped(json, false);
}

export function ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['Url'] == null ? undefined : json['Url'],
    };
}

export function ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadataToJSON(json: any): ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata {
    return ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadataToJSONTyped(json, false);
}

export function ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadataToJSONTyped(value?: ApiLtiSubscriptionsPostRequestSubscriptionTransportMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Url': value['url'],
    };
}

