/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner
 */
export interface ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner {
    /**
     * 
     * @type {string}
     * @memberof ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner
     */
    noticeType?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner
     */
    handler?: string;
}

/**
 * Check if a given object implements the ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner interface.
 */
export function instanceOfApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner(value: object): value is ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner {
    return true;
}

export function ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInnerFromJSON(json: any): ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner {
    return ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInnerFromJSONTyped(json, false);
}

export function ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'noticeType': json['notice_type'] == null ? undefined : json['notice_type'],
        'handler': json['handler'] == null ? undefined : json['handler'],
    };
}

export function ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInnerToJSON(json: any): ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner {
    return ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInnerToJSONTyped(json, false);
}

export function ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInnerToJSONTyped(value?: ApiLtiNoticeHandlersDeploymentIdGet200ResponseNoticeHandlersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notice_type': value['noticeType'],
        'handler': value['handler'],
    };
}

