/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLtiNoticeHandlersDeploymentIdPutRequest
 */
export interface ApiLtiNoticeHandlersDeploymentIdPutRequest {
    /**
     * The notice type to handle
     * @type {string}
     * @memberof ApiLtiNoticeHandlersDeploymentIdPutRequest
     */
    noticeType: string;
    /**
     * The public endpoint URL for receiving notices; empty to unregister
     * @type {string}
     * @memberof ApiLtiNoticeHandlersDeploymentIdPutRequest
     */
    handler: string;
}

/**
 * Check if a given object implements the ApiLtiNoticeHandlersDeploymentIdPutRequest interface.
 */
export function instanceOfApiLtiNoticeHandlersDeploymentIdPutRequest(value: object): value is ApiLtiNoticeHandlersDeploymentIdPutRequest {
    if (!('noticeType' in value) || value['noticeType'] === undefined) return false;
    if (!('handler' in value) || value['handler'] === undefined) return false;
    return true;
}

export function ApiLtiNoticeHandlersDeploymentIdPutRequestFromJSON(json: any): ApiLtiNoticeHandlersDeploymentIdPutRequest {
    return ApiLtiNoticeHandlersDeploymentIdPutRequestFromJSONTyped(json, false);
}

export function ApiLtiNoticeHandlersDeploymentIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLtiNoticeHandlersDeploymentIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'noticeType': json['notice_type'],
        'handler': json['handler'],
    };
}

export function ApiLtiNoticeHandlersDeploymentIdPutRequestToJSON(json: any): ApiLtiNoticeHandlersDeploymentIdPutRequest {
    return ApiLtiNoticeHandlersDeploymentIdPutRequestToJSONTyped(json, false);
}

export function ApiLtiNoticeHandlersDeploymentIdPutRequestToJSONTyped(value?: ApiLtiNoticeHandlersDeploymentIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notice_type': value['noticeType'],
        'handler': value['handler'],
    };
}

