/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiLtiAccountsAccountIdAuthorizePost200Response
 */
export interface ApiLtiAccountsAccountIdAuthorizePost200Response {
    /**
     * JWT access token
     * @type {string}
     * @memberof ApiLtiAccountsAccountIdAuthorizePost200Response
     */
    accessToken?: string;
    /**
     * Token type (bearer)
     * @type {string}
     * @memberof ApiLtiAccountsAccountIdAuthorizePost200Response
     */
    tokenType?: string;
    /**
     * Token lifetime in seconds
     * @type {number}
     * @memberof ApiLtiAccountsAccountIdAuthorizePost200Response
     */
    expiresIn?: number;
}

/**
 * Check if a given object implements the ApiLtiAccountsAccountIdAuthorizePost200Response interface.
 */
export function instanceOfApiLtiAccountsAccountIdAuthorizePost200Response(value: object): value is ApiLtiAccountsAccountIdAuthorizePost200Response {
    return true;
}

export function ApiLtiAccountsAccountIdAuthorizePost200ResponseFromJSON(json: any): ApiLtiAccountsAccountIdAuthorizePost200Response {
    return ApiLtiAccountsAccountIdAuthorizePost200ResponseFromJSONTyped(json, false);
}

export function ApiLtiAccountsAccountIdAuthorizePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLtiAccountsAccountIdAuthorizePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
    };
}

export function ApiLtiAccountsAccountIdAuthorizePost200ResponseToJSON(json: any): ApiLtiAccountsAccountIdAuthorizePost200Response {
    return ApiLtiAccountsAccountIdAuthorizePost200ResponseToJSONTyped(json, false);
}

export function ApiLtiAccountsAccountIdAuthorizePost200ResponseToJSONTyped(value?: ApiLtiAccountsAccountIdAuthorizePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
    };
}

