/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ServicesKalturaSessionPost200Response
 */
export interface ApiV1ServicesKalturaSessionPost200Response {
    /**
     * The Kaltura session id, for use in the Kaltura v3 API.
     * @type {string}
     * @memberof ApiV1ServicesKalturaSessionPost200Response
     */
    ks: string;
}

/**
 * Check if a given object implements the ApiV1ServicesKalturaSessionPost200Response interface.
 */
export function instanceOfApiV1ServicesKalturaSessionPost200Response(value: object): value is ApiV1ServicesKalturaSessionPost200Response {
    if (!('ks' in value) || value['ks'] === undefined) return false;
    return true;
}

export function ApiV1ServicesKalturaSessionPost200ResponseFromJSON(json: any): ApiV1ServicesKalturaSessionPost200Response {
    return ApiV1ServicesKalturaSessionPost200ResponseFromJSONTyped(json, false);
}

export function ApiV1ServicesKalturaSessionPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ServicesKalturaSessionPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ks': json['ks'],
    };
}

export function ApiV1ServicesKalturaSessionPost200ResponseToJSON(json: any): ApiV1ServicesKalturaSessionPost200Response {
    return ApiV1ServicesKalturaSessionPost200ResponseToJSONTyped(json, false);
}

export function ApiV1ServicesKalturaSessionPost200ResponseToJSONTyped(value?: ApiV1ServicesKalturaSessionPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ks': value['ks'],
    };
}

