/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1CoursesCourseIdSectionsPostRequestCourseSection } from './ApiV1CoursesCourseIdSectionsPostRequestCourseSection';
import {
    ApiV1CoursesCourseIdSectionsPostRequestCourseSectionFromJSON,
    ApiV1CoursesCourseIdSectionsPostRequestCourseSectionFromJSONTyped,
    ApiV1CoursesCourseIdSectionsPostRequestCourseSectionToJSON,
    ApiV1CoursesCourseIdSectionsPostRequestCourseSectionToJSONTyped,
} from './ApiV1CoursesCourseIdSectionsPostRequestCourseSection';

/**
 * 
 * @export
 * @interface ApiV1SectionsIdPutRequest
 */
export interface ApiV1SectionsIdPutRequest {
    /**
     * 
     * @type {ApiV1CoursesCourseIdSectionsPostRequestCourseSection}
     * @memberof ApiV1SectionsIdPutRequest
     */
    courseSection?: ApiV1CoursesCourseIdSectionsPostRequestCourseSection;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1SectionsIdPutRequest
     */
    overrideSisStickiness?: boolean;
}

/**
 * Check if a given object implements the ApiV1SectionsIdPutRequest interface.
 */
export function instanceOfApiV1SectionsIdPutRequest(value: object): value is ApiV1SectionsIdPutRequest {
    return true;
}

export function ApiV1SectionsIdPutRequestFromJSON(json: any): ApiV1SectionsIdPutRequest {
    return ApiV1SectionsIdPutRequestFromJSONTyped(json, false);
}

export function ApiV1SectionsIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SectionsIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseSection': json['course_section'] == null ? undefined : ApiV1CoursesCourseIdSectionsPostRequestCourseSectionFromJSON(json['course_section']),
        'overrideSisStickiness': json['override_sis_stickiness'] == null ? undefined : json['override_sis_stickiness'],
    };
}

export function ApiV1SectionsIdPutRequestToJSON(json: any): ApiV1SectionsIdPutRequest {
    return ApiV1SectionsIdPutRequestToJSONTyped(json, false);
}

export function ApiV1SectionsIdPutRequestToJSONTyped(value?: ApiV1SectionsIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'course_section': ApiV1CoursesCourseIdSectionsPostRequestCourseSectionToJSON(value['courseSection']),
        'override_sis_stickiness': value['overrideSisStickiness'],
    };
}

