/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1CoursesCourseIdFilesQuotaGet200Response
 */
export interface ApiV1CoursesCourseIdFilesQuotaGet200Response {
    /**
     * Total storage quota in bytes
     * @type {number}
     * @memberof ApiV1CoursesCourseIdFilesQuotaGet200Response
     */
    quota?: number;
    /**
     * Used storage quota in bytes
     * @type {number}
     * @memberof ApiV1CoursesCourseIdFilesQuotaGet200Response
     */
    quotaUsed?: number;
}

/**
 * Check if a given object implements the ApiV1CoursesCourseIdFilesQuotaGet200Response interface.
 */
export function instanceOfApiV1CoursesCourseIdFilesQuotaGet200Response(value: object): value is ApiV1CoursesCourseIdFilesQuotaGet200Response {
    return true;
}

export function ApiV1CoursesCourseIdFilesQuotaGet200ResponseFromJSON(json: any): ApiV1CoursesCourseIdFilesQuotaGet200Response {
    return ApiV1CoursesCourseIdFilesQuotaGet200ResponseFromJSONTyped(json, false);
}

export function ApiV1CoursesCourseIdFilesQuotaGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1CoursesCourseIdFilesQuotaGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'quota': json['quota'] == null ? undefined : json['quota'],
        'quotaUsed': json['quota_used'] == null ? undefined : json['quota_used'],
    };
}

export function ApiV1CoursesCourseIdFilesQuotaGet200ResponseToJSON(json: any): ApiV1CoursesCourseIdFilesQuotaGet200Response {
    return ApiV1CoursesCourseIdFilesQuotaGet200ResponseToJSONTyped(json, false);
}

export function ApiV1CoursesCourseIdFilesQuotaGet200ResponseToJSONTyped(value?: ApiV1CoursesCourseIdFilesQuotaGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quota': value['quota'],
        'quota_used': value['quotaUsed'],
    };
}

