/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest
 */
export interface ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest {
    /**
     * The attempt number of the quiz submission being taken.
     * @type {number}
     * @memberof ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest
     */
    attempt: number;
    /**
     * The unique validation token you received when the Quiz Submission was created.
     * @type {string}
     * @memberof ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest
     */
    validationToken: string;
    /**
     * Access code for the Quiz, if any.
     * @type {string}
     * @memberof ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest
     */
    accessCode?: string | null;
}

/**
 * Check if a given object implements the ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest interface.
 */
export function instanceOfApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest(value: object): value is ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest {
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('validationToken' in value) || value['validationToken'] === undefined) return false;
    return true;
}

export function ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequestFromJSON(json: any): ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest {
    return ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequestFromJSONTyped(json, false);
}

export function ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attempt': json['attempt'],
        'validationToken': json['validation_token'],
        'accessCode': json['access_code'] == null ? undefined : json['access_code'],
    };
}

export function ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequestToJSON(json: any): ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest {
    return ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequestToJSONTyped(json, false);
}

export function ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequestToJSONTyped(value?: ApiV1QuizSubmissionsQuizSubmissionIdQuestionsIdFlagPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempt': value['attempt'],
        'validation_token': value['validationToken'],
        'access_code': value['accessCode'],
    };
}

