/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1SubmissionsIdWhatIfGradesPutRequest
 */
export interface ApiV1SubmissionsIdWhatIfGradesPutRequest {
    /**
     * The score the student wants to test
     * @type {number}
     * @memberof ApiV1SubmissionsIdWhatIfGradesPutRequest
     */
    studentEnteredScore: number;
}

/**
 * Check if a given object implements the ApiV1SubmissionsIdWhatIfGradesPutRequest interface.
 */
export function instanceOfApiV1SubmissionsIdWhatIfGradesPutRequest(value: object): value is ApiV1SubmissionsIdWhatIfGradesPutRequest {
    if (!('studentEnteredScore' in value) || value['studentEnteredScore'] === undefined) return false;
    return true;
}

export function ApiV1SubmissionsIdWhatIfGradesPutRequestFromJSON(json: any): ApiV1SubmissionsIdWhatIfGradesPutRequest {
    return ApiV1SubmissionsIdWhatIfGradesPutRequestFromJSONTyped(json, false);
}

export function ApiV1SubmissionsIdWhatIfGradesPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1SubmissionsIdWhatIfGradesPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'studentEnteredScore': json['student_entered_score'],
    };
}

export function ApiV1SubmissionsIdWhatIfGradesPutRequestToJSON(json: any): ApiV1SubmissionsIdWhatIfGradesPutRequest {
    return ApiV1SubmissionsIdWhatIfGradesPutRequestToJSONTyped(json, false);
}

export function ApiV1SubmissionsIdWhatIfGradesPutRequestToJSONTyped(value?: ApiV1SubmissionsIdWhatIfGradesPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'student_entered_score': value['studentEnteredScore'],
    };
}

