/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz
 */
export interface ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz {
    /**
     * If true, notifies users that the quiz has changed.
     * @type {boolean}
     * @memberof ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz
     */
    notifyOfUpdate?: boolean;
}

/**
 * Check if a given object implements the ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz interface.
 */
export function instanceOfApiV1CoursesCourseIdQuizzesIdPutRequestQuiz(value: object): value is ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz {
    return true;
}

export function ApiV1CoursesCourseIdQuizzesIdPutRequestQuizFromJSON(json: any): ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz {
    return ApiV1CoursesCourseIdQuizzesIdPutRequestQuizFromJSONTyped(json, false);
}

export function ApiV1CoursesCourseIdQuizzesIdPutRequestQuizFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz {
    if (json == null) {
        return json;
    }
    return {
        
        'notifyOfUpdate': json['notify_of_update'] == null ? undefined : json['notify_of_update'],
    };
}

export function ApiV1CoursesCourseIdQuizzesIdPutRequestQuizToJSON(json: any): ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz {
    return ApiV1CoursesCourseIdQuizzesIdPutRequestQuizToJSONTyped(json, false);
}

export function ApiV1CoursesCourseIdQuizzesIdPutRequestQuizToJSONTyped(value?: ApiV1CoursesCourseIdQuizzesIdPutRequestQuiz | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notify_of_update': value['notifyOfUpdate'],
    };
}

