/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuizSubmissionQuestionInput } from './QuizSubmissionQuestionInput';
import {
    QuizSubmissionQuestionInputFromJSON,
    QuizSubmissionQuestionInputFromJSONTyped,
    QuizSubmissionQuestionInputToJSON,
    QuizSubmissionQuestionInputToJSONTyped,
} from './QuizSubmissionQuestionInput';

/**
 * 
 * @export
 * @interface ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest
 */
export interface ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest {
    /**
     * The attempt number of the quiz submission being taken.
     * @type {number}
     * @memberof ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest
     */
    attempt: number;
    /**
     * The unique validation token you received when the Quiz Submission was created.
     * @type {string}
     * @memberof ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest
     */
    validationToken: string;
    /**
     * Access code for the Quiz, if any.
     * @type {string}
     * @memberof ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest
     */
    accessCode?: string | null;
    /**
     * 
     * @type {Array<QuizSubmissionQuestionInput>}
     * @memberof ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest
     */
    quizQuestions?: Array<QuizSubmissionQuestionInput>;
}

/**
 * Check if a given object implements the ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest interface.
 */
export function instanceOfApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest(value: object): value is ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest {
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('validationToken' in value) || value['validationToken'] === undefined) return false;
    return true;
}

export function ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequestFromJSON(json: any): ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest {
    return ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequestFromJSONTyped(json, false);
}

export function ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'attempt': json['attempt'],
        'validationToken': json['validation_token'],
        'accessCode': json['access_code'] == null ? undefined : json['access_code'],
        'quizQuestions': json['quiz_questions'] == null ? undefined : ((json['quiz_questions'] as Array<any>).map(QuizSubmissionQuestionInputFromJSON)),
    };
}

export function ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequestToJSON(json: any): ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest {
    return ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequestToJSONTyped(json, false);
}

export function ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequestToJSONTyped(value?: ApiV1QuizSubmissionsQuizSubmissionIdQuestionsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempt': value['attempt'],
        'validation_token': value['validationToken'],
        'access_code': value['accessCode'],
        'quiz_questions': value['quizQuestions'] == null ? undefined : ((value['quizQuestions'] as Array<any>).map(QuizSubmissionQuestionInputToJSON)),
    };
}

