/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExternalToolTagAttributes } from './ExternalToolTagAttributes';
import {
    ExternalToolTagAttributesFromJSON,
    ExternalToolTagAttributesFromJSONTyped,
    ExternalToolTagAttributesToJSON,
    ExternalToolTagAttributesToJSONTyped,
} from './ExternalToolTagAttributes';
import type { NeedsGradingCount } from './NeedsGradingCount';
import {
    NeedsGradingCountFromJSON,
    NeedsGradingCountFromJSONTyped,
    NeedsGradingCountToJSON,
    NeedsGradingCountToJSONTyped,
} from './NeedsGradingCount';
import type { AssignmentDate } from './AssignmentDate';
import {
    AssignmentDateFromJSON,
    AssignmentDateFromJSONTyped,
    AssignmentDateToJSON,
    AssignmentDateToJSONTyped,
} from './AssignmentDate';
import type { TurnitinSettings } from './TurnitinSettings';
import {
    TurnitinSettingsFromJSON,
    TurnitinSettingsFromJSONTyped,
    TurnitinSettingsToJSON,
    TurnitinSettingsToJSONTyped,
} from './TurnitinSettings';
import type { AssignmentRubricSettings } from './AssignmentRubricSettings';
import {
    AssignmentRubricSettingsFromJSON,
    AssignmentRubricSettingsFromJSONTyped,
    AssignmentRubricSettingsToJSON,
    AssignmentRubricSettingsToJSONTyped,
} from './AssignmentRubricSettings';
import type { LockInfo } from './LockInfo';
import {
    LockInfoFromJSON,
    LockInfoFromJSONTyped,
    LockInfoToJSON,
    LockInfoToJSONTyped,
} from './LockInfo';
import type { RubricCriteria } from './RubricCriteria';
import {
    RubricCriteriaFromJSON,
    RubricCriteriaFromJSONTyped,
    RubricCriteriaToJSON,
    RubricCriteriaToJSONTyped,
} from './RubricCriteria';
import type { AssignmentOverride } from './AssignmentOverride';
import {
    AssignmentOverrideFromJSON,
    AssignmentOverrideFromJSONTyped,
    AssignmentOverrideToJSON,
    AssignmentOverrideToJSONTyped,
} from './AssignmentOverride';
import type { ScoreStatistic } from './ScoreStatistic';
import {
    ScoreStatisticFromJSON,
    ScoreStatisticFromJSONTyped,
    ScoreStatisticToJSON,
    ScoreStatisticToJSONTyped,
} from './ScoreStatistic';

/**
 * Represents a Canvas Assignment.
 * @export
 * @interface Assignment
 */
export interface Assignment {
    /**
     * The ID of the assignment.
     * @type {number}
     * @memberof Assignment
     */
    readonly id: number;
    /**
     * The name of the assignment.
     * @type {string}
     * @memberof Assignment
     */
    name: string;
    /**
     * The assignment description, in an HTML fragment.
     * @type {string}
     * @memberof Assignment
     */
    description?: string | null;
    /**
     * The time at which this assignment was originally created.
     * @type {Date}
     * @memberof Assignment
     */
    readonly createdAt: Date;
    /**
     * The time at which this assignment was last modified.
     * @type {Date}
     * @memberof Assignment
     */
    readonly updatedAt: Date;
    /**
     * The due date for the assignment. Responds to overrides unless overridden.
     * @type {Date}
     * @memberof Assignment
     */
    dueAt?: Date | null;
    /**
     * The lock date. Responds to overrides unless overridden.
     * @type {Date}
     * @memberof Assignment
     */
    lockAt?: Date | null;
    /**
     * The unlock date. Responds to overrides unless overridden.
     * @type {Date}
     * @memberof Assignment
     */
    unlockAt?: Date | null;
    /**
     * Whether this assignment has overrides.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly hasOverrides: boolean;
    /**
     * (Optional) All dates associated with the assignment (requires 'include[]=all_dates'). Base dates and override dates.
     * @type {Array<AssignmentDate>}
     * @memberof Assignment
     */
    readonly allDates?: Array<AssignmentDate> | null;
    /**
     * The ID of the course the assignment belongs to.
     * @type {number}
     * @memberof Assignment
     */
    readonly courseId: number;
    /**
     * The URL to the assignment's web page.
     * @type {string}
     * @memberof Assignment
     */
    readonly htmlUrl: string;
    /**
     * The URL to download all submissions as a zip. May be null if not available.
     * @type {string}
     * @memberof Assignment
     */
    readonly submissionsDownloadUrl?: string | null;
    /**
     * The ID of the assignment's group.
     * @type {number}
     * @memberof Assignment
     */
    assignmentGroupId: number;
    /**
     * If the assignment requires a due date based on account setting.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly dueDateRequired: boolean;
    /**
     * Allowed file extensions for 'online_upload'. Null if not applicable.
     * @type {Array<string>}
     * @memberof Assignment
     */
    allowedExtensions?: Array<string> | null;
    /**
     * Maximum length allowed for the assignment's name.
     * @type {number}
     * @memberof Assignment
     */
    readonly maxNameLength: number;
    /**
     * If Turnitin is enabled (requires plugin).
     * @type {boolean}
     * @memberof Assignment
     */
    turnitinEnabled: boolean;
    /**
     * If VeriCite is enabled (requires plugin).
     * @type {boolean}
     * @memberof Assignment
     */
    vericiteEnabled: boolean;
    /**
     * 
     * @type {TurnitinSettings}
     * @memberof Assignment
     */
    turnitinSettings?: TurnitinSettings;
    /**
     * If students in a group assignment will be graded individually. Null if not a group assignment.
     * @type {boolean}
     * @memberof Assignment
     */
    gradeGroupStudentsIndividually?: boolean | null;
    /**
     * 
     * @type {ExternalToolTagAttributes}
     * @memberof Assignment
     */
    externalToolTagAttributes?: ExternalToolTagAttributes;
    /**
     * If peer reviews are required.
     * @type {boolean}
     * @memberof Assignment
     */
    peerReviews: boolean;
    /**
     * If peer reviews are assigned automatically.
     * @type {boolean}
     * @memberof Assignment
     */
    automaticPeerReviews: boolean;
    /**
     * Number of reviews each user is assigned (if automatic_peer_reviews).
     * @type {number}
     * @memberof Assignment
     */
    peerReviewCount?: number | null;
    /**
     * Date peer reviews are assigned (if automatic_peer_reviews). Uses assignment due date if null/invalid.
     * @type {Date}
     * @memberof Assignment
     */
    peerReviewsAssignAt?: Date | null;
    /**
     * If members of the same group can review their own group's work.
     * @type {boolean}
     * @memberof Assignment
     */
    intraGroupPeerReviews?: boolean;
    /**
     * The ID of the assignment group set (if group assignment).
     * @type {number}
     * @memberof Assignment
     */
    groupCategoryId?: number | null;
    /**
     * Number of submissions needing grading (if grader). 0 if not a grader.
     * @type {number}
     * @memberof Assignment
     */
    readonly needsGradingCount?: number;
    /**
     * Needs grading count breakdown by section (requires 'needs_grading_count_by_section' flag and grader role).
     * @type {Array<NeedsGradingCount>}
     * @memberof Assignment
     */
    readonly needsGradingCountBySection?: Array<NeedsGradingCount>;
    /**
     * The sorting order of the assignment in the group.
     * @type {number}
     * @memberof Assignment
     */
    position: number;
    /**
     * (Optional) If Sync Grades to SIS feature is enabled and this assignment is marked for sync.
     * @type {boolean}
     * @memberof Assignment
     */
    postToSis?: boolean | null;
    /**
     * (Optional) Third party unique identifier for Assignment.
     * @type {string}
     * @memberof Assignment
     */
    integrationId?: string | null;
    /**
     * (Optional) Third party integration data.
     * @type {{ [key: string]: any; }}
     * @memberof Assignment
     */
    integrationData?: { [key: string]: any; } | null;
    /**
     * The maximum points possible.
     * @type {number}
     * @memberof Assignment
     */
    pointsPossible?: number | null;
    /**
     * Allowed submission types.
     * @type {Array<string>}
     * @memberof Assignment
     */
    submissionTypes: Array<AssignmentSubmissionTypesEnum>;
    /**
     * If at least one student has submitted.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly hasSubmittedSubmissions: boolean;
    /**
     * Grading strategy.
     * @type {string}
     * @memberof Assignment
     */
    gradingType: AssignmentGradingTypeEnum;
    /**
     * ID of the grading standard (if letter_grade or gpa_scale).
     * @type {number}
     * @memberof Assignment
     */
    gradingStandardId?: number | null;
    /**
     * Whether the assignment is published.
     * @type {boolean}
     * @memberof Assignment
     */
    published: boolean;
    /**
     * If the published state can be changed to false (false if submissions exist).
     * @type {boolean}
     * @memberof Assignment
     */
    readonly unpublishable: boolean;
    /**
     * Whether the assignment is only visible to overrides.
     * @type {boolean}
     * @memberof Assignment
     */
    onlyVisibleToOverrides: boolean;
    /**
     * Whether the assignment is locked for the current user based on dates or module prerequisites.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly lockedForUser: boolean;
    /**
     * 
     * @type {LockInfo}
     * @memberof Assignment
     */
    lockInfo?: LockInfo;
    /**
     * (Optional) Explanation of why this is locked for the user. Present when locked_for_user is true.
     * @type {string}
     * @memberof Assignment
     */
    readonly lockExplanation?: string | null;
    /**
     * (Optional) ID of the associated quiz (if submission_types is ['online_quiz']).
     * @type {number}
     * @memberof Assignment
     */
    readonly quizId?: number | null;
    /**
     * (Optional) Allow anonymous submissions (quiz only). Usually a quiz setting, may be read-only here.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly anonymousSubmissions?: boolean | null;
    /**
     * (Optional) Associated DiscussionTopic object (if submission_types is ['discussion_topic']).
     * @type {object}
     * @memberof Assignment
     */
    readonly discussionTopic?: object | null;
    /**
     * (Optional) Freeze assignment when copied (requires AssignmentFreezer plugin).
     * @type {boolean}
     * @memberof Assignment
     */
    freezeOnCopy?: boolean;
    /**
     * (Optional) If assignment is frozen for the user (requires AssignmentFreezer plugin).
     * @type {boolean}
     * @memberof Assignment
     */
    readonly frozen?: boolean;
    /**
     * (Optional) List of frozen attributes (requires AssignmentFreezer plugin). Empty if none frozen.
     * @type {Array<string>}
     * @memberof Assignment
     */
    readonly frozenAttributes?: Array<AssignmentFrozenAttributesEnum> | null;
    /**
     * (Optional) Current user's submission (requires 'include[]=submission'). Absent if no submission.
     * @type {object}
     * @memberof Assignment
     */
    readonly submission?: object | null;
    /**
     * (Optional) If the rubric is used for grading (if rubric exists).
     * @type {boolean}
     * @memberof Assignment
     */
    useRubricForGrading?: boolean | null;
    /**
     * 
     * @type {AssignmentRubricSettings}
     * @memberof Assignment
     */
    rubricSettings?: AssignmentRubricSettings | null;
    /**
     * (Optional) List of rubric criteria (if rubric exists).
     * @type {Array<RubricCriteria>}
     * @memberof Assignment
     */
    rubric?: Array<RubricCriteria> | null;
    /**
     * (Optional) Student IDs who can see this assignment (requires 'include[]=assignment_visibility').
     * @type {Array<number>}
     * @memberof Assignment
     */
    readonly assignmentVisibility?: Array<number> | null;
    /**
     * (Optional) List of override objects (requires 'include[]=overrides').
     * @type {Array<AssignmentOverride>}
     * @memberof Assignment
     */
    readonly overrides?: Array<AssignmentOverride> | null;
    /**
     * (Optional) Omit assignment from the student's final grade.
     * @type {boolean}
     * @memberof Assignment
     */
    omitFromFinalGrade: boolean;
    /**
     * (Optional) Hide assignment in gradebooks.
     * @type {boolean}
     * @memberof Assignment
     */
    hideInGradebook: boolean;
    /**
     * If the assignment is moderated.
     * @type {boolean}
     * @memberof Assignment
     */
    moderatedGrading: boolean;
    /**
     * Number of provisional graders (if moderated).
     * @type {number}
     * @memberof Assignment
     */
    graderCount?: number | null;
    /**
     * User ID of the final grader (if moderated).
     * @type {number}
     * @memberof Assignment
     */
    finalGraderId?: number | null;
    /**
     * If provisional grader comments are visible to others (if moderated).
     * @type {boolean}
     * @memberof Assignment
     */
    graderCommentsVisibleToGraders?: boolean | null;
    /**
     * If provisional grader identities are hidden from others (if moderated).
     * @type {boolean}
     * @memberof Assignment
     */
    gradersAnonymousToGraders?: boolean | null;
    /**
     * If provisional grader names are visible to the final grader (if moderated).
     * @type {boolean}
     * @memberof Assignment
     */
    graderNamesVisibleToFinalGrader?: boolean | null;
    /**
     * If the assignment is graded anonymously.
     * @type {boolean}
     * @memberof Assignment
     */
    anonymousGrading: boolean;
    /**
     * Number of submission attempts allowed (-1 for unlimited).
     * @type {number}
     * @memberof Assignment
     */
    allowedAttempts: number;
    /**
     * If manual posting is enabled (New Gradebook).
     * @type {boolean}
     * @memberof Assignment
     */
    postManually: boolean;
    /**
     * 
     * @type {ScoreStatistic}
     * @memberof Assignment
     */
    scoreStatistics?: ScoreStatistic;
    /**
     * (Optional) If the current user can submit (requires 'include[]=can_submit'). Checks dates, status, attempts etc. Not available with observed_users.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly canSubmit?: boolean;
    /**
     * (Optional) Academic benchmark GUIDs associated with the assignment or rubric (requires 'include[]=ab_guid').
     * @type {Array<string>}
     * @memberof Assignment
     */
    readonly abGuid?: Array<string> | null;
    /**
     * Attachment ID for student annotation submissions (if submission_types includes 'student_annotation').
     * @type {number}
     * @memberof Assignment
     */
    annotatableAttachmentId?: number | null;
    /**
     * (Optional) Anonymize student names in submissions.
     * @type {boolean}
     * @memberof Assignment
     */
    anonymizeStudents?: boolean;
    /**
     * (Optional) Require Respondus LockDown Browser®.
     * @type {boolean}
     * @memberof Assignment
     */
    requireLockdownBrowser?: boolean;
    /**
     * (Optional) If the assignment has important dates (e.g., due, lock, unlock).
     * @type {boolean}
     * @memberof Assignment
     */
    readonly importantDates?: boolean;
    /**
     * (Deprecated - use post_manually) If notifications are muted.
     * @type {boolean}
     * @memberof Assignment
     * @deprecated
     */
    muted?: boolean;
    /**
     * If peer reviews are anonymous.
     * @type {boolean}
     * @memberof Assignment
     */
    anonymousPeerReviews: boolean;
    /**
     * If instructor annotations are anonymous.
     * @type {boolean}
     * @memberof Assignment
     */
    anonymousInstructorAnnotations: boolean;
    /**
     * If graded submissions exist.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly gradedSubmissionsExist: boolean;
    /**
     * If this is a quiz LTI assignment.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly isQuizAssignment: boolean;
    /**
     * If the assignment is in a closed grading period.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly inClosedGradingPeriod: boolean;
    /**
     * If the assignment can be duplicated by the current user.
     * @type {boolean}
     * @memberof Assignment
     */
    readonly canDuplicate: boolean;
    /**
     * Original course ID if duplicated.
     * @type {number}
     * @memberof Assignment
     */
    readonly originalCourseId?: number | null;
    /**
     * Original assignment ID if duplicated.
     * @type {number}
     * @memberof Assignment
     */
    readonly originalAssignmentId?: number | null;
    /**
     * Original LTI resource link ID if duplicated.
     * @type {number}
     * @memberof Assignment
     */
    readonly originalLtiResourceLinkId?: number | null;
    /**
     * Original assignment name if duplicated.
     * @type {string}
     * @memberof Assignment
     */
    readonly originalAssignmentName?: string | null;
    /**
     * Original quiz ID if duplicated.
     * @type {number}
     * @memberof Assignment
     */
    readonly originalQuizId?: number | null;
    /**
     * The workflow state ('published' or 'unpublished'). Changed via 'published' flag.
     * @type {string}
     * @memberof Assignment
     */
    readonly workflowState: AssignmentWorkflowStateEnum;
}


/**
 * @export
 */
export const AssignmentSubmissionTypesEnum = {
    DiscussionTopic: 'discussion_topic',
    OnlineQuiz: 'online_quiz',
    OnPaper: 'on_paper',
    None: 'none',
    ExternalTool: 'external_tool',
    OnlineTextEntry: 'online_text_entry',
    OnlineUrl: 'online_url',
    OnlineUpload: 'online_upload',
    MediaRecording: 'media_recording',
    StudentAnnotation: 'student_annotation'
} as const;
export type AssignmentSubmissionTypesEnum = typeof AssignmentSubmissionTypesEnum[keyof typeof AssignmentSubmissionTypesEnum];

/**
 * @export
 */
export const AssignmentGradingTypeEnum = {
    PassFail: 'pass_fail',
    Percent: 'percent',
    LetterGrade: 'letter_grade',
    GpaScale: 'gpa_scale',
    Points: 'points',
    NotGraded: 'not_graded'
} as const;
export type AssignmentGradingTypeEnum = typeof AssignmentGradingTypeEnum[keyof typeof AssignmentGradingTypeEnum];

/**
 * @export
 */
export const AssignmentFrozenAttributesEnum = {
    Title: 'title',
    Description: 'description',
    LockAt: 'lock_at',
    PointsPossible: 'points_possible',
    GradingType: 'grading_type',
    SubmissionTypes: 'submission_types',
    AssignmentGroupId: 'assignment_group_id',
    AllowedExtensions: 'allowed_extensions',
    GroupCategoryId: 'group_category_id',
    NotifyOfUpdate: 'notify_of_update',
    PeerReviews: 'peer_reviews'
} as const;
export type AssignmentFrozenAttributesEnum = typeof AssignmentFrozenAttributesEnum[keyof typeof AssignmentFrozenAttributesEnum];

/**
 * @export
 */
export const AssignmentWorkflowStateEnum = {
    Published: 'published',
    Unpublished: 'unpublished'
} as const;
export type AssignmentWorkflowStateEnum = typeof AssignmentWorkflowStateEnum[keyof typeof AssignmentWorkflowStateEnum];


/**
 * Check if a given object implements the Assignment interface.
 */
export function instanceOfAssignment(value: object): value is Assignment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('hasOverrides' in value) || value['hasOverrides'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('htmlUrl' in value) || value['htmlUrl'] === undefined) return false;
    if (!('assignmentGroupId' in value) || value['assignmentGroupId'] === undefined) return false;
    if (!('dueDateRequired' in value) || value['dueDateRequired'] === undefined) return false;
    if (!('maxNameLength' in value) || value['maxNameLength'] === undefined) return false;
    if (!('turnitinEnabled' in value) || value['turnitinEnabled'] === undefined) return false;
    if (!('vericiteEnabled' in value) || value['vericiteEnabled'] === undefined) return false;
    if (!('peerReviews' in value) || value['peerReviews'] === undefined) return false;
    if (!('automaticPeerReviews' in value) || value['automaticPeerReviews'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('submissionTypes' in value) || value['submissionTypes'] === undefined) return false;
    if (!('hasSubmittedSubmissions' in value) || value['hasSubmittedSubmissions'] === undefined) return false;
    if (!('gradingType' in value) || value['gradingType'] === undefined) return false;
    if (!('published' in value) || value['published'] === undefined) return false;
    if (!('unpublishable' in value) || value['unpublishable'] === undefined) return false;
    if (!('onlyVisibleToOverrides' in value) || value['onlyVisibleToOverrides'] === undefined) return false;
    if (!('lockedForUser' in value) || value['lockedForUser'] === undefined) return false;
    if (!('omitFromFinalGrade' in value) || value['omitFromFinalGrade'] === undefined) return false;
    if (!('hideInGradebook' in value) || value['hideInGradebook'] === undefined) return false;
    if (!('moderatedGrading' in value) || value['moderatedGrading'] === undefined) return false;
    if (!('anonymousGrading' in value) || value['anonymousGrading'] === undefined) return false;
    if (!('allowedAttempts' in value) || value['allowedAttempts'] === undefined) return false;
    if (!('postManually' in value) || value['postManually'] === undefined) return false;
    if (!('anonymousPeerReviews' in value) || value['anonymousPeerReviews'] === undefined) return false;
    if (!('anonymousInstructorAnnotations' in value) || value['anonymousInstructorAnnotations'] === undefined) return false;
    if (!('gradedSubmissionsExist' in value) || value['gradedSubmissionsExist'] === undefined) return false;
    if (!('isQuizAssignment' in value) || value['isQuizAssignment'] === undefined) return false;
    if (!('inClosedGradingPeriod' in value) || value['inClosedGradingPeriod'] === undefined) return false;
    if (!('canDuplicate' in value) || value['canDuplicate'] === undefined) return false;
    if (!('workflowState' in value) || value['workflowState'] === undefined) return false;
    return true;
}

export function AssignmentFromJSON(json: any): Assignment {
    return AssignmentFromJSONTyped(json, false);
}

export function AssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Assignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'dueAt': json['due_at'] == null ? undefined : (new Date(json['due_at'])),
        'lockAt': json['lock_at'] == null ? undefined : (new Date(json['lock_at'])),
        'unlockAt': json['unlock_at'] == null ? undefined : (new Date(json['unlock_at'])),
        'hasOverrides': json['has_overrides'],
        'allDates': json['all_dates'] == null ? undefined : ((json['all_dates'] as Array<any>).map(AssignmentDateFromJSON)),
        'courseId': json['course_id'],
        'htmlUrl': json['html_url'],
        'submissionsDownloadUrl': json['submissions_download_url'] == null ? undefined : json['submissions_download_url'],
        'assignmentGroupId': json['assignment_group_id'],
        'dueDateRequired': json['due_date_required'],
        'allowedExtensions': json['allowed_extensions'] == null ? undefined : json['allowed_extensions'],
        'maxNameLength': json['max_name_length'],
        'turnitinEnabled': json['turnitin_enabled'],
        'vericiteEnabled': json['vericite_enabled'],
        'turnitinSettings': json['turnitin_settings'] == null ? undefined : TurnitinSettingsFromJSON(json['turnitin_settings']),
        'gradeGroupStudentsIndividually': json['grade_group_students_individually'] == null ? undefined : json['grade_group_students_individually'],
        'externalToolTagAttributes': json['external_tool_tag_attributes'] == null ? undefined : ExternalToolTagAttributesFromJSON(json['external_tool_tag_attributes']),
        'peerReviews': json['peer_reviews'],
        'automaticPeerReviews': json['automatic_peer_reviews'],
        'peerReviewCount': json['peer_review_count'] == null ? undefined : json['peer_review_count'],
        'peerReviewsAssignAt': json['peer_reviews_assign_at'] == null ? undefined : (new Date(json['peer_reviews_assign_at'])),
        'intraGroupPeerReviews': json['intra_group_peer_reviews'] == null ? undefined : json['intra_group_peer_reviews'],
        'groupCategoryId': json['group_category_id'] == null ? undefined : json['group_category_id'],
        'needsGradingCount': json['needs_grading_count'] == null ? undefined : json['needs_grading_count'],
        'needsGradingCountBySection': json['needs_grading_count_by_section'] == null ? undefined : ((json['needs_grading_count_by_section'] as Array<any>).map(NeedsGradingCountFromJSON)),
        'position': json['position'],
        'postToSis': json['post_to_sis'] == null ? undefined : json['post_to_sis'],
        'integrationId': json['integration_id'] == null ? undefined : json['integration_id'],
        'integrationData': json['integration_data'] == null ? undefined : json['integration_data'],
        'pointsPossible': json['points_possible'] == null ? undefined : json['points_possible'],
        'submissionTypes': json['submission_types'],
        'hasSubmittedSubmissions': json['has_submitted_submissions'],
        'gradingType': json['grading_type'],
        'gradingStandardId': json['grading_standard_id'] == null ? undefined : json['grading_standard_id'],
        'published': json['published'],
        'unpublishable': json['unpublishable'],
        'onlyVisibleToOverrides': json['only_visible_to_overrides'],
        'lockedForUser': json['locked_for_user'],
        'lockInfo': json['lock_info'] == null ? undefined : LockInfoFromJSON(json['lock_info']),
        'lockExplanation': json['lock_explanation'] == null ? undefined : json['lock_explanation'],
        'quizId': json['quiz_id'] == null ? undefined : json['quiz_id'],
        'anonymousSubmissions': json['anonymous_submissions'] == null ? undefined : json['anonymous_submissions'],
        'discussionTopic': json['discussion_topic'] == null ? undefined : json['discussion_topic'],
        'freezeOnCopy': json['freeze_on_copy'] == null ? undefined : json['freeze_on_copy'],
        'frozen': json['frozen'] == null ? undefined : json['frozen'],
        'frozenAttributes': json['frozen_attributes'] == null ? undefined : json['frozen_attributes'],
        'submission': json['submission'] == null ? undefined : json['submission'],
        'useRubricForGrading': json['use_rubric_for_grading'] == null ? undefined : json['use_rubric_for_grading'],
        'rubricSettings': json['rubric_settings'] == null ? undefined : AssignmentRubricSettingsFromJSON(json['rubric_settings']),
        'rubric': json['rubric'] == null ? undefined : ((json['rubric'] as Array<any>).map(RubricCriteriaFromJSON)),
        'assignmentVisibility': json['assignment_visibility'] == null ? undefined : json['assignment_visibility'],
        'overrides': json['overrides'] == null ? undefined : ((json['overrides'] as Array<any>).map(AssignmentOverrideFromJSON)),
        'omitFromFinalGrade': json['omit_from_final_grade'],
        'hideInGradebook': json['hide_in_gradebook'],
        'moderatedGrading': json['moderated_grading'],
        'graderCount': json['grader_count'] == null ? undefined : json['grader_count'],
        'finalGraderId': json['final_grader_id'] == null ? undefined : json['final_grader_id'],
        'graderCommentsVisibleToGraders': json['grader_comments_visible_to_graders'] == null ? undefined : json['grader_comments_visible_to_graders'],
        'gradersAnonymousToGraders': json['graders_anonymous_to_graders'] == null ? undefined : json['graders_anonymous_to_graders'],
        'graderNamesVisibleToFinalGrader': json['grader_names_visible_to_final_grader'] == null ? undefined : json['grader_names_visible_to_final_grader'],
        'anonymousGrading': json['anonymous_grading'],
        'allowedAttempts': json['allowed_attempts'],
        'postManually': json['post_manually'],
        'scoreStatistics': json['score_statistics'] == null ? undefined : ScoreStatisticFromJSON(json['score_statistics']),
        'canSubmit': json['can_submit'] == null ? undefined : json['can_submit'],
        'abGuid': json['ab_guid'] == null ? undefined : json['ab_guid'],
        'annotatableAttachmentId': json['annotatable_attachment_id'] == null ? undefined : json['annotatable_attachment_id'],
        'anonymizeStudents': json['anonymize_students'] == null ? undefined : json['anonymize_students'],
        'requireLockdownBrowser': json['require_lockdown_browser'] == null ? undefined : json['require_lockdown_browser'],
        'importantDates': json['important_dates'] == null ? undefined : json['important_dates'],
        'muted': json['muted'] == null ? undefined : json['muted'],
        'anonymousPeerReviews': json['anonymous_peer_reviews'],
        'anonymousInstructorAnnotations': json['anonymous_instructor_annotations'],
        'gradedSubmissionsExist': json['graded_submissions_exist'],
        'isQuizAssignment': json['is_quiz_assignment'],
        'inClosedGradingPeriod': json['in_closed_grading_period'],
        'canDuplicate': json['can_duplicate'],
        'originalCourseId': json['original_course_id'] == null ? undefined : json['original_course_id'],
        'originalAssignmentId': json['original_assignment_id'] == null ? undefined : json['original_assignment_id'],
        'originalLtiResourceLinkId': json['original_lti_resource_link_id'] == null ? undefined : json['original_lti_resource_link_id'],
        'originalAssignmentName': json['original_assignment_name'] == null ? undefined : json['original_assignment_name'],
        'originalQuizId': json['original_quiz_id'] == null ? undefined : json['original_quiz_id'],
        'workflowState': json['workflow_state'],
    };
}

export function AssignmentToJSON(json: any): Assignment {
    return AssignmentToJSONTyped(json, false);
}

export function AssignmentToJSONTyped(value?: Omit<Assignment, 'id'|'created_at'|'updated_at'|'has_overrides'|'all_dates'|'course_id'|'html_url'|'submissions_download_url'|'due_date_required'|'max_name_length'|'needs_grading_count'|'needs_grading_count_by_section'|'has_submitted_submissions'|'unpublishable'|'locked_for_user'|'lock_explanation'|'quiz_id'|'anonymous_submissions'|'discussion_topic'|'frozen'|'frozen_attributes'|'submission'|'assignment_visibility'|'overrides'|'can_submit'|'ab_guid'|'important_dates'|'graded_submissions_exist'|'is_quiz_assignment'|'in_closed_grading_period'|'can_duplicate'|'original_course_id'|'original_assignment_id'|'original_lti_resource_link_id'|'original_assignment_name'|'original_quiz_id'|'workflow_state'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'due_at': value['dueAt'] == null ? undefined : ((value['dueAt'] as any).toISOString()),
        'lock_at': value['lockAt'] == null ? undefined : ((value['lockAt'] as any).toISOString()),
        'unlock_at': value['unlockAt'] == null ? undefined : ((value['unlockAt'] as any).toISOString()),
        'assignment_group_id': value['assignmentGroupId'],
        'allowed_extensions': value['allowedExtensions'],
        'turnitin_enabled': value['turnitinEnabled'],
        'vericite_enabled': value['vericiteEnabled'],
        'turnitin_settings': TurnitinSettingsToJSON(value['turnitinSettings']),
        'grade_group_students_individually': value['gradeGroupStudentsIndividually'],
        'external_tool_tag_attributes': ExternalToolTagAttributesToJSON(value['externalToolTagAttributes']),
        'peer_reviews': value['peerReviews'],
        'automatic_peer_reviews': value['automaticPeerReviews'],
        'peer_review_count': value['peerReviewCount'],
        'peer_reviews_assign_at': value['peerReviewsAssignAt'] == null ? undefined : ((value['peerReviewsAssignAt'] as any).toISOString()),
        'intra_group_peer_reviews': value['intraGroupPeerReviews'],
        'group_category_id': value['groupCategoryId'],
        'position': value['position'],
        'post_to_sis': value['postToSis'],
        'integration_id': value['integrationId'],
        'integration_data': value['integrationData'],
        'points_possible': value['pointsPossible'],
        'submission_types': value['submissionTypes'],
        'grading_type': value['gradingType'],
        'grading_standard_id': value['gradingStandardId'],
        'published': value['published'],
        'only_visible_to_overrides': value['onlyVisibleToOverrides'],
        'lock_info': LockInfoToJSON(value['lockInfo']),
        'freeze_on_copy': value['freezeOnCopy'],
        'use_rubric_for_grading': value['useRubricForGrading'],
        'rubric_settings': AssignmentRubricSettingsToJSON(value['rubricSettings']),
        'rubric': value['rubric'] == null ? undefined : ((value['rubric'] as Array<any>).map(RubricCriteriaToJSON)),
        'omit_from_final_grade': value['omitFromFinalGrade'],
        'hide_in_gradebook': value['hideInGradebook'],
        'moderated_grading': value['moderatedGrading'],
        'grader_count': value['graderCount'],
        'final_grader_id': value['finalGraderId'],
        'grader_comments_visible_to_graders': value['graderCommentsVisibleToGraders'],
        'graders_anonymous_to_graders': value['gradersAnonymousToGraders'],
        'grader_names_visible_to_final_grader': value['graderNamesVisibleToFinalGrader'],
        'anonymous_grading': value['anonymousGrading'],
        'allowed_attempts': value['allowedAttempts'],
        'post_manually': value['postManually'],
        'score_statistics': ScoreStatisticToJSON(value['scoreStatistics']),
        'annotatable_attachment_id': value['annotatableAttachmentId'],
        'anonymize_students': value['anonymizeStudents'],
        'require_lockdown_browser': value['requireLockdownBrowser'],
        'muted': value['muted'],
        'anonymous_peer_reviews': value['anonymousPeerReviews'],
        'anonymous_instructor_annotations': value['anonymousInstructorAnnotations'],
    };
}

