/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * (Optional) Basic rubric attributes (if rubric exists).
 * @export
 * @interface AssignmentRubricSettings
 */
export interface AssignmentRubricSettings {
    /**
     * 
     * @type {number}
     * @memberof AssignmentRubricSettings
     */
    pointsPossible?: number;
}

/**
 * Check if a given object implements the AssignmentRubricSettings interface.
 */
export function instanceOfAssignmentRubricSettings(value: object): value is AssignmentRubricSettings {
    return true;
}

export function AssignmentRubricSettingsFromJSON(json: any): AssignmentRubricSettings {
    return AssignmentRubricSettingsFromJSONTyped(json, false);
}

export function AssignmentRubricSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentRubricSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'pointsPossible': json['points_possible'] == null ? undefined : json['points_possible'],
    };
}

export function AssignmentRubricSettingsToJSON(json: any): AssignmentRubricSettings {
    return AssignmentRubricSettingsToJSONTyped(json, false);
}

export function AssignmentRubricSettingsToJSONTyped(value?: AssignmentRubricSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'points_possible': value['pointsPossible'],
    };
}

