/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvailableReportParametersValue } from './AvailableReportParametersValue';
import {
    AvailableReportParametersValueFromJSON,
    AvailableReportParametersValueFromJSONTyped,
    AvailableReportParametersValueToJSON,
    AvailableReportParametersValueToJSONTyped,
} from './AvailableReportParametersValue';

/**
 * 
 * @export
 * @interface AvailableReport
 */
export interface AvailableReport {
    /**
     * The name of the report.
     * @type {string}
     * @memberof AvailableReport
     */
    report?: string;
    /**
     * The human-readable title of the report.
     * @type {string}
     * @memberof AvailableReport
     */
    title?: string;
    /**
     * The parameters will vary for each report.
     * @type {{ [key: string]: AvailableReportParametersValue; }}
     * @memberof AvailableReport
     */
    parameters?: { [key: string]: AvailableReportParametersValue; } | null;
}

/**
 * Check if a given object implements the AvailableReport interface.
 */
export function instanceOfAvailableReport(value: object): value is AvailableReport {
    return true;
}

export function AvailableReportFromJSON(json: any): AvailableReport {
    return AvailableReportFromJSONTyped(json, false);
}

export function AvailableReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailableReport {
    if (json == null) {
        return json;
    }
    return {
        
        'report': json['report'] == null ? undefined : json['report'],
        'title': json['title'] == null ? undefined : json['title'],
        'parameters': json['parameters'] == null ? undefined : (mapValues(json['parameters'], AvailableReportParametersValueFromJSON)),
    };
}

export function AvailableReportToJSON(json: any): AvailableReport {
    return AvailableReportToJSONTyped(json, false);
}

export function AvailableReportToJSONTyped(value?: AvailableReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report': value['report'],
        'title': value['title'],
        'parameters': value['parameters'] == null ? undefined : (mapValues(value['parameters'], AvailableReportParametersValueToJSON)),
    };
}

