/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentShareSourceCourse
 */
export interface ContentShareSourceCourse {
    /**
     * 
     * @type {number}
     * @memberof ContentShareSourceCourse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ContentShareSourceCourse
     */
    name?: string;
}

/**
 * Check if a given object implements the ContentShareSourceCourse interface.
 */
export function instanceOfContentShareSourceCourse(value: object): value is ContentShareSourceCourse {
    return true;
}

export function ContentShareSourceCourseFromJSON(json: any): ContentShareSourceCourse {
    return ContentShareSourceCourseFromJSONTyped(json, false);
}

export function ContentShareSourceCourseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentShareSourceCourse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ContentShareSourceCourseToJSON(json: any): ContentShareSourceCourse {
    return ContentShareSourceCourseToJSONTyped(json, false);
}

export function ContentShareSourceCourseToJSONTyped(value?: ContentShareSourceCourse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

