/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Shared contexts between current user and participants.
 * @export
 * @interface ConversationAudienceContexts
 */
export interface ConversationAudienceContexts {
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ConversationAudienceContexts
     */
    courses?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ConversationAudienceContexts
     */
    groups?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the ConversationAudienceContexts interface.
 */
export function instanceOfConversationAudienceContexts(value: object): value is ConversationAudienceContexts {
    return true;
}

export function ConversationAudienceContextsFromJSON(json: any): ConversationAudienceContexts {
    return ConversationAudienceContextsFromJSONTyped(json, false);
}

export function ConversationAudienceContextsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationAudienceContexts {
    if (json == null) {
        return json;
    }
    return {
        
        'courses': json['courses'] == null ? undefined : json['courses'],
        'groups': json['groups'] == null ? undefined : json['groups'],
    };
}

export function ConversationAudienceContextsToJSON(json: any): ConversationAudienceContexts {
    return ConversationAudienceContextsToJSONTyped(json, false);
}

export function ConversationAudienceContextsToJSONTyped(value?: ConversationAudienceContexts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courses': value['courses'],
        'groups': value['groups'],
    };
}

