/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Attributes for the GroupCategory.
 * @export
 * @interface CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory
 */
export interface CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory {
    /**
     * 
     * @type {number}
     * @memberof CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory
     */
    name?: string;
}

/**
 * Check if a given object implements the CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory interface.
 */
export function instanceOfCoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory(value: object): value is CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory {
    return true;
}

export function CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategoryFromJSON(json: any): CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory {
    return CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategoryFromJSONTyped(json, false);
}

export function CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategoryToJSON(json: any): CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory {
    return CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategoryToJSONTyped(json, false);
}

export function CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategoryToJSONTyped(value?: CoursesCourseIdGroupCategoriesBulkManageDifferentiationTagPostRequestGroupCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

