/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeveloperKeyInputDeveloperKey } from './DeveloperKeyInputDeveloperKey';
import {
    DeveloperKeyInputDeveloperKeyFromJSON,
    DeveloperKeyInputDeveloperKeyFromJSONTyped,
    DeveloperKeyInputDeveloperKeyToJSON,
    DeveloperKeyInputDeveloperKeyToJSONTyped,
} from './DeveloperKeyInputDeveloperKey';

/**
 * 
 * @export
 * @interface DeveloperKeyInput
 */
export interface DeveloperKeyInput {
    /**
     * 
     * @type {DeveloperKeyInputDeveloperKey}
     * @memberof DeveloperKeyInput
     */
    developerKey: DeveloperKeyInputDeveloperKey;
}

/**
 * Check if a given object implements the DeveloperKeyInput interface.
 */
export function instanceOfDeveloperKeyInput(value: object): value is DeveloperKeyInput {
    if (!('developerKey' in value) || value['developerKey'] === undefined) return false;
    return true;
}

export function DeveloperKeyInputFromJSON(json: any): DeveloperKeyInput {
    return DeveloperKeyInputFromJSONTyped(json, false);
}

export function DeveloperKeyInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeveloperKeyInput {
    if (json == null) {
        return json;
    }
    return {
        
        'developerKey': DeveloperKeyInputDeveloperKeyFromJSON(json['developer_key']),
    };
}

export function DeveloperKeyInputToJSON(json: any): DeveloperKeyInput {
    return DeveloperKeyInputToJSONTyped(json, false);
}

export function DeveloperKeyInputToJSONTyped(value?: DeveloperKeyInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'developer_key': DeveloperKeyInputDeveloperKeyToJSON(value['developerKey']),
    };
}

