/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EditAssignmentRequestAssignment } from './EditAssignmentRequestAssignment';
import {
    EditAssignmentRequestAssignmentFromJSON,
    EditAssignmentRequestAssignmentFromJSONTyped,
    EditAssignmentRequestAssignmentToJSON,
    EditAssignmentRequestAssignmentToJSONTyped,
} from './EditAssignmentRequestAssignment';

/**
 * 
 * @export
 * @interface EditAssignmentRequest
 */
export interface EditAssignmentRequest {
    /**
     * 
     * @type {EditAssignmentRequestAssignment}
     * @memberof EditAssignmentRequest
     */
    assignment?: EditAssignmentRequestAssignment;
}

/**
 * Check if a given object implements the EditAssignmentRequest interface.
 */
export function instanceOfEditAssignmentRequest(value: object): value is EditAssignmentRequest {
    return true;
}

export function EditAssignmentRequestFromJSON(json: any): EditAssignmentRequest {
    return EditAssignmentRequestFromJSONTyped(json, false);
}

export function EditAssignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditAssignmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assignment': json['assignment'] == null ? undefined : EditAssignmentRequestAssignmentFromJSON(json['assignment']),
    };
}

export function EditAssignmentRequestToJSON(json: any): EditAssignmentRequest {
    return EditAssignmentRequestToJSONTyped(json, false);
}

export function EditAssignmentRequestToJSONTyped(value?: EditAssignmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignment': EditAssignmentRequestAssignmentToJSON(value['assignment']),
    };
}

