/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnrollmentTerm } from './EnrollmentTerm';
import {
    EnrollmentTermFromJSON,
    EnrollmentTermFromJSONTyped,
    EnrollmentTermToJSON,
    EnrollmentTermToJSONTyped,
} from './EnrollmentTerm';

/**
 * 
 * @export
 * @interface EnrollmentTermsList
 */
export interface EnrollmentTermsList {
    /**
     * 
     * @type {Array<EnrollmentTerm>}
     * @memberof EnrollmentTermsList
     */
    enrollmentTerms?: Array<EnrollmentTerm>;
}

/**
 * Check if a given object implements the EnrollmentTermsList interface.
 */
export function instanceOfEnrollmentTermsList(value: object): value is EnrollmentTermsList {
    return true;
}

export function EnrollmentTermsListFromJSON(json: any): EnrollmentTermsList {
    return EnrollmentTermsListFromJSONTyped(json, false);
}

export function EnrollmentTermsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollmentTermsList {
    if (json == null) {
        return json;
    }
    return {
        
        'enrollmentTerms': json['enrollment_terms'] == null ? undefined : ((json['enrollment_terms'] as Array<any>).map(EnrollmentTermFromJSON)),
    };
}

export function EnrollmentTermsListToJSON(json: any): EnrollmentTermsList {
    return EnrollmentTermsListToJSONTyped(json, false);
}

export function EnrollmentTermsListToJSONTyped(value?: EnrollmentTermsList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enrollment_terms': value['enrollmentTerms'] == null ? undefined : ((value['enrollmentTerms'] as Array<any>).map(EnrollmentTermToJSON)),
    };
}

