/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnrollmentTermOverridesValue
 */
export interface EnrollmentTermOverridesValue {
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentTermOverridesValue
     */
    startAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EnrollmentTermOverridesValue
     */
    endAt?: Date;
}

/**
 * Check if a given object implements the EnrollmentTermOverridesValue interface.
 */
export function instanceOfEnrollmentTermOverridesValue(value: object): value is EnrollmentTermOverridesValue {
    return true;
}

export function EnrollmentTermOverridesValueFromJSON(json: any): EnrollmentTermOverridesValue {
    return EnrollmentTermOverridesValueFromJSONTyped(json, false);
}

export function EnrollmentTermOverridesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollmentTermOverridesValue {
    if (json == null) {
        return json;
    }
    return {
        
        'startAt': json['start_at'] == null ? undefined : (new Date(json['start_at'])),
        'endAt': json['end_at'] == null ? undefined : (new Date(json['end_at'])),
    };
}

export function EnrollmentTermOverridesValueToJSON(json: any): EnrollmentTermOverridesValue {
    return EnrollmentTermOverridesValueToJSONTyped(json, false);
}

export function EnrollmentTermOverridesValueToJSONTyped(value?: EnrollmentTermOverridesValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start_at': value['startAt'] == null ? undefined : ((value['startAt']).toISOString()),
        'end_at': value['endAt'] == null ? undefined : ((value['endAt']).toISOString()),
    };
}

