/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Error1
 */
export interface Error1 {
    /**
     * Error message explaining what went wrong
     * @type {string}
     * @memberof Error1
     */
    message?: string;
}

/**
 * Check if a given object implements the Error1 interface.
 */
export function instanceOfError1(value: object): value is Error1 {
    return true;
}

export function Error1FromJSON(json: any): Error1 {
    return Error1FromJSONTyped(json, false);
}

export function Error1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error1 {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function Error1ToJSON(json: any): Error1 {
    return Error1ToJSONTyped(json, false);
}

export function Error1ToJSONTyped(value?: Error1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

