/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Error2
 */
export interface Error2 {
    /**
     * 
     * @type {string}
     * @memberof Error2
     */
    error?: string;
}

/**
 * Check if a given object implements the Error2 interface.
 */
export function instanceOfError2(value: object): value is Error2 {
    return true;
}

export function Error2FromJSON(json: any): Error2 {
    return Error2FromJSONTyped(json, false);
}

export function Error2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error2 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Error2ToJSON(json: any): Error2 {
    return Error2ToJSONTyped(json, false);
}

export function Error2ToJSONTyped(value?: Error2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

