/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FederatedAttributeConfig } from './FederatedAttributeConfig';
import {
    instanceOfFederatedAttributeConfig,
    FederatedAttributeConfigFromJSON,
    FederatedAttributeConfigFromJSONTyped,
    FederatedAttributeConfigToJSON,
} from './FederatedAttributeConfig';

/**
 * @type FederatedAttributesConfigValue
 * 
 * @export
 */
export type FederatedAttributesConfigValue = FederatedAttributeConfig | string;

export function FederatedAttributesConfigValueFromJSON(json: any): FederatedAttributesConfigValue {
    return FederatedAttributesConfigValueFromJSONTyped(json, false);
}

export function FederatedAttributesConfigValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FederatedAttributesConfigValue {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfFederatedAttributeConfig(json)) {
        return FederatedAttributeConfigFromJSONTyped(json, true);
    }

    return {} as any;
}

export function FederatedAttributesConfigValueToJSON(json: any): any {
    return FederatedAttributesConfigValueToJSONTyped(json, false);
}

export function FederatedAttributesConfigValueToJSONTyped(value?: FederatedAttributesConfigValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfFederatedAttributeConfig(value)) {
        return FederatedAttributeConfigToJSON(value as FederatedAttributeConfig);
    }

    return {};
}

