/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GradingRules
 */
export interface GradingRules {
    /**
     * Number of lowest scores to be dropped for each user.
     * @type {number}
     * @memberof GradingRules
     */
    dropLowest: number;
    /**
     * Number of highest scores to be dropped for each user.
     * @type {number}
     * @memberof GradingRules
     */
    dropHighest: number;
    /**
     * Assignment IDs that should never be dropped.
     * @type {Array<number>}
     * @memberof GradingRules
     */
    neverDrop: Array<number>;
}

/**
 * Check if a given object implements the GradingRules interface.
 */
export function instanceOfGradingRules(value: object): value is GradingRules {
    if (!('dropLowest' in value) || value['dropLowest'] === undefined) return false;
    if (!('dropHighest' in value) || value['dropHighest'] === undefined) return false;
    if (!('neverDrop' in value) || value['neverDrop'] === undefined) return false;
    return true;
}

export function GradingRulesFromJSON(json: any): GradingRules {
    return GradingRulesFromJSONTyped(json, false);
}

export function GradingRulesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GradingRules {
    if (json == null) {
        return json;
    }
    return {
        
        'dropLowest': json['drop_lowest'],
        'dropHighest': json['drop_highest'],
        'neverDrop': json['never_drop'],
    };
}

export function GradingRulesToJSON(json: any): GradingRules {
    return GradingRulesToJSONTyped(json, false);
}

export function GradingRulesToJSONTyped(value?: GradingRules | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'drop_lowest': value['dropLowest'],
        'drop_highest': value['dropHighest'],
        'never_drop': value['neverDrop'],
    };
}

