/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Progress1 } from './Progress1';
import {
    instanceOfProgress1,
    Progress1FromJSON,
    Progress1FromJSONTyped,
    Progress1ToJSON,
} from './Progress1';

/**
 * @type GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200Response
 * 
 * @export
 */
export type GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200Response = Array<object> | Progress1;

export function GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200ResponseFromJSON(json: any): GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200Response {
    return GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200ResponseFromJSONTyped(json, false);
}

export function GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfProgress1(json)) {
        return Progress1FromJSONTyped(json, true);
    }

    return {} as any;
}

export function GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200ResponseToJSON(json: any): any {
    return GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200ResponseToJSONTyped(json, false);
}

export function GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200ResponseToJSONTyped(value?: GroupCategoriesGroupCategoryIdAssignUnassignedMembersPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfProgress1(value)) {
        return Progress1ToJSON(value as Progress1);
    }

    return {};
}

