/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about why an assignment might be locked for a user.
 * @export
 * @interface LockInfo
 */
export interface LockInfo {
    /**
     * Asset string for the object causing the lock (e.g., "assignment_4").
     * @type {string}
     * @memberof LockInfo
     */
    assetString: string;
    /**
     * (Optional) Time at which this was/will be unlocked by date.
     * @type {Date}
     * @memberof LockInfo
     */
    unlockAt?: Date | null;
    /**
     * (Optional) Time at which this was/will be locked by date.
     * @type {Date}
     * @memberof LockInfo
     */
    lockAt?: Date | null;
    /**
     * (Optional) Context module causing the lock via prerequisites or availability dates.
     * @type {object}
     * @memberof LockInfo
     */
    contextModule?: object | null;
    /**
     * If the assignment was manually locked by an instructor (module item).
     * @type {boolean}
     * @memberof LockInfo
     */
    manuallyLocked: boolean;
}

/**
 * Check if a given object implements the LockInfo interface.
 */
export function instanceOfLockInfo(value: object): value is LockInfo {
    if (!('assetString' in value) || value['assetString'] === undefined) return false;
    if (!('manuallyLocked' in value) || value['manuallyLocked'] === undefined) return false;
    return true;
}

export function LockInfoFromJSON(json: any): LockInfo {
    return LockInfoFromJSONTyped(json, false);
}

export function LockInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'assetString': json['asset_string'],
        'unlockAt': json['unlock_at'] == null ? undefined : (new Date(json['unlock_at'])),
        'lockAt': json['lock_at'] == null ? undefined : (new Date(json['lock_at'])),
        'contextModule': json['context_module'] == null ? undefined : json['context_module'],
        'manuallyLocked': json['manually_locked'],
    };
}

export function LockInfoToJSON(json: any): LockInfo {
    return LockInfoToJSONTyped(json, false);
}

export function LockInfoToJSONTyped(value?: LockInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asset_string': value['assetString'],
        'unlock_at': value['unlockAt'] == null ? undefined : ((value['unlockAt'] as any).toISOString()),
        'lock_at': value['lockAt'] == null ? undefined : ((value['lockAt'] as any).toISOString()),
        'context_module': value['contextModule'],
        'manually_locked': value['manuallyLocked'],
    };
}

