/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Page
 */
export interface Page {
    /**
     * The ID of the page
     * @type {number}
     * @memberof Page
     */
    pageId?: number;
    /**
     * The unique locator for the page
     * @type {string}
     * @memberof Page
     */
    url?: string;
    /**
     * The title of the page
     * @type {string}
     * @memberof Page
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof Page
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Page
     */
    updatedAt?: Date;
    /**
     * Deprecated; inverse of published
     * @type {boolean}
     * @memberof Page
     */
    hideFromStudents?: boolean;
    /**
     * Roles allowed to edit the page
     * @type {string}
     * @memberof Page
     */
    editingRoles?: string;
    /**
     * 
     * @type {object}
     * @memberof Page
     */
    lastEditedBy?: object | null;
    /**
     * The page content in HTML
     * @type {string}
     * @memberof Page
     */
    body?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Page
     */
    published?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Page
     */
    publishAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Page
     */
    frontPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Page
     */
    lockedForUser?: boolean;
    /**
     * 
     * @type {object}
     * @memberof Page
     */
    lockInfo?: object | null;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    lockExplanation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Page
     */
    editor?: PageEditorEnum;
    /**
     * 
     * @type {object}
     * @memberof Page
     */
    blockEditorAttributes?: object | null;
}


/**
 * @export
 */
export const PageEditorEnum = {
    Rce: 'rce',
    BlockEditor: 'block_editor'
} as const;
export type PageEditorEnum = typeof PageEditorEnum[keyof typeof PageEditorEnum];


/**
 * Check if a given object implements the Page interface.
 */
export function instanceOfPage(value: object): value is Page {
    return true;
}

export function PageFromJSON(json: any): Page {
    return PageFromJSONTyped(json, false);
}

export function PageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Page {
    if (json == null) {
        return json;
    }
    return {
        
        'pageId': json['page_id'] == null ? undefined : json['page_id'],
        'url': json['url'] == null ? undefined : json['url'],
        'title': json['title'] == null ? undefined : json['title'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'hideFromStudents': json['hide_from_students'] == null ? undefined : json['hide_from_students'],
        'editingRoles': json['editing_roles'] == null ? undefined : json['editing_roles'],
        'lastEditedBy': json['last_edited_by'] == null ? undefined : json['last_edited_by'],
        'body': json['body'] == null ? undefined : json['body'],
        'published': json['published'] == null ? undefined : json['published'],
        'publishAt': json['publish_at'] == null ? undefined : (new Date(json['publish_at'])),
        'frontPage': json['front_page'] == null ? undefined : json['front_page'],
        'lockedForUser': json['locked_for_user'] == null ? undefined : json['locked_for_user'],
        'lockInfo': json['lock_info'] == null ? undefined : json['lock_info'],
        'lockExplanation': json['lock_explanation'] == null ? undefined : json['lock_explanation'],
        'editor': json['editor'] == null ? undefined : json['editor'],
        'blockEditorAttributes': json['block_editor_attributes'] == null ? undefined : json['block_editor_attributes'],
    };
}

export function PageToJSON(json: any): Page {
    return PageToJSONTyped(json, false);
}

export function PageToJSONTyped(value?: Page | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page_id': value['pageId'],
        'url': value['url'],
        'title': value['title'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'hide_from_students': value['hideFromStudents'],
        'editing_roles': value['editingRoles'],
        'last_edited_by': value['lastEditedBy'],
        'body': value['body'],
        'published': value['published'],
        'publish_at': value['publishAt'] == null ? undefined : ((value['publishAt']).toISOString()),
        'front_page': value['frontPage'],
        'locked_for_user': value['lockedForUser'],
        'lock_info': value['lockInfo'],
        'lock_explanation': value['lockExplanation'],
        'editor': value['editor'],
        'block_editor_attributes': value['blockEditorAttributes'],
    };
}

