/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuizSettingsFilters } from './QuizSettingsFilters';
import {
    QuizSettingsFiltersFromJSON,
    QuizSettingsFiltersFromJSONTyped,
    QuizSettingsFiltersToJSON,
    QuizSettingsFiltersToJSONTyped,
} from './QuizSettingsFilters';
import type { MultipleAttemptsSettings } from './MultipleAttemptsSettings';
import {
    MultipleAttemptsSettingsFromJSON,
    MultipleAttemptsSettingsFromJSONTyped,
    MultipleAttemptsSettingsToJSON,
    MultipleAttemptsSettingsToJSONTyped,
} from './MultipleAttemptsSettings';
import type { ResultViewSettings } from './ResultViewSettings';
import {
    ResultViewSettingsFromJSON,
    ResultViewSettingsFromJSONTyped,
    ResultViewSettingsToJSON,
    ResultViewSettingsToJSONTyped,
} from './ResultViewSettings';

/**
 * 
 * @export
 * @interface QuizSettings
 */
export interface QuizSettings {
    /**
     * 
     * @type {string}
     * @memberof QuizSettings
     */
    calculatorType?: QuizSettingsCalculatorTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof QuizSettings
     */
    filterIpAddress?: boolean;
    /**
     * 
     * @type {QuizSettingsFilters}
     * @memberof QuizSettings
     */
    filters?: QuizSettingsFilters;
    /**
     * 
     * @type {string}
     * @memberof QuizSettings
     */
    oneAtATimeType?: QuizSettingsOneAtATimeTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof QuizSettings
     */
    allowBacktracking?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof QuizSettings
     */
    shuffleAnswers?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof QuizSettings
     */
    shuffleQuestions?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof QuizSettings
     */
    requireStudentAccessCode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof QuizSettings
     */
    studentAccessCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof QuizSettings
     */
    hasTimeLimit?: boolean;
    /**
     * 
     * @type {number}
     * @memberof QuizSettings
     */
    sessionTimeLimitInSeconds?: number;
    /**
     * 
     * @type {MultipleAttemptsSettings}
     * @memberof QuizSettings
     */
    multipleAttempts?: MultipleAttemptsSettings;
    /**
     * 
     * @type {ResultViewSettings}
     * @memberof QuizSettings
     */
    resultViewSettings?: ResultViewSettings;
}


/**
 * @export
 */
export const QuizSettingsCalculatorTypeEnum = {
    None: 'none',
    Basic: 'basic',
    Scientific: 'scientific'
} as const;
export type QuizSettingsCalculatorTypeEnum = typeof QuizSettingsCalculatorTypeEnum[keyof typeof QuizSettingsCalculatorTypeEnum];

/**
 * @export
 */
export const QuizSettingsOneAtATimeTypeEnum = {
    None: 'none',
    Question: 'question'
} as const;
export type QuizSettingsOneAtATimeTypeEnum = typeof QuizSettingsOneAtATimeTypeEnum[keyof typeof QuizSettingsOneAtATimeTypeEnum];


/**
 * Check if a given object implements the QuizSettings interface.
 */
export function instanceOfQuizSettings(value: object): value is QuizSettings {
    return true;
}

export function QuizSettingsFromJSON(json: any): QuizSettings {
    return QuizSettingsFromJSONTyped(json, false);
}

export function QuizSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'calculatorType': json['calculator_type'] == null ? undefined : json['calculator_type'],
        'filterIpAddress': json['filter_ip_address'] == null ? undefined : json['filter_ip_address'],
        'filters': json['filters'] == null ? undefined : QuizSettingsFiltersFromJSON(json['filters']),
        'oneAtATimeType': json['one_at_a_time_type'] == null ? undefined : json['one_at_a_time_type'],
        'allowBacktracking': json['allow_backtracking'] == null ? undefined : json['allow_backtracking'],
        'shuffleAnswers': json['shuffle_answers'] == null ? undefined : json['shuffle_answers'],
        'shuffleQuestions': json['shuffle_questions'] == null ? undefined : json['shuffle_questions'],
        'requireStudentAccessCode': json['require_student_access_code'] == null ? undefined : json['require_student_access_code'],
        'studentAccessCode': json['student_access_code'] == null ? undefined : json['student_access_code'],
        'hasTimeLimit': json['has_time_limit'] == null ? undefined : json['has_time_limit'],
        'sessionTimeLimitInSeconds': json['session_time_limit_in_seconds'] == null ? undefined : json['session_time_limit_in_seconds'],
        'multipleAttempts': json['multiple_attempts'] == null ? undefined : MultipleAttemptsSettingsFromJSON(json['multiple_attempts']),
        'resultViewSettings': json['result_view_settings'] == null ? undefined : ResultViewSettingsFromJSON(json['result_view_settings']),
    };
}

export function QuizSettingsToJSON(json: any): QuizSettings {
    return QuizSettingsToJSONTyped(json, false);
}

export function QuizSettingsToJSONTyped(value?: QuizSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'calculator_type': value['calculatorType'],
        'filter_ip_address': value['filterIpAddress'],
        'filters': QuizSettingsFiltersToJSON(value['filters']),
        'one_at_a_time_type': value['oneAtATimeType'],
        'allow_backtracking': value['allowBacktracking'],
        'shuffle_answers': value['shuffleAnswers'],
        'shuffle_questions': value['shuffleQuestions'],
        'require_student_access_code': value['requireStudentAccessCode'],
        'student_access_code': value['studentAccessCode'],
        'has_time_limit': value['hasTimeLimit'],
        'session_time_limit_in_seconds': value['sessionTimeLimitInSeconds'],
        'multiple_attempts': MultipleAttemptsSettingsToJSON(value['multipleAttempts']),
        'result_view_settings': ResultViewSettingsToJSON(value['resultViewSettings']),
    };
}

