/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuizSubmissionQuestionAnswer } from './QuizSubmissionQuestionAnswer';
import {
    QuizSubmissionQuestionAnswerFromJSON,
    QuizSubmissionQuestionAnswerFromJSONTyped,
    QuizSubmissionQuestionAnswerToJSON,
    QuizSubmissionQuestionAnswerToJSONTyped,
} from './QuizSubmissionQuestionAnswer';
import type { QuizSubmissionQuestionAnswers } from './QuizSubmissionQuestionAnswers';
import {
    QuizSubmissionQuestionAnswersFromJSON,
    QuizSubmissionQuestionAnswersFromJSONTyped,
    QuizSubmissionQuestionAnswersToJSON,
    QuizSubmissionQuestionAnswersToJSONTyped,
} from './QuizSubmissionQuestionAnswers';

/**
 * 
 * @export
 * @interface QuizSubmissionQuestion
 */
export interface QuizSubmissionQuestion {
    /**
     * The ID of the QuizQuestion this answer is for.
     * @type {number}
     * @memberof QuizSubmissionQuestion
     */
    id?: number;
    /**
     * Whether this question is flagged.
     * @type {boolean}
     * @memberof QuizSubmissionQuestion
     */
    flagged?: boolean;
    /**
     * 
     * @type {QuizSubmissionQuestionAnswer}
     * @memberof QuizSubmissionQuestion
     */
    answer?: QuizSubmissionQuestionAnswer | null;
    /**
     * 
     * @type {QuizSubmissionQuestionAnswers}
     * @memberof QuizSubmissionQuestion
     */
    answers?: QuizSubmissionQuestionAnswers | null;
}

/**
 * Check if a given object implements the QuizSubmissionQuestion interface.
 */
export function instanceOfQuizSubmissionQuestion(value: object): value is QuizSubmissionQuestion {
    return true;
}

export function QuizSubmissionQuestionFromJSON(json: any): QuizSubmissionQuestion {
    return QuizSubmissionQuestionFromJSONTyped(json, false);
}

export function QuizSubmissionQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizSubmissionQuestion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'flagged': json['flagged'] == null ? undefined : json['flagged'],
        'answer': json['answer'] == null ? undefined : QuizSubmissionQuestionAnswerFromJSON(json['answer']),
        'answers': json['answers'] == null ? undefined : QuizSubmissionQuestionAnswersFromJSON(json['answers']),
    };
}

export function QuizSubmissionQuestionToJSON(json: any): QuizSubmissionQuestion {
    return QuizSubmissionQuestionToJSONTyped(json, false);
}

export function QuizSubmissionQuestionToJSONTyped(value?: QuizSubmissionQuestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'flagged': value['flagged'],
        'answer': QuizSubmissionQuestionAnswerToJSON(value['answer']),
        'answers': QuizSubmissionQuestionAnswersToJSON(value['answers']),
    };
}

