/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type QuizSubmissionQuestionAnswer
 * The provided answer (if any) for this question. The format of this parameter depends on the type of the question.
 * 
 * @export
 */
export type QuizSubmissionQuestionAnswer = Array<string> | number | object | string;

export function QuizSubmissionQuestionAnswerFromJSON(json: any): QuizSubmissionQuestionAnswer {
    return QuizSubmissionQuestionAnswerFromJSONTyped(json, false);
}

export function QuizSubmissionQuestionAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizSubmissionQuestionAnswer {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function QuizSubmissionQuestionAnswerToJSON(json: any): any {
    return QuizSubmissionQuestionAnswerToJSONTyped(json, false);
}

export function QuizSubmissionQuestionAnswerToJSONTyped(value?: QuizSubmissionQuestionAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

