/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RubricRating } from './RubricRating';
import {
    RubricRatingFromJSON,
    RubricRatingFromJSONTyped,
    RubricRatingToJSON,
    RubricRatingToJSONTyped,
} from './RubricRating';

/**
 * Represents a criterion in an assignment rubric.
 * @export
 * @interface RubricCriteria
 */
export interface RubricCriteria {
    /**
     * Points possible for this criterion.
     * @type {number}
     * @memberof RubricCriteria
     */
    points: number;
    /**
     * The ID of the rubric criterion.
     * @type {string}
     * @memberof RubricCriteria
     */
    id: string;
    /**
     * (Optional) The ID of the learning outcome this criterion uses, if any.
     * @type {string}
     * @memberof RubricCriteria
     */
    learningOutcomeId?: string | null;
    /**
     * (Optional) The 3rd party vendor's GUID for the outcome this criteria references, if any.
     * @type {string}
     * @memberof RubricCriteria
     */
    vendorGuid?: string | null;
    /**
     * The description of the criterion.
     * @type {string}
     * @memberof RubricCriteria
     */
    description: string;
    /**
     * More detailed description of the criterion.
     * @type {string}
     * @memberof RubricCriteria
     */
    longDescription?: string | null;
    /**
     * Whether the criterion uses a point range.
     * @type {boolean}
     * @memberof RubricCriteria
     */
    criterionUseRange: boolean;
    /**
     * List of rating levels for the criterion.
     * @type {Array<RubricRating>}
     * @memberof RubricCriteria
     */
    ratings?: Array<RubricRating> | null;
    /**
     * Whether this criterion should be ignored when calculating the score.
     * @type {boolean}
     * @memberof RubricCriteria
     */
    ignoreForScoring: boolean;
}

/**
 * Check if a given object implements the RubricCriteria interface.
 */
export function instanceOfRubricCriteria(value: object): value is RubricCriteria {
    if (!('points' in value) || value['points'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('criterionUseRange' in value) || value['criterionUseRange'] === undefined) return false;
    if (!('ignoreForScoring' in value) || value['ignoreForScoring'] === undefined) return false;
    return true;
}

export function RubricCriteriaFromJSON(json: any): RubricCriteria {
    return RubricCriteriaFromJSONTyped(json, false);
}

export function RubricCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RubricCriteria {
    if (json == null) {
        return json;
    }
    return {
        
        'points': json['points'],
        'id': json['id'],
        'learningOutcomeId': json['learning_outcome_id'] == null ? undefined : json['learning_outcome_id'],
        'vendorGuid': json['vendor_guid'] == null ? undefined : json['vendor_guid'],
        'description': json['description'],
        'longDescription': json['long_description'] == null ? undefined : json['long_description'],
        'criterionUseRange': json['criterion_use_range'],
        'ratings': json['ratings'] == null ? undefined : ((json['ratings'] as Array<any>).map(RubricRatingFromJSON)),
        'ignoreForScoring': json['ignore_for_scoring'],
    };
}

export function RubricCriteriaToJSON(json: any): RubricCriteria {
    return RubricCriteriaToJSONTyped(json, false);
}

export function RubricCriteriaToJSONTyped(value?: RubricCriteria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'points': value['points'],
        'id': value['id'],
        'learning_outcome_id': value['learningOutcomeId'],
        'vendor_guid': value['vendorGuid'],
        'description': value['description'],
        'long_description': value['longDescription'],
        'criterion_use_range': value['criterionUseRange'],
        'ratings': value['ratings'] == null ? undefined : ((value['ratings'] as Array<any>).map(RubricRatingToJSON)),
        'ignore_for_scoring': value['ignoreForScoring'],
    };
}

