/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
    /**
     * The ID of the matching object.
     * @type {number}
     * @memberof SearchResult
     */
    contentId?: number;
    /**
     * The type of the matching object.
     * @type {string}
     * @memberof SearchResult
     */
    contentType?: string;
    /**
     * The title of the matching object.
     * @type {string}
     * @memberof SearchResult
     */
    title?: string;
    /**
     * The body of the matching object.
     * @type {string}
     * @memberof SearchResult
     */
    body?: string;
    /**
     * The Canvas URL of the matching object.
     * @type {string}
     * @memberof SearchResult
     */
    htmlUrl?: string;
    /**
     * The distance between the search query and the result. Smaller numbers indicate closer matches.
     * @type {number}
     * @memberof SearchResult
     */
    distance?: number;
}

/**
 * Check if a given object implements the SearchResult interface.
 */
export function instanceOfSearchResult(value: object): value is SearchResult {
    return true;
}

export function SearchResultFromJSON(json: any): SearchResult {
    return SearchResultFromJSONTyped(json, false);
}

export function SearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'contentId': json['content_id'] == null ? undefined : json['content_id'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'title': json['title'] == null ? undefined : json['title'],
        'body': json['body'] == null ? undefined : json['body'],
        'htmlUrl': json['html_url'] == null ? undefined : json['html_url'],
        'distance': json['distance'] == null ? undefined : json['distance'],
    };
}

export function SearchResultToJSON(json: any): SearchResult {
    return SearchResultToJSONTyped(json, false);
}

export function SearchResultToJSONTyped(value?: SearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_id': value['contentId'],
        'content_type': value['contentType'],
        'title': value['title'],
        'body': value['body'],
        'html_url': value['htmlUrl'],
        'distance': value['distance'],
    };
}

