/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * 
 * @export
 * @interface Submission
 */
export interface Submission {
    /**
     * 
     * @type {number}
     * @memberof Submission
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Submission
     */
    studentEnteredScore?: number;
}

/**
 * Check if a given object implements the Submission interface.
 */
export function instanceOfSubmission(value: object): value is Submission {
    return true;
}

export function SubmissionFromJSON(json: any): Submission {
    return SubmissionFromJSONTyped(json, false);
}

export function SubmissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Submission {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'studentEnteredScore': json['student_entered_score'] == null ? undefined : json['student_entered_score'],
    };
}

export function SubmissionToJSON(json: any): Submission {
    return SubmissionToJSONTyped(json, false);
}

export function SubmissionToJSONTyped(value?: Submission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'student_entered_score': value['studentEnteredScore'],
    };
}

