/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Settings for Turnitin originality checking.
 * @export
 * @interface TurnitinSettings
 */
export interface TurnitinSettings {
    /**
     * 
     * @type {string}
     * @memberof TurnitinSettings
     */
    originalityReportVisibility?: TurnitinSettingsOriginalityReportVisibilityEnum;
    /**
     * Check against student paper repository.
     * @type {boolean}
     * @memberof TurnitinSettings
     */
    sPaperCheck?: boolean;
    /**
     * Check against internet sources.
     * @type {boolean}
     * @memberof TurnitinSettings
     */
    internetCheck?: boolean;
    /**
     * Check against journals, periodicals, publications.
     * @type {boolean}
     * @memberof TurnitinSettings
     */
    journalCheck?: boolean;
    /**
     * Exclude bibliographic materials.
     * @type {boolean}
     * @memberof TurnitinSettings
     */
    excludeBiblio?: boolean;
    /**
     * Exclude quoted materials.
     * @type {boolean}
     * @memberof TurnitinSettings
     */
    excludeQuoted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TurnitinSettings
     */
    excludeSmallMatchesType?: TurnitinSettingsExcludeSmallMatchesTypeEnum | null;
    /**
     * 
     * @type {number}
     * @memberof TurnitinSettings
     */
    excludeSmallMatchesValue?: number | null;
}


/**
 * @export
 */
export const TurnitinSettingsOriginalityReportVisibilityEnum = {
    Immediate: 'immediate',
    AfterGrading: 'after_grading',
    AfterDueDate: 'after_due_date',
    Never: 'never'
} as const;
export type TurnitinSettingsOriginalityReportVisibilityEnum = typeof TurnitinSettingsOriginalityReportVisibilityEnum[keyof typeof TurnitinSettingsOriginalityReportVisibilityEnum];

/**
 * @export
 */
export const TurnitinSettingsExcludeSmallMatchesTypeEnum = {
    Percent: 'percent',
    Words: 'words'
} as const;
export type TurnitinSettingsExcludeSmallMatchesTypeEnum = typeof TurnitinSettingsExcludeSmallMatchesTypeEnum[keyof typeof TurnitinSettingsExcludeSmallMatchesTypeEnum];


/**
 * Check if a given object implements the TurnitinSettings interface.
 */
export function instanceOfTurnitinSettings(value: object): value is TurnitinSettings {
    return true;
}

export function TurnitinSettingsFromJSON(json: any): TurnitinSettings {
    return TurnitinSettingsFromJSONTyped(json, false);
}

export function TurnitinSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TurnitinSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'originalityReportVisibility': json['originality_report_visibility'] == null ? undefined : json['originality_report_visibility'],
        'sPaperCheck': json['s_paper_check'] == null ? undefined : json['s_paper_check'],
        'internetCheck': json['internet_check'] == null ? undefined : json['internet_check'],
        'journalCheck': json['journal_check'] == null ? undefined : json['journal_check'],
        'excludeBiblio': json['exclude_biblio'] == null ? undefined : json['exclude_biblio'],
        'excludeQuoted': json['exclude_quoted'] == null ? undefined : json['exclude_quoted'],
        'excludeSmallMatchesType': json['exclude_small_matches_type'] == null ? undefined : json['exclude_small_matches_type'],
        'excludeSmallMatchesValue': json['exclude_small_matches_value'] == null ? undefined : json['exclude_small_matches_value'],
    };
}

export function TurnitinSettingsToJSON(json: any): TurnitinSettings {
    return TurnitinSettingsToJSONTyped(json, false);
}

export function TurnitinSettingsToJSONTyped(value?: TurnitinSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'originality_report_visibility': value['originalityReportVisibility'],
        's_paper_check': value['sPaperCheck'],
        'internet_check': value['internetCheck'],
        'journal_check': value['journalCheck'],
        'exclude_biblio': value['excludeBiblio'],
        'exclude_quoted': value['excludeQuoted'],
        'exclude_small_matches_type': value['excludeSmallMatchesType'],
        'exclude_small_matches_value': value['excludeSmallMatchesValue'],
    };
}

