/* tslint:disable */
/* eslint-disable */
/**
 * User Observees API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Optional result metadata
 * @export
 * @interface XAPIStatementResult
 */
export interface XAPIStatementResult {
    /**
     * ISO 8601 duration (e.g., “PT3M0S”), capped at 5 minutes
     * @type {string}
     * @memberof XAPIStatementResult
     */
    duration?: string;
}

/**
 * Check if a given object implements the XAPIStatementResult interface.
 */
export function instanceOfXAPIStatementResult(value: object): value is XAPIStatementResult {
    return true;
}

export function XAPIStatementResultFromJSON(json: any): XAPIStatementResult {
    return XAPIStatementResultFromJSONTyped(json, false);
}

export function XAPIStatementResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): XAPIStatementResult {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'] == null ? undefined : json['duration'],
    };
}

export function XAPIStatementResultToJSON(json: any): XAPIStatementResult {
    return XAPIStatementResultToJSONTyped(json, false);
}

export function XAPIStatementResultToJSONTyped(value?: XAPIStatementResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': value['duration'],
    };
}

