# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Answer(BaseModel):
    """
    Answer
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The unique identifier for the answer. Do not supply if this answer is part of a new question.")
    answer_text: Optional[StrictStr] = None
    answer_weight: Optional[StrictInt] = None
    answer_comments: Optional[StrictStr] = None
    text_after_answers: Optional[StrictStr] = None
    answer_match_left: Optional[StrictStr] = None
    answer_match_right: Optional[StrictStr] = None
    matching_answer_incorrect_matches: Optional[StrictStr] = None
    numerical_answer_type: Optional[StrictStr] = None
    exact: Optional[Union[StrictFloat, StrictInt]] = None
    margin: Optional[Union[StrictFloat, StrictInt]] = None
    approximate: Optional[Union[StrictFloat, StrictInt]] = None
    precision: Optional[StrictInt] = None
    start: Optional[Union[StrictFloat, StrictInt]] = None
    end: Optional[Union[StrictFloat, StrictInt]] = None
    blank_id: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["id", "answer_text", "answer_weight", "answer_comments", "text_after_answers", "answer_match_left", "answer_match_right", "matching_answer_incorrect_matches", "numerical_answer_type", "exact", "margin", "approximate", "precision", "start", "end", "blank_id"]

    @field_validator('numerical_answer_type')
    def numerical_answer_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['exact_answer', 'range_answer', 'precision_answer']):
            raise ValueError("must be one of enum values ('exact_answer', 'range_answer', 'precision_answer')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Answer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Answer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "answer_text": obj.get("answer_text"),
            "answer_weight": obj.get("answer_weight"),
            "answer_comments": obj.get("answer_comments"),
            "text_after_answers": obj.get("text_after_answers"),
            "answer_match_left": obj.get("answer_match_left"),
            "answer_match_right": obj.get("answer_match_right"),
            "matching_answer_incorrect_matches": obj.get("matching_answer_incorrect_matches"),
            "numerical_answer_type": obj.get("numerical_answer_type"),
            "exact": obj.get("exact"),
            "margin": obj.get("margin"),
            "approximate": obj.get("approximate"),
            "precision": obj.get("precision"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "blank_id": obj.get("blank_id")
        })
        return _obj


