# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ApiV1CoursesCourseIdQuizzesPostRequestQuiz(BaseModel):
    """
    ApiV1CoursesCourseIdQuizzesPostRequestQuiz
    """ # noqa: E501
    title: StrictStr = Field(description="The quiz title.")
    description: Optional[StrictStr] = Field(default=None, description="A description of the quiz.")
    quiz_type: Optional[StrictStr] = Field(default=None, description="The type of quiz.")
    assignment_group_id: Optional[StrictInt] = Field(default=None, description="The assignment group ID to put the assignment in.")
    time_limit: Optional[StrictInt] = Field(default=None, description="Time limit to take this quiz, in minutes.")
    shuffle_answers: Optional[StrictBool] = None
    hide_results: Optional[StrictStr] = None
    show_correct_answers: Optional[StrictBool] = None
    show_correct_answers_last_attempt: Optional[StrictBool] = None
    show_correct_answers_at: Optional[datetime] = None
    hide_correct_answers_at: Optional[datetime] = None
    allowed_attempts: Optional[StrictInt] = None
    scoring_policy: Optional[StrictStr] = None
    one_question_at_a_time: Optional[StrictBool] = None
    cant_go_back: Optional[StrictBool] = None
    access_code: Optional[StrictStr] = None
    ip_filter: Optional[StrictStr] = None
    due_at: Optional[datetime] = None
    lock_at: Optional[datetime] = None
    unlock_at: Optional[datetime] = None
    published: Optional[StrictBool] = None
    one_time_results: Optional[StrictBool] = None
    only_visible_to_overrides: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["title", "description", "quiz_type", "assignment_group_id", "time_limit", "shuffle_answers", "hide_results", "show_correct_answers", "show_correct_answers_last_attempt", "show_correct_answers_at", "hide_correct_answers_at", "allowed_attempts", "scoring_policy", "one_question_at_a_time", "cant_go_back", "access_code", "ip_filter", "due_at", "lock_at", "unlock_at", "published", "one_time_results", "only_visible_to_overrides"]

    @field_validator('quiz_type')
    def quiz_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['practice_quiz', 'assignment', 'graded_survey', 'survey']):
            raise ValueError("must be one of enum values ('practice_quiz', 'assignment', 'graded_survey', 'survey')")
        return value

    @field_validator('hide_results')
    def hide_results_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['always', 'until_after_last_attempt']):
            raise ValueError("must be one of enum values ('always', 'until_after_last_attempt')")
        return value

    @field_validator('scoring_policy')
    def scoring_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['keep_highest', 'keep_latest']):
            raise ValueError("must be one of enum values ('keep_highest', 'keep_latest')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiV1CoursesCourseIdQuizzesPostRequestQuiz from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiV1CoursesCourseIdQuizzesPostRequestQuiz from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "quiz_type": obj.get("quiz_type"),
            "assignment_group_id": obj.get("assignment_group_id"),
            "time_limit": obj.get("time_limit"),
            "shuffle_answers": obj.get("shuffle_answers"),
            "hide_results": obj.get("hide_results"),
            "show_correct_answers": obj.get("show_correct_answers"),
            "show_correct_answers_last_attempt": obj.get("show_correct_answers_last_attempt"),
            "show_correct_answers_at": obj.get("show_correct_answers_at"),
            "hide_correct_answers_at": obj.get("hide_correct_answers_at"),
            "allowed_attempts": obj.get("allowed_attempts"),
            "scoring_policy": obj.get("scoring_policy"),
            "one_question_at_a_time": obj.get("one_question_at_a_time"),
            "cant_go_back": obj.get("cant_go_back"),
            "access_code": obj.get("access_code"),
            "ip_filter": obj.get("ip_filter"),
            "due_at": obj.get("due_at"),
            "lock_at": obj.get("lock_at"),
            "unlock_at": obj.get("unlock_at"),
            "published": obj.get("published"),
            "one_time_results": obj.get("one_time_results"),
            "only_visible_to_overrides": obj.get("only_visible_to_overrides")
        })
        return _obj


