# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from canvas_lms_sdk.models.federated_attributes_config_value import FederatedAttributesConfigValue
from typing import Optional, Set
from typing_extensions import Self

class AuthenticationProvider(BaseModel):
    """
    AuthenticationProvider
    """ # noqa: E501
    id: Optional[StrictInt] = None
    auth_type: Optional[StrictStr] = None
    identifier_format: Optional[StrictStr] = None
    log_in_url: Optional[StrictStr] = None
    log_out_url: Optional[StrictStr] = None
    certificate_fingerprint: Optional[StrictStr] = None
    requested_authn_context: Optional[StrictStr] = None
    auth_host: Optional[StrictStr] = None
    auth_filter: Optional[StrictStr] = None
    auth_over_tls: Optional[StrictStr] = None
    auth_base: Optional[StrictStr] = None
    auth_username: Optional[StrictStr] = None
    auth_port: Optional[StrictInt] = None
    position: Optional[StrictInt] = None
    idp_entity_id: Optional[StrictStr] = None
    login_attribute: Optional[StrictStr] = None
    sig_alg: Optional[StrictStr] = None
    jit_provisioning: Optional[StrictBool] = None
    federated_attributes: Optional[Dict[str, FederatedAttributesConfigValue]] = None
    mfa_required: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "auth_type", "identifier_format", "log_in_url", "log_out_url", "certificate_fingerprint", "requested_authn_context", "auth_host", "auth_filter", "auth_over_tls", "auth_base", "auth_username", "auth_port", "position", "idp_entity_id", "login_attribute", "sig_alg", "jit_provisioning", "federated_attributes", "mfa_required"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthenticationProvider from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in federated_attributes (dict)
        _field_dict = {}
        if self.federated_attributes:
            for _key_federated_attributes in self.federated_attributes:
                if self.federated_attributes[_key_federated_attributes]:
                    _field_dict[_key_federated_attributes] = self.federated_attributes[_key_federated_attributes].to_dict()
            _dict['federated_attributes'] = _field_dict
        # set to None if requested_authn_context (nullable) is None
        # and model_fields_set contains the field
        if self.requested_authn_context is None and "requested_authn_context" in self.model_fields_set:
            _dict['requested_authn_context'] = None

        # set to None if auth_over_tls (nullable) is None
        # and model_fields_set contains the field
        if self.auth_over_tls is None and "auth_over_tls" in self.model_fields_set:
            _dict['auth_over_tls'] = None

        # set to None if auth_base (nullable) is None
        # and model_fields_set contains the field
        if self.auth_base is None and "auth_base" in self.model_fields_set:
            _dict['auth_base'] = None

        # set to None if auth_port (nullable) is None
        # and model_fields_set contains the field
        if self.auth_port is None and "auth_port" in self.model_fields_set:
            _dict['auth_port'] = None

        # set to None if jit_provisioning (nullable) is None
        # and model_fields_set contains the field
        if self.jit_provisioning is None and "jit_provisioning" in self.model_fields_set:
            _dict['jit_provisioning'] = None

        # set to None if mfa_required (nullable) is None
        # and model_fields_set contains the field
        if self.mfa_required is None and "mfa_required" in self.model_fields_set:
            _dict['mfa_required'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthenticationProvider from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "auth_type": obj.get("auth_type"),
            "identifier_format": obj.get("identifier_format"),
            "log_in_url": obj.get("log_in_url"),
            "log_out_url": obj.get("log_out_url"),
            "certificate_fingerprint": obj.get("certificate_fingerprint"),
            "requested_authn_context": obj.get("requested_authn_context"),
            "auth_host": obj.get("auth_host"),
            "auth_filter": obj.get("auth_filter"),
            "auth_over_tls": obj.get("auth_over_tls"),
            "auth_base": obj.get("auth_base"),
            "auth_username": obj.get("auth_username"),
            "auth_port": obj.get("auth_port"),
            "position": obj.get("position"),
            "idp_entity_id": obj.get("idp_entity_id"),
            "login_attribute": obj.get("login_attribute"),
            "sig_alg": obj.get("sig_alg"),
            "jit_provisioning": obj.get("jit_provisioning"),
            "federated_attributes": dict(
                (_k, FederatedAttributesConfigValue.from_dict(_v))
                for _k, _v in obj["federated_attributes"].items()
            )
            if obj.get("federated_attributes") is not None
            else None,
            "mfa_required": obj.get("mfa_required")
        })
        return _obj


