# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DeveloperKeyInputDeveloperKey(BaseModel):
    """
    DeveloperKeyInputDeveloperKey
    """ # noqa: E501
    auto_expire_tokens: Optional[StrictBool] = Field(default=None, description="Defaults to false. If true, access tokens generated by this key will expire after 1 hour.")
    email: Optional[StrictStr] = Field(default=None, description="Contact email for the key.")
    icon_url: Optional[StrictStr] = Field(default=None, description="URL for a small icon to display in key list.")
    name: Optional[StrictStr] = Field(default=None, description="The display name.")
    notes: Optional[StrictStr] = Field(default=None, description="User-provided notes about the key.")
    redirect_uri: Optional[StrictStr] = Field(default=None, description="Deprecated in favor of redirect_uris. Do not use.")
    redirect_uris: Optional[List[StrictStr]] = Field(default=None, description="List of URLs used during OAuth2 flow to validate given redirect URI.")
    vendor_code: Optional[StrictStr] = Field(default=None, description="User-specified code representing the vendor that uses the key.")
    visible: Optional[StrictBool] = Field(default=None, description="Defaults to true. If false, key will not be visible in the UI.")
    test_cluster_only: Optional[StrictBool] = Field(default=None, description="Defaults to false. If true, key is only usable in non-production environments (test, beta).")
    client_credentials_audience: Optional[StrictStr] = Field(default=None, description="Used in OAuth2 client credentials flow to specify the audience for the access token.")
    scopes: Optional[List[StrictStr]] = Field(default=None, description="List of API endpoints key is allowed to access.")
    require_scopes: Optional[StrictBool] = Field(default=None, description="If true, then token requests with this key must include scopes.")
    allow_includes: Optional[StrictBool] = Field(default=None, description="If true, allows ‘includes’ parameters in API requests that match the scopes of this key.")
    __properties: ClassVar[List[str]] = ["auto_expire_tokens", "email", "icon_url", "name", "notes", "redirect_uri", "redirect_uris", "vendor_code", "visible", "test_cluster_only", "client_credentials_audience", "scopes", "require_scopes", "allow_includes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeveloperKeyInputDeveloperKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeveloperKeyInputDeveloperKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auto_expire_tokens": obj.get("auto_expire_tokens"),
            "email": obj.get("email"),
            "icon_url": obj.get("icon_url"),
            "name": obj.get("name"),
            "notes": obj.get("notes"),
            "redirect_uri": obj.get("redirect_uri"),
            "redirect_uris": obj.get("redirect_uris"),
            "vendor_code": obj.get("vendor_code"),
            "visible": obj.get("visible"),
            "test_cluster_only": obj.get("test_cluster_only"),
            "client_credentials_audience": obj.get("client_credentials_audience"),
            "scopes": obj.get("scopes"),
            "require_scopes": obj.get("require_scopes"),
            "allow_includes": obj.get("allow_includes")
        })
        return _obj


