# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from canvas_lms_sdk.models.progress1 import Progress1
from typing import Optional, Set
from typing_extensions import Self

class GroupCategory(BaseModel):
    """
    GroupCategory
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The ID of the group category.")
    name: Optional[StrictStr] = Field(default=None, description="The display name of the group category.")
    role: Optional[StrictStr] = Field(default=None, description="Certain types of group categories have special role designations. Currently these include: 'communities', 'student_organized', 'imported'. ")
    self_signup: Optional[StrictStr] = Field(default=None, description="If enabled, users may join a group themselves. Values: 'enabled', 'restricted', or null. ")
    auto_leader: Optional[StrictStr] = Field(default=None, description="Auto-assign group leaders. Values: 'random', 'first', or null. ")
    context_type: Optional[StrictStr] = None
    account_id: Optional[StrictInt] = None
    course_id: Optional[StrictInt] = None
    group_limit: Optional[StrictInt] = None
    sis_group_category_id: Optional[StrictStr] = None
    sis_import_id: Optional[StrictInt] = None
    progress: Optional[Progress1] = None
    non_collaborative: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["id", "name", "role", "self_signup", "auto_leader", "context_type", "account_id", "course_id", "group_limit", "sis_group_category_id", "sis_import_id", "progress", "non_collaborative"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GroupCategory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of progress
        if self.progress:
            _dict['progress'] = self.progress.to_dict()
        # set to None if role (nullable) is None
        # and model_fields_set contains the field
        if self.role is None and "role" in self.model_fields_set:
            _dict['role'] = None

        # set to None if self_signup (nullable) is None
        # and model_fields_set contains the field
        if self.self_signup is None and "self_signup" in self.model_fields_set:
            _dict['self_signup'] = None

        # set to None if auto_leader (nullable) is None
        # and model_fields_set contains the field
        if self.auto_leader is None and "auto_leader" in self.model_fields_set:
            _dict['auto_leader'] = None

        # set to None if group_limit (nullable) is None
        # and model_fields_set contains the field
        if self.group_limit is None and "group_limit" in self.model_fields_set:
            _dict['group_limit'] = None

        # set to None if sis_group_category_id (nullable) is None
        # and model_fields_set contains the field
        if self.sis_group_category_id is None and "sis_group_category_id" in self.model_fields_set:
            _dict['sis_group_category_id'] = None

        # set to None if sis_import_id (nullable) is None
        # and model_fields_set contains the field
        if self.sis_import_id is None and "sis_import_id" in self.model_fields_set:
            _dict['sis_import_id'] = None

        # set to None if non_collaborative (nullable) is None
        # and model_fields_set contains the field
        if self.non_collaborative is None and "non_collaborative" in self.model_fields_set:
            _dict['non_collaborative'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GroupCategory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "role": obj.get("role"),
            "self_signup": obj.get("self_signup"),
            "auto_leader": obj.get("auto_leader"),
            "context_type": obj.get("context_type"),
            "account_id": obj.get("account_id"),
            "course_id": obj.get("course_id"),
            "group_limit": obj.get("group_limit"),
            "sis_group_category_id": obj.get("sis_group_category_id"),
            "sis_import_id": obj.get("sis_import_id"),
            "progress": Progress1.from_dict(obj["progress"]) if obj.get("progress") is not None else None,
            "non_collaborative": obj.get("non_collaborative")
        })
        return _obj


