# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from canvas_lms_sdk.models.outcome_import_data import OutcomeImportData
from canvas_lms_sdk.models.outcome_import_processing_errors_inner_inner import OutcomeImportProcessingErrorsInnerInner
from typing import Optional, Set
from typing_extensions import Self

class OutcomeImport(BaseModel):
    """
    OutcomeImport
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The unique identifier for the outcome import")
    learning_outcome_group_id: Optional[StrictInt] = Field(default=None, description="The ID of the group into which the outcomes will be imported")
    created_at: Optional[datetime] = None
    ended_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    workflow_state: Optional[StrictStr] = Field(default=None, description="The current state of the outcome import: - 'created': The outcome import has been created. - 'importing': The outcome import is currently processing. - 'succeeded': The outcome import has completed successfully. - 'failed': The outcome import failed. ")
    data: Optional[OutcomeImportData] = None
    progress: Optional[StrictStr] = Field(default=None, description="The progress of the outcome import as a percentage")
    user: Optional[Dict[str, Any]] = Field(default=None, description="The user that initiated the outcome import")
    processing_errors: Optional[List[List[OutcomeImportProcessingErrorsInnerInner]]] = Field(default=None, description="An array of row number / error message pairs (first 25 errors)")
    __properties: ClassVar[List[str]] = ["id", "learning_outcome_group_id", "created_at", "ended_at", "updated_at", "workflow_state", "data", "progress", "user", "processing_errors"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OutcomeImport from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in processing_errors (list of list)
        _items = []
        if self.processing_errors:
            for _item_processing_errors in self.processing_errors:
                if _item_processing_errors:
                    _items.append(
                         [_inner_item.to_dict() for _inner_item in _item_processing_errors if _inner_item is not None]
                    )
            _dict['processing_errors'] = _items
        # set to None if learning_outcome_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.learning_outcome_group_id is None and "learning_outcome_group_id" in self.model_fields_set:
            _dict['learning_outcome_group_id'] = None

        # set to None if ended_at (nullable) is None
        # and model_fields_set contains the field
        if self.ended_at is None and "ended_at" in self.model_fields_set:
            _dict['ended_at'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OutcomeImport from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "learning_outcome_group_id": obj.get("learning_outcome_group_id"),
            "created_at": obj.get("created_at"),
            "ended_at": obj.get("ended_at"),
            "updated_at": obj.get("updated_at"),
            "workflow_state": obj.get("workflow_state"),
            "data": OutcomeImportData.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "progress": obj.get("progress"),
            "user": obj.get("user"),
            "processing_errors": [
                    [OutcomeImportProcessingErrorsInnerInner.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["processing_errors"]
                ] if obj.get("processing_errors") is not None else None
        })
        return _obj


