# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ScoreStatistic(BaseModel):
    """
    Basic score statistics for an assignment. Included only if stats available (>=5 submissions, enabled by instructor) and 'include[]=score_statistics,submission'.
    """ # noqa: E501
    min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Minimum score. Null if N/A.")
    max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Maximum score. Null if N/A.")
    mean: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mean score. Null if N/A.")
    upper_q: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Upper quartile score. Null if N/A.")
    median: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Median score. Null if N/A.")
    lower_q: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Lower quartile score. Null if N/A.")
    __properties: ClassVar[List[str]] = ["min", "max", "mean", "upper_q", "median", "lower_q"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScoreStatistic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if min (nullable) is None
        # and model_fields_set contains the field
        if self.min is None and "min" in self.model_fields_set:
            _dict['min'] = None

        # set to None if max (nullable) is None
        # and model_fields_set contains the field
        if self.max is None and "max" in self.model_fields_set:
            _dict['max'] = None

        # set to None if mean (nullable) is None
        # and model_fields_set contains the field
        if self.mean is None and "mean" in self.model_fields_set:
            _dict['mean'] = None

        # set to None if upper_q (nullable) is None
        # and model_fields_set contains the field
        if self.upper_q is None and "upper_q" in self.model_fields_set:
            _dict['upper_q'] = None

        # set to None if median (nullable) is None
        # and model_fields_set contains the field
        if self.median is None and "median" in self.model_fields_set:
            _dict['median'] = None

        # set to None if lower_q (nullable) is None
        # and model_fields_set contains the field
        if self.lower_q is None and "lower_q" in self.model_fields_set:
            _dict['lower_q'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScoreStatistic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "min": obj.get("min"),
            "max": obj.get("max"),
            "mean": obj.get("mean"),
            "upper_q": obj.get("upper_q"),
            "median": obj.get("median"),
            "lower_q": obj.get("lower_q")
        })
        return _obj


