# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SSOSettings(BaseModel):
    """
    SSOSettings
    """ # noqa: E501
    login_handle_name: Optional[StrictStr] = None
    change_password_url: Optional[StrictStr] = None
    auth_discovery_url: Optional[StrictStr] = None
    unknown_user_url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["login_handle_name", "change_password_url", "auth_discovery_url", "unknown_user_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SSOSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if change_password_url (nullable) is None
        # and model_fields_set contains the field
        if self.change_password_url is None and "change_password_url" in self.model_fields_set:
            _dict['change_password_url'] = None

        # set to None if auth_discovery_url (nullable) is None
        # and model_fields_set contains the field
        if self.auth_discovery_url is None and "auth_discovery_url" in self.model_fields_set:
            _dict['auth_discovery_url'] = None

        # set to None if unknown_user_url (nullable) is None
        # and model_fields_set contains the field
        if self.unknown_user_url is None and "unknown_user_url" in self.model_fields_set:
            _dict['unknown_user_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SSOSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "login_handle_name": obj.get("login_handle_name"),
            "change_password_url": obj.get("change_password_url"),
            "auth_discovery_url": obj.get("auth_discovery_url"),
            "unknown_user_url": obj.get("unknown_user_url")
        })
        return _obj


