# coding: utf-8

"""
    User Observees API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TurnitinSettings(BaseModel):
    """
    Settings for Turnitin originality checking.
    """ # noqa: E501
    originality_report_visibility: Optional[StrictStr] = None
    s_paper_check: Optional[StrictBool] = Field(default=None, description="Check against student paper repository.")
    internet_check: Optional[StrictBool] = Field(default=None, description="Check against internet sources.")
    journal_check: Optional[StrictBool] = Field(default=None, description="Check against journals, periodicals, publications.")
    exclude_biblio: Optional[StrictBool] = Field(default=None, description="Exclude bibliographic materials.")
    exclude_quoted: Optional[StrictBool] = Field(default=None, description="Exclude quoted materials.")
    exclude_small_matches_type: Optional[StrictStr] = None
    exclude_small_matches_value: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["originality_report_visibility", "s_paper_check", "internet_check", "journal_check", "exclude_biblio", "exclude_quoted", "exclude_small_matches_type", "exclude_small_matches_value"]

    @field_validator('originality_report_visibility')
    def originality_report_visibility_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['immediate', 'after_grading', 'after_due_date', 'never']):
            raise ValueError("must be one of enum values ('immediate', 'after_grading', 'after_due_date', 'never')")
        return value

    @field_validator('exclude_small_matches_type')
    def exclude_small_matches_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['percent', 'words']):
            raise ValueError("must be one of enum values ('percent', 'words')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TurnitinSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if exclude_small_matches_type (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_small_matches_type is None and "exclude_small_matches_type" in self.model_fields_set:
            _dict['exclude_small_matches_type'] = None

        # set to None if exclude_small_matches_value (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_small_matches_value is None and "exclude_small_matches_value" in self.model_fields_set:
            _dict['exclude_small_matches_value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TurnitinSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "originality_report_visibility": obj.get("originality_report_visibility"),
            "s_paper_check": obj.get("s_paper_check"),
            "internet_check": obj.get("internet_check"),
            "journal_check": obj.get("journal_check"),
            "exclude_biblio": obj.get("exclude_biblio"),
            "exclude_quoted": obj.get("exclude_quoted"),
            "exclude_small_matches_type": obj.get("exclude_small_matches_type"),
            "exclude_small_matches_value": obj.get("exclude_small_matches_value")
        })
        return _obj


